// Code generated by protoc-gen-go. DO NOT EDIT.
// source: billingd.proto

package api_billingd_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckHealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckHealthRequest) Reset()         { *m = CheckHealthRequest{} }
func (m *CheckHealthRequest) String() string { return proto.CompactTextString(m) }
func (*CheckHealthRequest) ProtoMessage()    {}
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{0}
}

func (m *CheckHealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckHealthRequest.Unmarshal(m, b)
}
func (m *CheckHealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckHealthRequest.Marshal(b, m, deterministic)
}
func (m *CheckHealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckHealthRequest.Merge(m, src)
}
func (m *CheckHealthRequest) XXX_Size() int {
	return xxx_messageInfo_CheckHealthRequest.Size(m)
}
func (m *CheckHealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckHealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckHealthRequest proto.InternalMessageInfo

type CheckHealthResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckHealthResponse) Reset()         { *m = CheckHealthResponse{} }
func (m *CheckHealthResponse) String() string { return proto.CompactTextString(m) }
func (*CheckHealthResponse) ProtoMessage()    {}
func (*CheckHealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{1}
}

func (m *CheckHealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckHealthResponse.Unmarshal(m, b)
}
func (m *CheckHealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckHealthResponse.Marshal(b, m, deterministic)
}
func (m *CheckHealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckHealthResponse.Merge(m, src)
}
func (m *CheckHealthResponse) XXX_Size() int {
	return xxx_messageInfo_CheckHealthResponse.Size(m)
}
func (m *CheckHealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckHealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckHealthResponse proto.InternalMessageInfo

type CreateCustomerRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerRequest) Reset()         { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()    {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{2}
}

func (m *CreateCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerRequest.Unmarshal(m, b)
}
func (m *CreateCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerRequest.Marshal(b, m, deterministic)
}
func (m *CreateCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerRequest.Merge(m, src)
}
func (m *CreateCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerRequest.Size(m)
}
func (m *CreateCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerRequest proto.InternalMessageInfo

func (m *CreateCustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateCustomerResponse struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerResponse) Reset()         { *m = CreateCustomerResponse{} }
func (m *CreateCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerResponse) ProtoMessage()    {}
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{3}
}

func (m *CreateCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerResponse.Unmarshal(m, b)
}
func (m *CreateCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerResponse.Marshal(b, m, deterministic)
}
func (m *CreateCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerResponse.Merge(m, src)
}
func (m *CreateCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerResponse.Size(m)
}
func (m *CreateCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerResponse proto.InternalMessageInfo

func (m *CreateCustomerResponse) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type GetCustomerRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerRequest) Reset()         { *m = GetCustomerRequest{} }
func (m *GetCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomerRequest) ProtoMessage()    {}
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{4}
}

func (m *GetCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerRequest.Unmarshal(m, b)
}
func (m *GetCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerRequest.Marshal(b, m, deterministic)
}
func (m *GetCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerRequest.Merge(m, src)
}
func (m *GetCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomerRequest.Size(m)
}
func (m *GetCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerRequest proto.InternalMessageInfo

func (m *GetCustomerRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type GetCustomerResponse struct {
	Balance              int64    `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Billable             bool     `protobuf:"varint,2,opt,name=billable,proto3" json:"billable,omitempty"`
	Delinquent           bool     `protobuf:"varint,3,opt,name=delinquent,proto3" json:"delinquent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerResponse) Reset()         { *m = GetCustomerResponse{} }
func (m *GetCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*GetCustomerResponse) ProtoMessage()    {}
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{5}
}

func (m *GetCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerResponse.Unmarshal(m, b)
}
func (m *GetCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerResponse.Marshal(b, m, deterministic)
}
func (m *GetCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerResponse.Merge(m, src)
}
func (m *GetCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_GetCustomerResponse.Size(m)
}
func (m *GetCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerResponse proto.InternalMessageInfo

func (m *GetCustomerResponse) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *GetCustomerResponse) GetBillable() bool {
	if m != nil {
		return m.Billable
	}
	return false
}

func (m *GetCustomerResponse) GetDelinquent() bool {
	if m != nil {
		return m.Delinquent
	}
	return false
}

type DeleteCustomerRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomerRequest) Reset()         { *m = DeleteCustomerRequest{} }
func (m *DeleteCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomerRequest) ProtoMessage()    {}
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{6}
}

func (m *DeleteCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomerRequest.Unmarshal(m, b)
}
func (m *DeleteCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomerRequest.Merge(m, src)
}
func (m *DeleteCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomerRequest.Size(m)
}
func (m *DeleteCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomerRequest proto.InternalMessageInfo

func (m *DeleteCustomerRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type DeleteCustomerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomerResponse) Reset()         { *m = DeleteCustomerResponse{} }
func (m *DeleteCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomerResponse) ProtoMessage()    {}
func (*DeleteCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{7}
}

func (m *DeleteCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomerResponse.Unmarshal(m, b)
}
func (m *DeleteCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomerResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomerResponse.Merge(m, src)
}
func (m *DeleteCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomerResponse.Size(m)
}
func (m *DeleteCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomerResponse proto.InternalMessageInfo

type AddCardRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCardRequest) Reset()         { *m = AddCardRequest{} }
func (m *AddCardRequest) String() string { return proto.CompactTextString(m) }
func (*AddCardRequest) ProtoMessage()    {}
func (*AddCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{8}
}

func (m *AddCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCardRequest.Unmarshal(m, b)
}
func (m *AddCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCardRequest.Marshal(b, m, deterministic)
}
func (m *AddCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCardRequest.Merge(m, src)
}
func (m *AddCardRequest) XXX_Size() int {
	return xxx_messageInfo_AddCardRequest.Size(m)
}
func (m *AddCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCardRequest proto.InternalMessageInfo

func (m *AddCardRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *AddCardRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AddCardResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCardResponse) Reset()         { *m = AddCardResponse{} }
func (m *AddCardResponse) String() string { return proto.CompactTextString(m) }
func (*AddCardResponse) ProtoMessage()    {}
func (*AddCardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{9}
}

func (m *AddCardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCardResponse.Unmarshal(m, b)
}
func (m *AddCardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCardResponse.Marshal(b, m, deterministic)
}
func (m *AddCardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCardResponse.Merge(m, src)
}
func (m *AddCardResponse) XXX_Size() int {
	return xxx_messageInfo_AddCardResponse.Size(m)
}
func (m *AddCardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCardResponse proto.InternalMessageInfo

type IncStoredDataRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	IncSize              int64    `protobuf:"varint,2,opt,name=inc_size,json=incSize,proto3" json:"inc_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncStoredDataRequest) Reset()         { *m = IncStoredDataRequest{} }
func (m *IncStoredDataRequest) String() string { return proto.CompactTextString(m) }
func (*IncStoredDataRequest) ProtoMessage()    {}
func (*IncStoredDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{10}
}

func (m *IncStoredDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncStoredDataRequest.Unmarshal(m, b)
}
func (m *IncStoredDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncStoredDataRequest.Marshal(b, m, deterministic)
}
func (m *IncStoredDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncStoredDataRequest.Merge(m, src)
}
func (m *IncStoredDataRequest) XXX_Size() int {
	return xxx_messageInfo_IncStoredDataRequest.Size(m)
}
func (m *IncStoredDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncStoredDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncStoredDataRequest proto.InternalMessageInfo

func (m *IncStoredDataRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *IncStoredDataRequest) GetIncSize() int64 {
	if m != nil {
		return m.IncSize
	}
	return 0
}

type IncStoredDataResponse struct {
	Units                int64    `protobuf:"varint,1,opt,name=units,proto3" json:"units,omitempty"`
	TotalSize            int64    `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncStoredDataResponse) Reset()         { *m = IncStoredDataResponse{} }
func (m *IncStoredDataResponse) String() string { return proto.CompactTextString(m) }
func (*IncStoredDataResponse) ProtoMessage()    {}
func (*IncStoredDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{11}
}

func (m *IncStoredDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncStoredDataResponse.Unmarshal(m, b)
}
func (m *IncStoredDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncStoredDataResponse.Marshal(b, m, deterministic)
}
func (m *IncStoredDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncStoredDataResponse.Merge(m, src)
}
func (m *IncStoredDataResponse) XXX_Size() int {
	return xxx_messageInfo_IncStoredDataResponse.Size(m)
}
func (m *IncStoredDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncStoredDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncStoredDataResponse proto.InternalMessageInfo

func (m *IncStoredDataResponse) GetUnits() int64 {
	if m != nil {
		return m.Units
	}
	return 0
}

func (m *IncStoredDataResponse) GetTotalSize() int64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

type GetStoredDataRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStoredDataRequest) Reset()         { *m = GetStoredDataRequest{} }
func (m *GetStoredDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetStoredDataRequest) ProtoMessage()    {}
func (*GetStoredDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{12}
}

func (m *GetStoredDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStoredDataRequest.Unmarshal(m, b)
}
func (m *GetStoredDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStoredDataRequest.Marshal(b, m, deterministic)
}
func (m *GetStoredDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStoredDataRequest.Merge(m, src)
}
func (m *GetStoredDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetStoredDataRequest.Size(m)
}
func (m *GetStoredDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStoredDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStoredDataRequest proto.InternalMessageInfo

func (m *GetStoredDataRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type GetStoredDataResponse struct {
	Units                int64        `protobuf:"varint,1,opt,name=units,proto3" json:"units,omitempty"`
	TotalSize            int64        `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	FreeSize             int64        `protobuf:"varint,3,opt,name=free_size,json=freeSize,proto3" json:"free_size,omitempty"`
	Period               *UsagePeriod `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetStoredDataResponse) Reset()         { *m = GetStoredDataResponse{} }
func (m *GetStoredDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetStoredDataResponse) ProtoMessage()    {}
func (*GetStoredDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{13}
}

func (m *GetStoredDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStoredDataResponse.Unmarshal(m, b)
}
func (m *GetStoredDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStoredDataResponse.Marshal(b, m, deterministic)
}
func (m *GetStoredDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStoredDataResponse.Merge(m, src)
}
func (m *GetStoredDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetStoredDataResponse.Size(m)
}
func (m *GetStoredDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStoredDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStoredDataResponse proto.InternalMessageInfo

func (m *GetStoredDataResponse) GetUnits() int64 {
	if m != nil {
		return m.Units
	}
	return 0
}

func (m *GetStoredDataResponse) GetTotalSize() int64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *GetStoredDataResponse) GetFreeSize() int64 {
	if m != nil {
		return m.FreeSize
	}
	return 0
}

func (m *GetStoredDataResponse) GetPeriod() *UsagePeriod {
	if m != nil {
		return m.Period
	}
	return nil
}

type IncNetworkEgressRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	IncSize              int64    `protobuf:"varint,2,opt,name=inc_size,json=incSize,proto3" json:"inc_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncNetworkEgressRequest) Reset()         { *m = IncNetworkEgressRequest{} }
func (m *IncNetworkEgressRequest) String() string { return proto.CompactTextString(m) }
func (*IncNetworkEgressRequest) ProtoMessage()    {}
func (*IncNetworkEgressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{14}
}

func (m *IncNetworkEgressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncNetworkEgressRequest.Unmarshal(m, b)
}
func (m *IncNetworkEgressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncNetworkEgressRequest.Marshal(b, m, deterministic)
}
func (m *IncNetworkEgressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncNetworkEgressRequest.Merge(m, src)
}
func (m *IncNetworkEgressRequest) XXX_Size() int {
	return xxx_messageInfo_IncNetworkEgressRequest.Size(m)
}
func (m *IncNetworkEgressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncNetworkEgressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncNetworkEgressRequest proto.InternalMessageInfo

func (m *IncNetworkEgressRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *IncNetworkEgressRequest) GetIncSize() int64 {
	if m != nil {
		return m.IncSize
	}
	return 0
}

type IncNetworkEgressResponse struct {
	AddedUnits           int64    `protobuf:"varint,1,opt,name=added_units,json=addedUnits,proto3" json:"added_units,omitempty"`
	SubUnits             int64    `protobuf:"varint,2,opt,name=sub_units,json=subUnits,proto3" json:"sub_units,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncNetworkEgressResponse) Reset()         { *m = IncNetworkEgressResponse{} }
func (m *IncNetworkEgressResponse) String() string { return proto.CompactTextString(m) }
func (*IncNetworkEgressResponse) ProtoMessage()    {}
func (*IncNetworkEgressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{15}
}

func (m *IncNetworkEgressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncNetworkEgressResponse.Unmarshal(m, b)
}
func (m *IncNetworkEgressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncNetworkEgressResponse.Marshal(b, m, deterministic)
}
func (m *IncNetworkEgressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncNetworkEgressResponse.Merge(m, src)
}
func (m *IncNetworkEgressResponse) XXX_Size() int {
	return xxx_messageInfo_IncNetworkEgressResponse.Size(m)
}
func (m *IncNetworkEgressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncNetworkEgressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncNetworkEgressResponse proto.InternalMessageInfo

func (m *IncNetworkEgressResponse) GetAddedUnits() int64 {
	if m != nil {
		return m.AddedUnits
	}
	return 0
}

func (m *IncNetworkEgressResponse) GetSubUnits() int64 {
	if m != nil {
		return m.SubUnits
	}
	return 0
}

type GetNetworkEgressRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNetworkEgressRequest) Reset()         { *m = GetNetworkEgressRequest{} }
func (m *GetNetworkEgressRequest) String() string { return proto.CompactTextString(m) }
func (*GetNetworkEgressRequest) ProtoMessage()    {}
func (*GetNetworkEgressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{16}
}

func (m *GetNetworkEgressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNetworkEgressRequest.Unmarshal(m, b)
}
func (m *GetNetworkEgressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNetworkEgressRequest.Marshal(b, m, deterministic)
}
func (m *GetNetworkEgressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNetworkEgressRequest.Merge(m, src)
}
func (m *GetNetworkEgressRequest) XXX_Size() int {
	return xxx_messageInfo_GetNetworkEgressRequest.Size(m)
}
func (m *GetNetworkEgressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNetworkEgressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNetworkEgressRequest proto.InternalMessageInfo

func (m *GetNetworkEgressRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type GetNetworkEgressResponse struct {
	Units                int64        `protobuf:"varint,1,opt,name=units,proto3" json:"units,omitempty"`
	SubUnits             int64        `protobuf:"varint,2,opt,name=sub_units,json=subUnits,proto3" json:"sub_units,omitempty"`
	FreeUnits            int64        `protobuf:"varint,3,opt,name=free_units,json=freeUnits,proto3" json:"free_units,omitempty"`
	Period               *UsagePeriod `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetNetworkEgressResponse) Reset()         { *m = GetNetworkEgressResponse{} }
func (m *GetNetworkEgressResponse) String() string { return proto.CompactTextString(m) }
func (*GetNetworkEgressResponse) ProtoMessage()    {}
func (*GetNetworkEgressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{17}
}

func (m *GetNetworkEgressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNetworkEgressResponse.Unmarshal(m, b)
}
func (m *GetNetworkEgressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNetworkEgressResponse.Marshal(b, m, deterministic)
}
func (m *GetNetworkEgressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNetworkEgressResponse.Merge(m, src)
}
func (m *GetNetworkEgressResponse) XXX_Size() int {
	return xxx_messageInfo_GetNetworkEgressResponse.Size(m)
}
func (m *GetNetworkEgressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNetworkEgressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNetworkEgressResponse proto.InternalMessageInfo

func (m *GetNetworkEgressResponse) GetUnits() int64 {
	if m != nil {
		return m.Units
	}
	return 0
}

func (m *GetNetworkEgressResponse) GetSubUnits() int64 {
	if m != nil {
		return m.SubUnits
	}
	return 0
}

func (m *GetNetworkEgressResponse) GetFreeUnits() int64 {
	if m != nil {
		return m.FreeUnits
	}
	return 0
}

func (m *GetNetworkEgressResponse) GetPeriod() *UsagePeriod {
	if m != nil {
		return m.Period
	}
	return nil
}

type IncInstanceReadsRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	IncCount             int64    `protobuf:"varint,2,opt,name=inc_count,json=incCount,proto3" json:"inc_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncInstanceReadsRequest) Reset()         { *m = IncInstanceReadsRequest{} }
func (m *IncInstanceReadsRequest) String() string { return proto.CompactTextString(m) }
func (*IncInstanceReadsRequest) ProtoMessage()    {}
func (*IncInstanceReadsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{18}
}

func (m *IncInstanceReadsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncInstanceReadsRequest.Unmarshal(m, b)
}
func (m *IncInstanceReadsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncInstanceReadsRequest.Marshal(b, m, deterministic)
}
func (m *IncInstanceReadsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncInstanceReadsRequest.Merge(m, src)
}
func (m *IncInstanceReadsRequest) XXX_Size() int {
	return xxx_messageInfo_IncInstanceReadsRequest.Size(m)
}
func (m *IncInstanceReadsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncInstanceReadsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncInstanceReadsRequest proto.InternalMessageInfo

func (m *IncInstanceReadsRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *IncInstanceReadsRequest) GetIncCount() int64 {
	if m != nil {
		return m.IncCount
	}
	return 0
}

type IncInstanceReadsResponse struct {
	AddedUnits           int64    `protobuf:"varint,1,opt,name=added_units,json=addedUnits,proto3" json:"added_units,omitempty"`
	SubUnits             int64    `protobuf:"varint,2,opt,name=sub_units,json=subUnits,proto3" json:"sub_units,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncInstanceReadsResponse) Reset()         { *m = IncInstanceReadsResponse{} }
func (m *IncInstanceReadsResponse) String() string { return proto.CompactTextString(m) }
func (*IncInstanceReadsResponse) ProtoMessage()    {}
func (*IncInstanceReadsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{19}
}

func (m *IncInstanceReadsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncInstanceReadsResponse.Unmarshal(m, b)
}
func (m *IncInstanceReadsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncInstanceReadsResponse.Marshal(b, m, deterministic)
}
func (m *IncInstanceReadsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncInstanceReadsResponse.Merge(m, src)
}
func (m *IncInstanceReadsResponse) XXX_Size() int {
	return xxx_messageInfo_IncInstanceReadsResponse.Size(m)
}
func (m *IncInstanceReadsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncInstanceReadsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncInstanceReadsResponse proto.InternalMessageInfo

func (m *IncInstanceReadsResponse) GetAddedUnits() int64 {
	if m != nil {
		return m.AddedUnits
	}
	return 0
}

func (m *IncInstanceReadsResponse) GetSubUnits() int64 {
	if m != nil {
		return m.SubUnits
	}
	return 0
}

type GetInstanceReadsRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInstanceReadsRequest) Reset()         { *m = GetInstanceReadsRequest{} }
func (m *GetInstanceReadsRequest) String() string { return proto.CompactTextString(m) }
func (*GetInstanceReadsRequest) ProtoMessage()    {}
func (*GetInstanceReadsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{20}
}

func (m *GetInstanceReadsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInstanceReadsRequest.Unmarshal(m, b)
}
func (m *GetInstanceReadsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInstanceReadsRequest.Marshal(b, m, deterministic)
}
func (m *GetInstanceReadsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInstanceReadsRequest.Merge(m, src)
}
func (m *GetInstanceReadsRequest) XXX_Size() int {
	return xxx_messageInfo_GetInstanceReadsRequest.Size(m)
}
func (m *GetInstanceReadsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInstanceReadsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInstanceReadsRequest proto.InternalMessageInfo

func (m *GetInstanceReadsRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type GetInstanceReadsResponse struct {
	Units                int64        `protobuf:"varint,1,opt,name=units,proto3" json:"units,omitempty"`
	SubUnits             int64        `protobuf:"varint,2,opt,name=sub_units,json=subUnits,proto3" json:"sub_units,omitempty"`
	FreeUnits            int64        `protobuf:"varint,3,opt,name=free_units,json=freeUnits,proto3" json:"free_units,omitempty"`
	Period               *UsagePeriod `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetInstanceReadsResponse) Reset()         { *m = GetInstanceReadsResponse{} }
func (m *GetInstanceReadsResponse) String() string { return proto.CompactTextString(m) }
func (*GetInstanceReadsResponse) ProtoMessage()    {}
func (*GetInstanceReadsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{21}
}

func (m *GetInstanceReadsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInstanceReadsResponse.Unmarshal(m, b)
}
func (m *GetInstanceReadsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInstanceReadsResponse.Marshal(b, m, deterministic)
}
func (m *GetInstanceReadsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInstanceReadsResponse.Merge(m, src)
}
func (m *GetInstanceReadsResponse) XXX_Size() int {
	return xxx_messageInfo_GetInstanceReadsResponse.Size(m)
}
func (m *GetInstanceReadsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInstanceReadsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInstanceReadsResponse proto.InternalMessageInfo

func (m *GetInstanceReadsResponse) GetUnits() int64 {
	if m != nil {
		return m.Units
	}
	return 0
}

func (m *GetInstanceReadsResponse) GetSubUnits() int64 {
	if m != nil {
		return m.SubUnits
	}
	return 0
}

func (m *GetInstanceReadsResponse) GetFreeUnits() int64 {
	if m != nil {
		return m.FreeUnits
	}
	return 0
}

func (m *GetInstanceReadsResponse) GetPeriod() *UsagePeriod {
	if m != nil {
		return m.Period
	}
	return nil
}

type IncInstanceWritesRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	IncCount             int64    `protobuf:"varint,2,opt,name=inc_count,json=incCount,proto3" json:"inc_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncInstanceWritesRequest) Reset()         { *m = IncInstanceWritesRequest{} }
func (m *IncInstanceWritesRequest) String() string { return proto.CompactTextString(m) }
func (*IncInstanceWritesRequest) ProtoMessage()    {}
func (*IncInstanceWritesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{22}
}

func (m *IncInstanceWritesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncInstanceWritesRequest.Unmarshal(m, b)
}
func (m *IncInstanceWritesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncInstanceWritesRequest.Marshal(b, m, deterministic)
}
func (m *IncInstanceWritesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncInstanceWritesRequest.Merge(m, src)
}
func (m *IncInstanceWritesRequest) XXX_Size() int {
	return xxx_messageInfo_IncInstanceWritesRequest.Size(m)
}
func (m *IncInstanceWritesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncInstanceWritesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncInstanceWritesRequest proto.InternalMessageInfo

func (m *IncInstanceWritesRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *IncInstanceWritesRequest) GetIncCount() int64 {
	if m != nil {
		return m.IncCount
	}
	return 0
}

type IncInstanceWritesResponse struct {
	AddedUnits           int64    `protobuf:"varint,1,opt,name=added_units,json=addedUnits,proto3" json:"added_units,omitempty"`
	SubUnits             int64    `protobuf:"varint,2,opt,name=sub_units,json=subUnits,proto3" json:"sub_units,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncInstanceWritesResponse) Reset()         { *m = IncInstanceWritesResponse{} }
func (m *IncInstanceWritesResponse) String() string { return proto.CompactTextString(m) }
func (*IncInstanceWritesResponse) ProtoMessage()    {}
func (*IncInstanceWritesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{23}
}

func (m *IncInstanceWritesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncInstanceWritesResponse.Unmarshal(m, b)
}
func (m *IncInstanceWritesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncInstanceWritesResponse.Marshal(b, m, deterministic)
}
func (m *IncInstanceWritesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncInstanceWritesResponse.Merge(m, src)
}
func (m *IncInstanceWritesResponse) XXX_Size() int {
	return xxx_messageInfo_IncInstanceWritesResponse.Size(m)
}
func (m *IncInstanceWritesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncInstanceWritesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncInstanceWritesResponse proto.InternalMessageInfo

func (m *IncInstanceWritesResponse) GetAddedUnits() int64 {
	if m != nil {
		return m.AddedUnits
	}
	return 0
}

func (m *IncInstanceWritesResponse) GetSubUnits() int64 {
	if m != nil {
		return m.SubUnits
	}
	return 0
}

type GetInstanceWritesRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInstanceWritesRequest) Reset()         { *m = GetInstanceWritesRequest{} }
func (m *GetInstanceWritesRequest) String() string { return proto.CompactTextString(m) }
func (*GetInstanceWritesRequest) ProtoMessage()    {}
func (*GetInstanceWritesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{24}
}

func (m *GetInstanceWritesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInstanceWritesRequest.Unmarshal(m, b)
}
func (m *GetInstanceWritesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInstanceWritesRequest.Marshal(b, m, deterministic)
}
func (m *GetInstanceWritesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInstanceWritesRequest.Merge(m, src)
}
func (m *GetInstanceWritesRequest) XXX_Size() int {
	return xxx_messageInfo_GetInstanceWritesRequest.Size(m)
}
func (m *GetInstanceWritesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInstanceWritesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInstanceWritesRequest proto.InternalMessageInfo

func (m *GetInstanceWritesRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type GetInstanceWritesResponse struct {
	Units                int64        `protobuf:"varint,1,opt,name=units,proto3" json:"units,omitempty"`
	SubUnits             int64        `protobuf:"varint,2,opt,name=sub_units,json=subUnits,proto3" json:"sub_units,omitempty"`
	FreeUnits            int64        `protobuf:"varint,3,opt,name=free_units,json=freeUnits,proto3" json:"free_units,omitempty"`
	Period               *UsagePeriod `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetInstanceWritesResponse) Reset()         { *m = GetInstanceWritesResponse{} }
func (m *GetInstanceWritesResponse) String() string { return proto.CompactTextString(m) }
func (*GetInstanceWritesResponse) ProtoMessage()    {}
func (*GetInstanceWritesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{25}
}

func (m *GetInstanceWritesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInstanceWritesResponse.Unmarshal(m, b)
}
func (m *GetInstanceWritesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInstanceWritesResponse.Marshal(b, m, deterministic)
}
func (m *GetInstanceWritesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInstanceWritesResponse.Merge(m, src)
}
func (m *GetInstanceWritesResponse) XXX_Size() int {
	return xxx_messageInfo_GetInstanceWritesResponse.Size(m)
}
func (m *GetInstanceWritesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInstanceWritesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInstanceWritesResponse proto.InternalMessageInfo

func (m *GetInstanceWritesResponse) GetUnits() int64 {
	if m != nil {
		return m.Units
	}
	return 0
}

func (m *GetInstanceWritesResponse) GetSubUnits() int64 {
	if m != nil {
		return m.SubUnits
	}
	return 0
}

func (m *GetInstanceWritesResponse) GetFreeUnits() int64 {
	if m != nil {
		return m.FreeUnits
	}
	return 0
}

func (m *GetInstanceWritesResponse) GetPeriod() *UsagePeriod {
	if m != nil {
		return m.Period
	}
	return nil
}

type UsagePeriod struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsagePeriod) Reset()         { *m = UsagePeriod{} }
func (m *UsagePeriod) String() string { return proto.CompactTextString(m) }
func (*UsagePeriod) ProtoMessage()    {}
func (*UsagePeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_68f8d6015d3759a6, []int{26}
}

func (m *UsagePeriod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsagePeriod.Unmarshal(m, b)
}
func (m *UsagePeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsagePeriod.Marshal(b, m, deterministic)
}
func (m *UsagePeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsagePeriod.Merge(m, src)
}
func (m *UsagePeriod) XXX_Size() int {
	return xxx_messageInfo_UsagePeriod.Size(m)
}
func (m *UsagePeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_UsagePeriod.DiscardUnknown(m)
}

var xxx_messageInfo_UsagePeriod proto.InternalMessageInfo

func (m *UsagePeriod) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *UsagePeriod) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func init() {
	proto.RegisterType((*CheckHealthRequest)(nil), "api.billingd.pb.CheckHealthRequest")
	proto.RegisterType((*CheckHealthResponse)(nil), "api.billingd.pb.CheckHealthResponse")
	proto.RegisterType((*CreateCustomerRequest)(nil), "api.billingd.pb.CreateCustomerRequest")
	proto.RegisterType((*CreateCustomerResponse)(nil), "api.billingd.pb.CreateCustomerResponse")
	proto.RegisterType((*GetCustomerRequest)(nil), "api.billingd.pb.GetCustomerRequest")
	proto.RegisterType((*GetCustomerResponse)(nil), "api.billingd.pb.GetCustomerResponse")
	proto.RegisterType((*DeleteCustomerRequest)(nil), "api.billingd.pb.DeleteCustomerRequest")
	proto.RegisterType((*DeleteCustomerResponse)(nil), "api.billingd.pb.DeleteCustomerResponse")
	proto.RegisterType((*AddCardRequest)(nil), "api.billingd.pb.AddCardRequest")
	proto.RegisterType((*AddCardResponse)(nil), "api.billingd.pb.AddCardResponse")
	proto.RegisterType((*IncStoredDataRequest)(nil), "api.billingd.pb.IncStoredDataRequest")
	proto.RegisterType((*IncStoredDataResponse)(nil), "api.billingd.pb.IncStoredDataResponse")
	proto.RegisterType((*GetStoredDataRequest)(nil), "api.billingd.pb.GetStoredDataRequest")
	proto.RegisterType((*GetStoredDataResponse)(nil), "api.billingd.pb.GetStoredDataResponse")
	proto.RegisterType((*IncNetworkEgressRequest)(nil), "api.billingd.pb.IncNetworkEgressRequest")
	proto.RegisterType((*IncNetworkEgressResponse)(nil), "api.billingd.pb.IncNetworkEgressResponse")
	proto.RegisterType((*GetNetworkEgressRequest)(nil), "api.billingd.pb.GetNetworkEgressRequest")
	proto.RegisterType((*GetNetworkEgressResponse)(nil), "api.billingd.pb.GetNetworkEgressResponse")
	proto.RegisterType((*IncInstanceReadsRequest)(nil), "api.billingd.pb.IncInstanceReadsRequest")
	proto.RegisterType((*IncInstanceReadsResponse)(nil), "api.billingd.pb.IncInstanceReadsResponse")
	proto.RegisterType((*GetInstanceReadsRequest)(nil), "api.billingd.pb.GetInstanceReadsRequest")
	proto.RegisterType((*GetInstanceReadsResponse)(nil), "api.billingd.pb.GetInstanceReadsResponse")
	proto.RegisterType((*IncInstanceWritesRequest)(nil), "api.billingd.pb.IncInstanceWritesRequest")
	proto.RegisterType((*IncInstanceWritesResponse)(nil), "api.billingd.pb.IncInstanceWritesResponse")
	proto.RegisterType((*GetInstanceWritesRequest)(nil), "api.billingd.pb.GetInstanceWritesRequest")
	proto.RegisterType((*GetInstanceWritesResponse)(nil), "api.billingd.pb.GetInstanceWritesResponse")
	proto.RegisterType((*UsagePeriod)(nil), "api.billingd.pb.UsagePeriod")
}

func init() { proto.RegisterFile("billingd.proto", fileDescriptor_68f8d6015d3759a6) }

var fileDescriptor_68f8d6015d3759a6 = []byte{
	// 809 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x5b, 0x4f, 0x1b, 0x47,
	0x14, 0xb6, 0xeb, 0x02, 0xf6, 0xb1, 0xca, 0x65, 0xb0, 0x61, 0x31, 0x6d, 0xb1, 0xa6, 0x2d, 0x75,
	0x2b, 0xd5, 0x0f, 0x34, 0x28, 0xb7, 0x27, 0x64, 0x22, 0xc7, 0x52, 0x84, 0xd0, 0x22, 0x44, 0xc2,
	0x0b, 0x19, 0xef, 0x9e, 0xc0, 0xc8, 0xcb, 0xac, 0xd9, 0x1d, 0x27, 0x12, 0x7f, 0x26, 0x52, 0xf2,
	0x96, 0x5f, 0x19, 0xed, 0xec, 0xda, 0xec, 0x65, 0x7c, 0x81, 0xf8, 0x81, 0x37, 0xcf, 0x99, 0x73,
	0xf9, 0xce, 0xf9, 0xb4, 0x73, 0x3e, 0xc3, 0x72, 0x97, 0x3b, 0x0e, 0x17, 0x97, 0x76, 0xb3, 0xef,
	0xb9, 0xd2, 0x25, 0x2b, 0xac, 0xcf, 0x9b, 0x77, 0xb6, 0x2e, 0xad, 0x00, 0x69, 0x5d, 0xa1, 0xd5,
	0x7b, 0x8d, 0xcc, 0x91, 0x57, 0x26, 0xde, 0x0c, 0xd0, 0x97, 0xb4, 0x0a, 0xeb, 0x09, 0xab, 0xdf,
	0x77, 0x85, 0x8f, 0xf4, 0x3f, 0xa8, 0xb6, 0x3c, 0x64, 0x12, 0x5b, 0x03, 0x5f, 0xba, 0xd7, 0xe8,
	0x45, 0xfe, 0xa4, 0x02, 0x0b, 0x78, 0xcd, 0xb8, 0x63, 0xe4, 0xeb, 0xf9, 0x46, 0xc9, 0x0c, 0x0f,
	0xf4, 0x39, 0x6c, 0xa4, 0xdd, 0xc3, 0x44, 0x64, 0x07, 0xca, 0x56, 0x64, 0xbb, 0xe0, 0x76, 0x14,
	0x05, 0x43, 0x53, 0xc7, 0xa6, 0xfb, 0x40, 0xda, 0x28, 0xd3, 0x65, 0xa6, 0x86, 0xf5, 0x60, 0x3d,
	0x11, 0x16, 0x95, 0x33, 0x60, 0xa9, 0xcb, 0x1c, 0x26, 0x2c, 0x54, 0x31, 0x05, 0x73, 0x78, 0x24,
	0x35, 0x28, 0x06, 0xd3, 0x60, 0x5d, 0x07, 0x8d, 0x9f, 0xea, 0xf9, 0x46, 0xd1, 0x1c, 0x9d, 0xc9,
	0xef, 0x00, 0x36, 0x3a, 0x5c, 0xdc, 0x0c, 0x50, 0x48, 0xa3, 0xa0, 0x6e, 0x63, 0x16, 0xfa, 0x0c,
	0xaa, 0x87, 0xe8, 0x60, 0x76, 0x1a, 0x53, 0x61, 0x1a, 0xb0, 0x91, 0x8e, 0x8c, 0x26, 0xdc, 0x86,
	0xe5, 0x03, 0xdb, 0x6e, 0x31, 0xcf, 0x9e, 0x35, 0x59, 0x30, 0x7b, 0xe9, 0xf6, 0x50, 0x28, 0xfc,
	0x25, 0x33, 0x3c, 0xd0, 0x35, 0x58, 0x19, 0x25, 0x8a, 0x72, 0x9b, 0x50, 0xe9, 0x08, 0xeb, 0x44,
	0xba, 0x1e, 0xda, 0x87, 0x4c, 0xb2, 0x99, 0x2b, 0x6c, 0x41, 0x91, 0x0b, 0xeb, 0xc2, 0xe7, 0xb7,
	0xe1, 0x90, 0x0a, 0xe6, 0x12, 0x17, 0xd6, 0x09, 0xbf, 0x45, 0xfa, 0x06, 0xaa, 0xa9, 0x9c, 0xd1,
	0xc8, 0x2b, 0xb0, 0x30, 0x10, 0x5c, 0xfa, 0xd1, 0xc0, 0xc3, 0x03, 0xf9, 0x0d, 0x40, 0xba, 0x92,
	0x39, 0xf1, 0x5c, 0x25, 0x65, 0x51, 0xd9, 0x9e, 0x42, 0xa5, 0x8d, 0xf2, 0xfe, 0x08, 0xe9, 0xe7,
	0x3c, 0x54, 0x53, 0x91, 0x3f, 0x80, 0x83, 0x6c, 0x43, 0xe9, 0x83, 0x87, 0x18, 0xde, 0x16, 0xd4,
	0x6d, 0x31, 0x30, 0xa8, 0xcb, 0x27, 0xb0, 0xd8, 0x47, 0x8f, 0xbb, 0xb6, 0xf1, 0x73, 0x3d, 0xdf,
	0x28, 0xef, 0xfd, 0xda, 0x4c, 0x7d, 0x53, 0xcd, 0x53, 0x9f, 0x5d, 0xe2, 0xb1, 0xf2, 0x31, 0x23,
	0x5f, 0x7a, 0x0a, 0x9b, 0x1d, 0x61, 0x1d, 0xa1, 0xfc, 0xe4, 0x7a, 0xbd, 0x57, 0x97, 0x1e, 0xfa,
	0xfe, 0x3c, 0xe6, 0xff, 0x16, 0x8c, 0x6c, 0xda, 0xbb, 0x8f, 0x8c, 0xd9, 0x36, 0xda, 0x17, 0xf1,
	0x01, 0x80, 0x32, 0x9d, 0xaa, 0x29, 0x6c, 0x43, 0xc9, 0x1f, 0x74, 0xa3, 0xeb, 0x30, 0x71, 0xd1,
	0x1f, 0x74, 0xd5, 0x25, 0x7d, 0x01, 0x9b, 0x6d, 0x94, 0x0f, 0x02, 0x4c, 0xbf, 0xe4, 0xc1, 0xc8,
	0x06, 0x4f, 0x64, 0x64, 0x12, 0x96, 0x80, 0x2e, 0xc5, 0x47, 0x78, 0x1b, 0x12, 0xa2, 0x18, 0x0a,
	0xaf, 0x1f, 0xc6, 0xc8, 0x99, 0x62, 0xa4, 0x23, 0x7c, 0x19, 0xbc, 0x04, 0x26, 0x32, 0x7b, 0x76,
	0x46, 0xb6, 0xa1, 0x14, 0x30, 0x62, 0xb9, 0x03, 0x21, 0x87, 0x68, 0xb9, 0xb0, 0x5a, 0xc1, 0x39,
	0xe2, 0x24, 0x95, 0x78, 0x8e, 0x9c, 0x3c, 0x08, 0xf2, 0x90, 0x13, 0x3d, 0xac, 0xc7, 0xc2, 0x49,
	0x72, 0x74, 0x67, 0x1e, 0x97, 0x38, 0x27, 0x52, 0xde, 0xc1, 0x96, 0x26, 0xf3, 0x5c, 0x58, 0x79,
	0x99, 0x18, 0xec, 0xfd, 0x40, 0xd3, 0xaf, 0x79, 0xd8, 0xd2, 0x44, 0x3f, 0x32, 0x5e, 0xf6, 0xa1,
	0x1c, 0x33, 0x07, 0xb0, 0x7c, 0xc9, 0x3c, 0x39, 0x84, 0xa5, 0x0e, 0x64, 0x15, 0x0a, 0x28, 0xec,
	0x08, 0x50, 0xf0, 0x73, 0xef, 0x1b, 0x00, 0x1c, 0x1c, 0x77, 0x4e, 0xd0, 0xfb, 0xc8, 0x2d, 0x24,
	0xe7, 0x50, 0x8e, 0xa9, 0x0a, 0xf2, 0x47, 0xa6, 0x74, 0x56, 0x89, 0xd4, 0xfe, 0x9c, 0xec, 0x14,
	0xad, 0xb6, 0x1c, 0xb1, 0x60, 0x39, 0xa9, 0x35, 0xc8, 0x6e, 0x36, 0x52, 0xa7, 0x5d, 0x6a, 0x7f,
	0x4f, 0xf5, 0x1b, 0x15, 0x39, 0x87, 0x72, 0x4c, 0x5e, 0x68, 0x1a, 0xc8, 0x6a, 0x16, 0x4d, 0x03,
	0x1a, 0x85, 0x12, 0x36, 0x90, 0xd4, 0x04, 0x9a, 0x06, 0xb4, 0x72, 0x43, 0xd3, 0xc0, 0x18, 0x71,
	0x91, 0x23, 0x47, 0xb0, 0x14, 0xa9, 0x02, 0xb2, 0x93, 0x89, 0x4a, 0x0a, 0x8f, 0x5a, 0x7d, 0xbc,
	0xc3, 0x28, 0xdf, 0x7b, 0xf8, 0x25, 0xb1, 0xfe, 0xc9, 0x5f, 0x99, 0x20, 0x9d, 0xe4, 0xa8, 0xed,
	0x4e, 0x73, 0x8b, 0x57, 0x48, 0x2c, 0x76, 0x4d, 0x05, 0x9d, 0x64, 0xd0, 0x54, 0xd0, 0xea, 0x03,
	0x9a, 0x23, 0x1c, 0x56, 0xd3, 0x2b, 0x94, 0x34, 0x74, 0xf8, 0x74, 0xbb, 0xb0, 0xf6, 0xcf, 0x0c,
	0x9e, 0xf1, 0x52, 0xe9, 0xb5, 0xa8, 0x29, 0x35, 0x66, 0xed, 0x6a, 0x4a, 0x8d, 0xdb, 0xb1, 0xa3,
	0xae, 0x12, 0xaf, 0xbd, 0xbe, 0x2b, 0xdd, 0x36, 0xd1, 0x77, 0xa5, 0x5d, 0x1d, 0xa3, 0xae, 0xa6,
	0x95, 0x1a, 0xb3, 0xb8, 0xf4, 0x5d, 0x8d, 0x2b, 0xe5, 0xc0, 0x5a, 0xe6, 0x15, 0x27, 0x13, 0xc1,
	0x26, 0x9e, 0xe3, 0xda, 0xbf, 0xb3, 0xb8, 0xc6, 0xab, 0x65, 0x9e, 0x66, 0x32, 0x11, 0xef, 0xb4,
	0x6a, 0x63, 0x5f, 0x7a, 0x9a, 0xeb, 0x2e, 0xaa, 0x7f, 0x68, 0xff, 0x7f, 0x0f, 0x00, 0x00, 0xff,
	0xff, 0x06, 0x9e, 0x94, 0x2f, 0xb3, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIServiceClient is the client API for APIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIServiceClient interface {
	CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthResponse, error)
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerResponse, error)
	GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*GetCustomerResponse, error)
	DeleteCustomer(ctx context.Context, in *DeleteCustomerRequest, opts ...grpc.CallOption) (*DeleteCustomerResponse, error)
	AddCard(ctx context.Context, in *AddCardRequest, opts ...grpc.CallOption) (*AddCardResponse, error)
	IncStoredData(ctx context.Context, in *IncStoredDataRequest, opts ...grpc.CallOption) (*IncStoredDataResponse, error)
	GetStoredData(ctx context.Context, in *GetStoredDataRequest, opts ...grpc.CallOption) (*GetStoredDataResponse, error)
	IncNetworkEgress(ctx context.Context, in *IncNetworkEgressRequest, opts ...grpc.CallOption) (*IncNetworkEgressResponse, error)
	GetNetworkEgress(ctx context.Context, in *GetNetworkEgressRequest, opts ...grpc.CallOption) (*GetNetworkEgressResponse, error)
	IncInstanceReads(ctx context.Context, in *IncInstanceReadsRequest, opts ...grpc.CallOption) (*IncInstanceReadsResponse, error)
	GetInstanceReads(ctx context.Context, in *GetInstanceReadsRequest, opts ...grpc.CallOption) (*GetInstanceReadsResponse, error)
	IncInstanceWrites(ctx context.Context, in *IncInstanceWritesRequest, opts ...grpc.CallOption) (*IncInstanceWritesResponse, error)
	GetInstanceWrites(ctx context.Context, in *GetInstanceWritesRequest, opts ...grpc.CallOption) (*GetInstanceWritesResponse, error)
}

type aPIServiceClient struct {
	cc *grpc.ClientConn
}

func NewAPIServiceClient(cc *grpc.ClientConn) APIServiceClient {
	return &aPIServiceClient{cc}
}

func (c *aPIServiceClient) CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthResponse, error) {
	out := new(CheckHealthResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/CheckHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerResponse, error) {
	out := new(CreateCustomerResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*GetCustomerResponse, error) {
	out := new(GetCustomerResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/GetCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) DeleteCustomer(ctx context.Context, in *DeleteCustomerRequest, opts ...grpc.CallOption) (*DeleteCustomerResponse, error) {
	out := new(DeleteCustomerResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/DeleteCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) AddCard(ctx context.Context, in *AddCardRequest, opts ...grpc.CallOption) (*AddCardResponse, error) {
	out := new(AddCardResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/AddCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) IncStoredData(ctx context.Context, in *IncStoredDataRequest, opts ...grpc.CallOption) (*IncStoredDataResponse, error) {
	out := new(IncStoredDataResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/IncStoredData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetStoredData(ctx context.Context, in *GetStoredDataRequest, opts ...grpc.CallOption) (*GetStoredDataResponse, error) {
	out := new(GetStoredDataResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/GetStoredData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) IncNetworkEgress(ctx context.Context, in *IncNetworkEgressRequest, opts ...grpc.CallOption) (*IncNetworkEgressResponse, error) {
	out := new(IncNetworkEgressResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/IncNetworkEgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetNetworkEgress(ctx context.Context, in *GetNetworkEgressRequest, opts ...grpc.CallOption) (*GetNetworkEgressResponse, error) {
	out := new(GetNetworkEgressResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/GetNetworkEgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) IncInstanceReads(ctx context.Context, in *IncInstanceReadsRequest, opts ...grpc.CallOption) (*IncInstanceReadsResponse, error) {
	out := new(IncInstanceReadsResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/IncInstanceReads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetInstanceReads(ctx context.Context, in *GetInstanceReadsRequest, opts ...grpc.CallOption) (*GetInstanceReadsResponse, error) {
	out := new(GetInstanceReadsResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/GetInstanceReads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) IncInstanceWrites(ctx context.Context, in *IncInstanceWritesRequest, opts ...grpc.CallOption) (*IncInstanceWritesResponse, error) {
	out := new(IncInstanceWritesResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/IncInstanceWrites", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetInstanceWrites(ctx context.Context, in *GetInstanceWritesRequest, opts ...grpc.CallOption) (*GetInstanceWritesResponse, error) {
	out := new(GetInstanceWritesResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/GetInstanceWrites", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServiceServer is the server API for APIService service.
type APIServiceServer interface {
	CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthResponse, error)
	CreateCustomer(context.Context, *CreateCustomerRequest) (*CreateCustomerResponse, error)
	GetCustomer(context.Context, *GetCustomerRequest) (*GetCustomerResponse, error)
	DeleteCustomer(context.Context, *DeleteCustomerRequest) (*DeleteCustomerResponse, error)
	AddCard(context.Context, *AddCardRequest) (*AddCardResponse, error)
	IncStoredData(context.Context, *IncStoredDataRequest) (*IncStoredDataResponse, error)
	GetStoredData(context.Context, *GetStoredDataRequest) (*GetStoredDataResponse, error)
	IncNetworkEgress(context.Context, *IncNetworkEgressRequest) (*IncNetworkEgressResponse, error)
	GetNetworkEgress(context.Context, *GetNetworkEgressRequest) (*GetNetworkEgressResponse, error)
	IncInstanceReads(context.Context, *IncInstanceReadsRequest) (*IncInstanceReadsResponse, error)
	GetInstanceReads(context.Context, *GetInstanceReadsRequest) (*GetInstanceReadsResponse, error)
	IncInstanceWrites(context.Context, *IncInstanceWritesRequest) (*IncInstanceWritesResponse, error)
	GetInstanceWrites(context.Context, *GetInstanceWritesRequest) (*GetInstanceWritesResponse, error)
}

// UnimplementedAPIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServiceServer struct {
}

func (*UnimplementedAPIServiceServer) CheckHealth(ctx context.Context, req *CheckHealthRequest) (*CheckHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}
func (*UnimplementedAPIServiceServer) CreateCustomer(ctx context.Context, req *CreateCustomerRequest) (*CreateCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (*UnimplementedAPIServiceServer) GetCustomer(ctx context.Context, req *GetCustomerRequest) (*GetCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomer not implemented")
}
func (*UnimplementedAPIServiceServer) DeleteCustomer(ctx context.Context, req *DeleteCustomerRequest) (*DeleteCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCustomer not implemented")
}
func (*UnimplementedAPIServiceServer) AddCard(ctx context.Context, req *AddCardRequest) (*AddCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCard not implemented")
}
func (*UnimplementedAPIServiceServer) IncStoredData(ctx context.Context, req *IncStoredDataRequest) (*IncStoredDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncStoredData not implemented")
}
func (*UnimplementedAPIServiceServer) GetStoredData(ctx context.Context, req *GetStoredDataRequest) (*GetStoredDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStoredData not implemented")
}
func (*UnimplementedAPIServiceServer) IncNetworkEgress(ctx context.Context, req *IncNetworkEgressRequest) (*IncNetworkEgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncNetworkEgress not implemented")
}
func (*UnimplementedAPIServiceServer) GetNetworkEgress(ctx context.Context, req *GetNetworkEgressRequest) (*GetNetworkEgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetworkEgress not implemented")
}
func (*UnimplementedAPIServiceServer) IncInstanceReads(ctx context.Context, req *IncInstanceReadsRequest) (*IncInstanceReadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncInstanceReads not implemented")
}
func (*UnimplementedAPIServiceServer) GetInstanceReads(ctx context.Context, req *GetInstanceReadsRequest) (*GetInstanceReadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstanceReads not implemented")
}
func (*UnimplementedAPIServiceServer) IncInstanceWrites(ctx context.Context, req *IncInstanceWritesRequest) (*IncInstanceWritesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncInstanceWrites not implemented")
}
func (*UnimplementedAPIServiceServer) GetInstanceWrites(ctx context.Context, req *GetInstanceWritesRequest) (*GetInstanceWritesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstanceWrites not implemented")
}

func RegisterAPIServiceServer(s *grpc.Server, srv APIServiceServer) {
	s.RegisterService(&_APIService_serviceDesc, srv)
}

func _APIService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/CheckHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).CheckHealth(ctx, req.(*CheckHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).CreateCustomer(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/GetCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetCustomer(ctx, req.(*GetCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_DeleteCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).DeleteCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/DeleteCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).DeleteCustomer(ctx, req.(*DeleteCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_AddCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).AddCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/AddCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).AddCard(ctx, req.(*AddCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_IncStoredData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncStoredDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).IncStoredData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/IncStoredData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).IncStoredData(ctx, req.(*IncStoredDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetStoredData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoredDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetStoredData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/GetStoredData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetStoredData(ctx, req.(*GetStoredDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_IncNetworkEgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncNetworkEgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).IncNetworkEgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/IncNetworkEgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).IncNetworkEgress(ctx, req.(*IncNetworkEgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetNetworkEgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkEgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetNetworkEgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/GetNetworkEgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetNetworkEgress(ctx, req.(*GetNetworkEgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_IncInstanceReads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncInstanceReadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).IncInstanceReads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/IncInstanceReads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).IncInstanceReads(ctx, req.(*IncInstanceReadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetInstanceReads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceReadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetInstanceReads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/GetInstanceReads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetInstanceReads(ctx, req.(*GetInstanceReadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_IncInstanceWrites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncInstanceWritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).IncInstanceWrites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/IncInstanceWrites",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).IncInstanceWrites(ctx, req.(*IncInstanceWritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetInstanceWrites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceWritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetInstanceWrites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/GetInstanceWrites",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetInstanceWrites(ctx, req.(*GetInstanceWritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _APIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.billingd.pb.APIService",
	HandlerType: (*APIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckHealth",
			Handler:    _APIService_CheckHealth_Handler,
		},
		{
			MethodName: "CreateCustomer",
			Handler:    _APIService_CreateCustomer_Handler,
		},
		{
			MethodName: "GetCustomer",
			Handler:    _APIService_GetCustomer_Handler,
		},
		{
			MethodName: "DeleteCustomer",
			Handler:    _APIService_DeleteCustomer_Handler,
		},
		{
			MethodName: "AddCard",
			Handler:    _APIService_AddCard_Handler,
		},
		{
			MethodName: "IncStoredData",
			Handler:    _APIService_IncStoredData_Handler,
		},
		{
			MethodName: "GetStoredData",
			Handler:    _APIService_GetStoredData_Handler,
		},
		{
			MethodName: "IncNetworkEgress",
			Handler:    _APIService_IncNetworkEgress_Handler,
		},
		{
			MethodName: "GetNetworkEgress",
			Handler:    _APIService_GetNetworkEgress_Handler,
		},
		{
			MethodName: "IncInstanceReads",
			Handler:    _APIService_IncInstanceReads_Handler,
		},
		{
			MethodName: "GetInstanceReads",
			Handler:    _APIService_GetInstanceReads_Handler,
		},
		{
			MethodName: "IncInstanceWrites",
			Handler:    _APIService_IncInstanceWrites_Handler,
		},
		{
			MethodName: "GetInstanceWrites",
			Handler:    _APIService_GetInstanceWrites_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billingd.proto",
}
