// Code generated by protoc-gen-go. DO NOT EDIT.
// source: billing.proto

package api_billing_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckHealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckHealthRequest) Reset()         { *m = CheckHealthRequest{} }
func (m *CheckHealthRequest) String() string { return proto.CompactTextString(m) }
func (*CheckHealthRequest) ProtoMessage()    {}
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{0}
}

func (m *CheckHealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckHealthRequest.Unmarshal(m, b)
}
func (m *CheckHealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckHealthRequest.Marshal(b, m, deterministic)
}
func (m *CheckHealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckHealthRequest.Merge(m, src)
}
func (m *CheckHealthRequest) XXX_Size() int {
	return xxx_messageInfo_CheckHealthRequest.Size(m)
}
func (m *CheckHealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckHealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckHealthRequest proto.InternalMessageInfo

type CheckHealthResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckHealthResponse) Reset()         { *m = CheckHealthResponse{} }
func (m *CheckHealthResponse) String() string { return proto.CompactTextString(m) }
func (*CheckHealthResponse) ProtoMessage()    {}
func (*CheckHealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{1}
}

func (m *CheckHealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckHealthResponse.Unmarshal(m, b)
}
func (m *CheckHealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckHealthResponse.Marshal(b, m, deterministic)
}
func (m *CheckHealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckHealthResponse.Merge(m, src)
}
func (m *CheckHealthResponse) XXX_Size() int {
	return xxx_messageInfo_CheckHealthResponse.Size(m)
}
func (m *CheckHealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckHealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckHealthResponse proto.InternalMessageInfo

type CreateCustomerRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerRequest) Reset()         { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()    {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{2}
}

func (m *CreateCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerRequest.Unmarshal(m, b)
}
func (m *CreateCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerRequest.Marshal(b, m, deterministic)
}
func (m *CreateCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerRequest.Merge(m, src)
}
func (m *CreateCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerRequest.Size(m)
}
func (m *CreateCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerRequest proto.InternalMessageInfo

func (m *CreateCustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateCustomerResponse struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerResponse) Reset()         { *m = CreateCustomerResponse{} }
func (m *CreateCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerResponse) ProtoMessage()    {}
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{3}
}

func (m *CreateCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerResponse.Unmarshal(m, b)
}
func (m *CreateCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerResponse.Marshal(b, m, deterministic)
}
func (m *CreateCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerResponse.Merge(m, src)
}
func (m *CreateCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerResponse.Size(m)
}
func (m *CreateCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerResponse proto.InternalMessageInfo

func (m *CreateCustomerResponse) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type SetStoredDataRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ByteSize             int64    `protobuf:"varint,2,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStoredDataRequest) Reset()         { *m = SetStoredDataRequest{} }
func (m *SetStoredDataRequest) String() string { return proto.CompactTextString(m) }
func (*SetStoredDataRequest) ProtoMessage()    {}
func (*SetStoredDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{4}
}

func (m *SetStoredDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStoredDataRequest.Unmarshal(m, b)
}
func (m *SetStoredDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStoredDataRequest.Marshal(b, m, deterministic)
}
func (m *SetStoredDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStoredDataRequest.Merge(m, src)
}
func (m *SetStoredDataRequest) XXX_Size() int {
	return xxx_messageInfo_SetStoredDataRequest.Size(m)
}
func (m *SetStoredDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStoredDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetStoredDataRequest proto.InternalMessageInfo

func (m *SetStoredDataRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *SetStoredDataRequest) GetByteSize() int64 {
	if m != nil {
		return m.ByteSize
	}
	return 0
}

type SetStoredDataResponse struct {
	PeriodUnits          int64    `protobuf:"varint,1,opt,name=period_units,json=periodUnits,proto3" json:"period_units,omitempty"`
	Changed              bool     `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStoredDataResponse) Reset()         { *m = SetStoredDataResponse{} }
func (m *SetStoredDataResponse) String() string { return proto.CompactTextString(m) }
func (*SetStoredDataResponse) ProtoMessage()    {}
func (*SetStoredDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{5}
}

func (m *SetStoredDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStoredDataResponse.Unmarshal(m, b)
}
func (m *SetStoredDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStoredDataResponse.Marshal(b, m, deterministic)
}
func (m *SetStoredDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStoredDataResponse.Merge(m, src)
}
func (m *SetStoredDataResponse) XXX_Size() int {
	return xxx_messageInfo_SetStoredDataResponse.Size(m)
}
func (m *SetStoredDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStoredDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetStoredDataResponse proto.InternalMessageInfo

func (m *SetStoredDataResponse) GetPeriodUnits() int64 {
	if m != nil {
		return m.PeriodUnits
	}
	return 0
}

func (m *SetStoredDataResponse) GetChanged() bool {
	if m != nil {
		return m.Changed
	}
	return false
}

type IncNetworkEgressRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ByteSize             int64    `protobuf:"varint,2,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncNetworkEgressRequest) Reset()         { *m = IncNetworkEgressRequest{} }
func (m *IncNetworkEgressRequest) String() string { return proto.CompactTextString(m) }
func (*IncNetworkEgressRequest) ProtoMessage()    {}
func (*IncNetworkEgressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{6}
}

func (m *IncNetworkEgressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncNetworkEgressRequest.Unmarshal(m, b)
}
func (m *IncNetworkEgressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncNetworkEgressRequest.Marshal(b, m, deterministic)
}
func (m *IncNetworkEgressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncNetworkEgressRequest.Merge(m, src)
}
func (m *IncNetworkEgressRequest) XXX_Size() int {
	return xxx_messageInfo_IncNetworkEgressRequest.Size(m)
}
func (m *IncNetworkEgressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncNetworkEgressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncNetworkEgressRequest proto.InternalMessageInfo

func (m *IncNetworkEgressRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *IncNetworkEgressRequest) GetByteSize() int64 {
	if m != nil {
		return m.ByteSize
	}
	return 0
}

type IncNetworkEgressResponse struct {
	PeriodUnits          int64    `protobuf:"varint,1,opt,name=period_units,json=periodUnits,proto3" json:"period_units,omitempty"`
	Changed              bool     `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncNetworkEgressResponse) Reset()         { *m = IncNetworkEgressResponse{} }
func (m *IncNetworkEgressResponse) String() string { return proto.CompactTextString(m) }
func (*IncNetworkEgressResponse) ProtoMessage()    {}
func (*IncNetworkEgressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{7}
}

func (m *IncNetworkEgressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncNetworkEgressResponse.Unmarshal(m, b)
}
func (m *IncNetworkEgressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncNetworkEgressResponse.Marshal(b, m, deterministic)
}
func (m *IncNetworkEgressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncNetworkEgressResponse.Merge(m, src)
}
func (m *IncNetworkEgressResponse) XXX_Size() int {
	return xxx_messageInfo_IncNetworkEgressResponse.Size(m)
}
func (m *IncNetworkEgressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncNetworkEgressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncNetworkEgressResponse proto.InternalMessageInfo

func (m *IncNetworkEgressResponse) GetPeriodUnits() int64 {
	if m != nil {
		return m.PeriodUnits
	}
	return 0
}

func (m *IncNetworkEgressResponse) GetChanged() bool {
	if m != nil {
		return m.Changed
	}
	return false
}

type IncInstanceReadsRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncInstanceReadsRequest) Reset()         { *m = IncInstanceReadsRequest{} }
func (m *IncInstanceReadsRequest) String() string { return proto.CompactTextString(m) }
func (*IncInstanceReadsRequest) ProtoMessage()    {}
func (*IncInstanceReadsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{8}
}

func (m *IncInstanceReadsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncInstanceReadsRequest.Unmarshal(m, b)
}
func (m *IncInstanceReadsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncInstanceReadsRequest.Marshal(b, m, deterministic)
}
func (m *IncInstanceReadsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncInstanceReadsRequest.Merge(m, src)
}
func (m *IncInstanceReadsRequest) XXX_Size() int {
	return xxx_messageInfo_IncInstanceReadsRequest.Size(m)
}
func (m *IncInstanceReadsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncInstanceReadsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncInstanceReadsRequest proto.InternalMessageInfo

func (m *IncInstanceReadsRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *IncInstanceReadsRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type IncInstanceReadsResponse struct {
	PeriodUnits          int64    `protobuf:"varint,1,opt,name=period_units,json=periodUnits,proto3" json:"period_units,omitempty"`
	Changed              bool     `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncInstanceReadsResponse) Reset()         { *m = IncInstanceReadsResponse{} }
func (m *IncInstanceReadsResponse) String() string { return proto.CompactTextString(m) }
func (*IncInstanceReadsResponse) ProtoMessage()    {}
func (*IncInstanceReadsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{9}
}

func (m *IncInstanceReadsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncInstanceReadsResponse.Unmarshal(m, b)
}
func (m *IncInstanceReadsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncInstanceReadsResponse.Marshal(b, m, deterministic)
}
func (m *IncInstanceReadsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncInstanceReadsResponse.Merge(m, src)
}
func (m *IncInstanceReadsResponse) XXX_Size() int {
	return xxx_messageInfo_IncInstanceReadsResponse.Size(m)
}
func (m *IncInstanceReadsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncInstanceReadsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncInstanceReadsResponse proto.InternalMessageInfo

func (m *IncInstanceReadsResponse) GetPeriodUnits() int64 {
	if m != nil {
		return m.PeriodUnits
	}
	return 0
}

func (m *IncInstanceReadsResponse) GetChanged() bool {
	if m != nil {
		return m.Changed
	}
	return false
}

type IncInstanceWritesRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncInstanceWritesRequest) Reset()         { *m = IncInstanceWritesRequest{} }
func (m *IncInstanceWritesRequest) String() string { return proto.CompactTextString(m) }
func (*IncInstanceWritesRequest) ProtoMessage()    {}
func (*IncInstanceWritesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{10}
}

func (m *IncInstanceWritesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncInstanceWritesRequest.Unmarshal(m, b)
}
func (m *IncInstanceWritesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncInstanceWritesRequest.Marshal(b, m, deterministic)
}
func (m *IncInstanceWritesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncInstanceWritesRequest.Merge(m, src)
}
func (m *IncInstanceWritesRequest) XXX_Size() int {
	return xxx_messageInfo_IncInstanceWritesRequest.Size(m)
}
func (m *IncInstanceWritesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncInstanceWritesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncInstanceWritesRequest proto.InternalMessageInfo

func (m *IncInstanceWritesRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *IncInstanceWritesRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type IncInstanceWritesResponse struct {
	PeriodUnits          int64    `protobuf:"varint,1,opt,name=period_units,json=periodUnits,proto3" json:"period_units,omitempty"`
	Changed              bool     `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncInstanceWritesResponse) Reset()         { *m = IncInstanceWritesResponse{} }
func (m *IncInstanceWritesResponse) String() string { return proto.CompactTextString(m) }
func (*IncInstanceWritesResponse) ProtoMessage()    {}
func (*IncInstanceWritesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{11}
}

func (m *IncInstanceWritesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncInstanceWritesResponse.Unmarshal(m, b)
}
func (m *IncInstanceWritesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncInstanceWritesResponse.Marshal(b, m, deterministic)
}
func (m *IncInstanceWritesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncInstanceWritesResponse.Merge(m, src)
}
func (m *IncInstanceWritesResponse) XXX_Size() int {
	return xxx_messageInfo_IncInstanceWritesResponse.Size(m)
}
func (m *IncInstanceWritesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncInstanceWritesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncInstanceWritesResponse proto.InternalMessageInfo

func (m *IncInstanceWritesResponse) GetPeriodUnits() int64 {
	if m != nil {
		return m.PeriodUnits
	}
	return 0
}

func (m *IncInstanceWritesResponse) GetChanged() bool {
	if m != nil {
		return m.Changed
	}
	return false
}

type DeleteCustomerRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomerRequest) Reset()         { *m = DeleteCustomerRequest{} }
func (m *DeleteCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomerRequest) ProtoMessage()    {}
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{12}
}

func (m *DeleteCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomerRequest.Unmarshal(m, b)
}
func (m *DeleteCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomerRequest.Merge(m, src)
}
func (m *DeleteCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomerRequest.Size(m)
}
func (m *DeleteCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomerRequest proto.InternalMessageInfo

func (m *DeleteCustomerRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type DeleteCustomerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomerResponse) Reset()         { *m = DeleteCustomerResponse{} }
func (m *DeleteCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomerResponse) ProtoMessage()    {}
func (*DeleteCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{13}
}

func (m *DeleteCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomerResponse.Unmarshal(m, b)
}
func (m *DeleteCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomerResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomerResponse.Merge(m, src)
}
func (m *DeleteCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomerResponse.Size(m)
}
func (m *DeleteCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomerResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CheckHealthRequest)(nil), "api.billing.pb.CheckHealthRequest")
	proto.RegisterType((*CheckHealthResponse)(nil), "api.billing.pb.CheckHealthResponse")
	proto.RegisterType((*CreateCustomerRequest)(nil), "api.billing.pb.CreateCustomerRequest")
	proto.RegisterType((*CreateCustomerResponse)(nil), "api.billing.pb.CreateCustomerResponse")
	proto.RegisterType((*SetStoredDataRequest)(nil), "api.billing.pb.SetStoredDataRequest")
	proto.RegisterType((*SetStoredDataResponse)(nil), "api.billing.pb.SetStoredDataResponse")
	proto.RegisterType((*IncNetworkEgressRequest)(nil), "api.billing.pb.IncNetworkEgressRequest")
	proto.RegisterType((*IncNetworkEgressResponse)(nil), "api.billing.pb.IncNetworkEgressResponse")
	proto.RegisterType((*IncInstanceReadsRequest)(nil), "api.billing.pb.IncInstanceReadsRequest")
	proto.RegisterType((*IncInstanceReadsResponse)(nil), "api.billing.pb.IncInstanceReadsResponse")
	proto.RegisterType((*IncInstanceWritesRequest)(nil), "api.billing.pb.IncInstanceWritesRequest")
	proto.RegisterType((*IncInstanceWritesResponse)(nil), "api.billing.pb.IncInstanceWritesResponse")
	proto.RegisterType((*DeleteCustomerRequest)(nil), "api.billing.pb.DeleteCustomerRequest")
	proto.RegisterType((*DeleteCustomerResponse)(nil), "api.billing.pb.DeleteCustomerResponse")
}

func init() { proto.RegisterFile("billing.proto", fileDescriptor_958db8ba491a6b57) }

var fileDescriptor_958db8ba491a6b57 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x5b, 0xa6, 0xc2, 0xf6, 0xca, 0x26, 0x30, 0xed, 0x08, 0xe1, 0xc0, 0x30, 0x0c, 0xca,
	0x81, 0x1e, 0xe0, 0x02, 0x47, 0xd4, 0x21, 0xd1, 0x0b, 0x1a, 0xe9, 0x50, 0x77, 0xa2, 0x72, 0x93,
	0xa7, 0xd6, 0x2c, 0xb3, 0x8b, 0xed, 0x80, 0xd8, 0x9f, 0xc8, 0x5f, 0x85, 0x96, 0xa4, 0xd5, 0xec,
	0x98, 0x65, 0x12, 0x39, 0xfa, 0xe9, 0x7b, 0xdf, 0xfb, 0x0e, 0xdf, 0x4f, 0x86, 0xdd, 0x39, 0x4f,
	0x53, 0x2e, 0x16, 0xc3, 0x95, 0x92, 0x46, 0x92, 0x3d, 0xb6, 0xe2, 0xc3, 0xcd, 0x68, 0x4e, 0x7b,
	0x40, 0x46, 0x4b, 0x8c, 0xcf, 0x3e, 0x21, 0x4b, 0xcd, 0x32, 0xc2, 0x1f, 0x19, 0x6a, 0x43, 0xfb,
	0xf0, 0xc0, 0x9a, 0xea, 0x95, 0x14, 0x1a, 0xe9, 0x6b, 0xe8, 0x8f, 0x14, 0x32, 0x83, 0xa3, 0x4c,
	0x1b, 0x79, 0x8e, 0xaa, 0xd4, 0x93, 0x1e, 0x74, 0xf0, 0x9c, 0xf1, 0x34, 0x68, 0x1f, 0xb4, 0x07,
	0x3b, 0x51, 0xf1, 0xa0, 0xef, 0x61, 0xdf, 0x95, 0x17, 0x46, 0xe4, 0x09, 0x74, 0xe3, 0x72, 0x36,
	0xe3, 0x49, 0xb9, 0x05, 0xeb, 0xd1, 0x38, 0xa1, 0x27, 0xd0, 0x9b, 0xa0, 0x99, 0x18, 0xa9, 0x30,
	0x39, 0x62, 0x86, 0xad, 0x0f, 0xd5, 0x2d, 0x92, 0xc7, 0xb0, 0x33, 0xff, 0x6d, 0x70, 0xa6, 0xf9,
	0x05, 0x06, 0xb7, 0x0e, 0xda, 0x83, 0xad, 0x68, 0xfb, 0x72, 0x30, 0xe1, 0x17, 0x48, 0x4f, 0xa0,
	0xef, 0xb8, 0x96, 0x79, 0x9e, 0xc2, 0xdd, 0x15, 0x2a, 0x2e, 0x93, 0x59, 0x26, 0xb8, 0xd1, 0xb9,
	0xef, 0x56, 0xd4, 0x2d, 0x66, 0x5f, 0x2f, 0x47, 0x24, 0x80, 0x3b, 0xf1, 0x92, 0x89, 0x05, 0x26,
	0xb9, 0xed, 0x76, 0xb4, 0x7e, 0xd2, 0x29, 0x3c, 0x1c, 0x8b, 0xf8, 0x33, 0x9a, 0x5f, 0x52, 0x9d,
	0x7d, 0x5c, 0x28, 0xd4, 0xba, 0x99, 0xb8, 0x53, 0x08, 0xaa, 0xc6, 0x4d, 0x24, 0x3e, 0xce, 0x13,
	0x8f, 0x85, 0x36, 0x4c, 0xc4, 0x18, 0x21, 0x4b, 0x6e, 0x9e, 0xb8, 0x07, 0x9d, 0x58, 0x66, 0xc2,
	0x94, 0x69, 0x8b, 0x47, 0x19, 0xd5, 0x71, 0x6c, 0x22, 0xea, 0x17, 0xcb, 0x78, 0xaa, 0xb8, 0xc1,
	0xff, 0xcd, 0x7a, 0x0a, 0x8f, 0x3c, 0x96, 0x4d, 0x84, 0x7d, 0x07, 0xfd, 0x23, 0x4c, 0xb1, 0xca,
	0x47, 0x6d, 0xdf, 0x03, 0xd8, 0x77, 0x37, 0x8b, 0x40, 0x6f, 0xfe, 0x74, 0x00, 0x3e, 0x1c, 0x8f,
	0x27, 0xa8, 0x7e, 0xf2, 0x18, 0xc9, 0x29, 0x74, 0xaf, 0x90, 0x49, 0xe8, 0xd0, 0xe6, 0x79, 0x58,
	0x85, 0x39, 0x7c, 0x76, 0xad, 0xa6, 0x44, 0xbb, 0x45, 0x18, 0xec, 0xd9, 0xb4, 0x92, 0xc3, 0xca,
	0xa2, 0x0f, 0xfe, 0xf0, 0x45, 0x9d, 0x6c, 0x73, 0xe2, 0x1b, 0xec, 0x5a, 0xfc, 0x91, 0xe7, 0xee,
	0xaa, 0x0f, 0xfa, 0xf0, 0xb0, 0x46, 0xb5, 0xf1, 0x5f, 0xc0, 0x3d, 0x17, 0x18, 0xf2, 0xd2, 0x5d,
	0xfe, 0x07, 0xab, 0xe1, 0xa0, 0x5e, 0xe8, 0x1c, 0xb2, 0xea, 0xee, 0x3d, 0xe4, 0x43, 0xcc, 0x7b,
	0xc8, 0x4b, 0x0e, 0x6d, 0x91, 0xef, 0x70, 0xbf, 0xd2, 0x55, 0x72, 0x9d, 0x81, 0x45, 0x48, 0xf8,
	0xea, 0x06, 0xca, 0xab, 0x05, 0xb0, 0x3b, 0x58, 0x2d, 0x80, 0xb7, 0xdd, 0xd5, 0x02, 0xf8, 0xab,
	0x4c, 0x5b, 0xf3, 0xdb, 0xf9, 0x27, 0xf4, 0xf6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x94,
	0xc5, 0x34, 0x95, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIServiceClient is the client API for APIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIServiceClient interface {
	CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthResponse, error)
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerResponse, error)
	SetStoredData(ctx context.Context, in *SetStoredDataRequest, opts ...grpc.CallOption) (*SetStoredDataResponse, error)
	IncNetworkEgress(ctx context.Context, in *IncNetworkEgressRequest, opts ...grpc.CallOption) (*IncNetworkEgressResponse, error)
	IncInstanceReads(ctx context.Context, in *IncInstanceReadsRequest, opts ...grpc.CallOption) (*IncInstanceReadsResponse, error)
	IncInstanceWrites(ctx context.Context, in *IncInstanceWritesRequest, opts ...grpc.CallOption) (*IncInstanceWritesResponse, error)
	DeleteCustomer(ctx context.Context, in *DeleteCustomerRequest, opts ...grpc.CallOption) (*DeleteCustomerResponse, error)
}

type aPIServiceClient struct {
	cc *grpc.ClientConn
}

func NewAPIServiceClient(cc *grpc.ClientConn) APIServiceClient {
	return &aPIServiceClient{cc}
}

func (c *aPIServiceClient) CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthResponse, error) {
	out := new(CheckHealthResponse)
	err := c.cc.Invoke(ctx, "/api.billing.pb.APIService/CheckHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerResponse, error) {
	out := new(CreateCustomerResponse)
	err := c.cc.Invoke(ctx, "/api.billing.pb.APIService/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) SetStoredData(ctx context.Context, in *SetStoredDataRequest, opts ...grpc.CallOption) (*SetStoredDataResponse, error) {
	out := new(SetStoredDataResponse)
	err := c.cc.Invoke(ctx, "/api.billing.pb.APIService/SetStoredData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) IncNetworkEgress(ctx context.Context, in *IncNetworkEgressRequest, opts ...grpc.CallOption) (*IncNetworkEgressResponse, error) {
	out := new(IncNetworkEgressResponse)
	err := c.cc.Invoke(ctx, "/api.billing.pb.APIService/IncNetworkEgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) IncInstanceReads(ctx context.Context, in *IncInstanceReadsRequest, opts ...grpc.CallOption) (*IncInstanceReadsResponse, error) {
	out := new(IncInstanceReadsResponse)
	err := c.cc.Invoke(ctx, "/api.billing.pb.APIService/IncInstanceReads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) IncInstanceWrites(ctx context.Context, in *IncInstanceWritesRequest, opts ...grpc.CallOption) (*IncInstanceWritesResponse, error) {
	out := new(IncInstanceWritesResponse)
	err := c.cc.Invoke(ctx, "/api.billing.pb.APIService/IncInstanceWrites", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) DeleteCustomer(ctx context.Context, in *DeleteCustomerRequest, opts ...grpc.CallOption) (*DeleteCustomerResponse, error) {
	out := new(DeleteCustomerResponse)
	err := c.cc.Invoke(ctx, "/api.billing.pb.APIService/DeleteCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServiceServer is the server API for APIService service.
type APIServiceServer interface {
	CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthResponse, error)
	CreateCustomer(context.Context, *CreateCustomerRequest) (*CreateCustomerResponse, error)
	SetStoredData(context.Context, *SetStoredDataRequest) (*SetStoredDataResponse, error)
	IncNetworkEgress(context.Context, *IncNetworkEgressRequest) (*IncNetworkEgressResponse, error)
	IncInstanceReads(context.Context, *IncInstanceReadsRequest) (*IncInstanceReadsResponse, error)
	IncInstanceWrites(context.Context, *IncInstanceWritesRequest) (*IncInstanceWritesResponse, error)
	DeleteCustomer(context.Context, *DeleteCustomerRequest) (*DeleteCustomerResponse, error)
}

// UnimplementedAPIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServiceServer struct {
}

func (*UnimplementedAPIServiceServer) CheckHealth(ctx context.Context, req *CheckHealthRequest) (*CheckHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}
func (*UnimplementedAPIServiceServer) CreateCustomer(ctx context.Context, req *CreateCustomerRequest) (*CreateCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (*UnimplementedAPIServiceServer) SetStoredData(ctx context.Context, req *SetStoredDataRequest) (*SetStoredDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetStoredData not implemented")
}
func (*UnimplementedAPIServiceServer) IncNetworkEgress(ctx context.Context, req *IncNetworkEgressRequest) (*IncNetworkEgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncNetworkEgress not implemented")
}
func (*UnimplementedAPIServiceServer) IncInstanceReads(ctx context.Context, req *IncInstanceReadsRequest) (*IncInstanceReadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncInstanceReads not implemented")
}
func (*UnimplementedAPIServiceServer) IncInstanceWrites(ctx context.Context, req *IncInstanceWritesRequest) (*IncInstanceWritesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncInstanceWrites not implemented")
}
func (*UnimplementedAPIServiceServer) DeleteCustomer(ctx context.Context, req *DeleteCustomerRequest) (*DeleteCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCustomer not implemented")
}

func RegisterAPIServiceServer(s *grpc.Server, srv APIServiceServer) {
	s.RegisterService(&_APIService_serviceDesc, srv)
}

func _APIService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billing.pb.APIService/CheckHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).CheckHealth(ctx, req.(*CheckHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billing.pb.APIService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).CreateCustomer(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_SetStoredData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStoredDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).SetStoredData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billing.pb.APIService/SetStoredData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).SetStoredData(ctx, req.(*SetStoredDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_IncNetworkEgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncNetworkEgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).IncNetworkEgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billing.pb.APIService/IncNetworkEgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).IncNetworkEgress(ctx, req.(*IncNetworkEgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_IncInstanceReads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncInstanceReadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).IncInstanceReads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billing.pb.APIService/IncInstanceReads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).IncInstanceReads(ctx, req.(*IncInstanceReadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_IncInstanceWrites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncInstanceWritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).IncInstanceWrites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billing.pb.APIService/IncInstanceWrites",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).IncInstanceWrites(ctx, req.(*IncInstanceWritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_DeleteCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).DeleteCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billing.pb.APIService/DeleteCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).DeleteCustomer(ctx, req.(*DeleteCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _APIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.billing.pb.APIService",
	HandlerType: (*APIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckHealth",
			Handler:    _APIService_CheckHealth_Handler,
		},
		{
			MethodName: "CreateCustomer",
			Handler:    _APIService_CreateCustomer_Handler,
		},
		{
			MethodName: "SetStoredData",
			Handler:    _APIService_SetStoredData_Handler,
		},
		{
			MethodName: "IncNetworkEgress",
			Handler:    _APIService_IncNetworkEgress_Handler,
		},
		{
			MethodName: "IncInstanceReads",
			Handler:    _APIService_IncInstanceReads_Handler,
		},
		{
			MethodName: "IncInstanceWrites",
			Handler:    _APIService_IncInstanceWrites_Handler,
		},
		{
			MethodName: "DeleteCustomer",
			Handler:    _APIService_DeleteCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing.proto",
}
