// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/billingd/pb/billingd.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Period struct {
	UnixStart            int64    `protobuf:"varint,1,opt,name=unix_start,json=unixStart,proto3" json:"unix_start,omitempty"`
	UnixEnd              int64    `protobuf:"varint,2,opt,name=unix_end,json=unixEnd,proto3" json:"unix_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Period) Reset()         { *m = Period{} }
func (m *Period) String() string { return proto.CompactTextString(m) }
func (*Period) ProtoMessage()    {}
func (*Period) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{0}
}

func (m *Period) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Period.Unmarshal(m, b)
}
func (m *Period) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Period.Marshal(b, m, deterministic)
}
func (m *Period) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Period.Merge(m, src)
}
func (m *Period) XXX_Size() int {
	return xxx_messageInfo_Period.Size(m)
}
func (m *Period) XXX_DiscardUnknown() {
	xxx_messageInfo_Period.DiscardUnknown(m)
}

var xxx_messageInfo_Period proto.InternalMessageInfo

func (m *Period) GetUnixStart() int64 {
	if m != nil {
		return m.UnixStart
	}
	return 0
}

func (m *Period) GetUnixEnd() int64 {
	if m != nil {
		return m.UnixEnd
	}
	return 0
}

type Usage struct {
	Units                int64    `protobuf:"varint,1,opt,name=units,proto3" json:"units,omitempty"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Free                 int64    `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`
	Cost                 int64    `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Usage) Reset()         { *m = Usage{} }
func (m *Usage) String() string { return proto.CompactTextString(m) }
func (*Usage) ProtoMessage()    {}
func (*Usage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{1}
}

func (m *Usage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Usage.Unmarshal(m, b)
}
func (m *Usage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Usage.Marshal(b, m, deterministic)
}
func (m *Usage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Usage.Merge(m, src)
}
func (m *Usage) XXX_Size() int {
	return xxx_messageInfo_Usage.Size(m)
}
func (m *Usage) XXX_DiscardUnknown() {
	xxx_messageInfo_Usage.DiscardUnknown(m)
}

var xxx_messageInfo_Usage proto.InternalMessageInfo

func (m *Usage) GetUnits() int64 {
	if m != nil {
		return m.Units
	}
	return 0
}

func (m *Usage) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Usage) GetFree() int64 {
	if m != nil {
		return m.Free
	}
	return 0
}

func (m *Usage) GetCost() int64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type CheckHealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckHealthRequest) Reset()         { *m = CheckHealthRequest{} }
func (m *CheckHealthRequest) String() string { return proto.CompactTextString(m) }
func (*CheckHealthRequest) ProtoMessage()    {}
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{2}
}

func (m *CheckHealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckHealthRequest.Unmarshal(m, b)
}
func (m *CheckHealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckHealthRequest.Marshal(b, m, deterministic)
}
func (m *CheckHealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckHealthRequest.Merge(m, src)
}
func (m *CheckHealthRequest) XXX_Size() int {
	return xxx_messageInfo_CheckHealthRequest.Size(m)
}
func (m *CheckHealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckHealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckHealthRequest proto.InternalMessageInfo

type CheckHealthResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckHealthResponse) Reset()         { *m = CheckHealthResponse{} }
func (m *CheckHealthResponse) String() string { return proto.CompactTextString(m) }
func (*CheckHealthResponse) ProtoMessage()    {}
func (*CheckHealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{3}
}

func (m *CheckHealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckHealthResponse.Unmarshal(m, b)
}
func (m *CheckHealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckHealthResponse.Marshal(b, m, deterministic)
}
func (m *CheckHealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckHealthResponse.Merge(m, src)
}
func (m *CheckHealthResponse) XXX_Size() int {
	return xxx_messageInfo_CheckHealthResponse.Size(m)
}
func (m *CheckHealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckHealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckHealthResponse proto.InternalMessageInfo

type CreateCustomerRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ParentKey            string   `protobuf:"bytes,2,opt,name=parent_key,json=parentKey,proto3" json:"parent_key,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerRequest) Reset()         { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()    {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{4}
}

func (m *CreateCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerRequest.Unmarshal(m, b)
}
func (m *CreateCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerRequest.Marshal(b, m, deterministic)
}
func (m *CreateCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerRequest.Merge(m, src)
}
func (m *CreateCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerRequest.Size(m)
}
func (m *CreateCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerRequest proto.InternalMessageInfo

func (m *CreateCustomerRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateCustomerRequest) GetParentKey() string {
	if m != nil {
		return m.ParentKey
	}
	return ""
}

func (m *CreateCustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CreateCustomerResponse struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerResponse) Reset()         { *m = CreateCustomerResponse{} }
func (m *CreateCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerResponse) ProtoMessage()    {}
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{5}
}

func (m *CreateCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerResponse.Unmarshal(m, b)
}
func (m *CreateCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerResponse.Marshal(b, m, deterministic)
}
func (m *CreateCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerResponse.Merge(m, src)
}
func (m *CreateCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerResponse.Size(m)
}
func (m *CreateCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerResponse proto.InternalMessageInfo

func (m *CreateCustomerResponse) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type GetCustomerRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerRequest) Reset()         { *m = GetCustomerRequest{} }
func (m *GetCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomerRequest) ProtoMessage()    {}
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{6}
}

func (m *GetCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerRequest.Unmarshal(m, b)
}
func (m *GetCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerRequest.Marshal(b, m, deterministic)
}
func (m *GetCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerRequest.Merge(m, src)
}
func (m *GetCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomerRequest.Size(m)
}
func (m *GetCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerRequest proto.InternalMessageInfo

func (m *GetCustomerRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetCustomerResponse struct {
	Key                  string            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CustomerId           string            `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ParentKey            string            `protobuf:"bytes,3,opt,name=parent_key,json=parentKey,proto3" json:"parent_key,omitempty"`
	Email                string            `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	AccountStatus        string            `protobuf:"bytes,5,opt,name=account_status,json=accountStatus,proto3" json:"account_status,omitempty"`
	SubscriptionStatus   string            `protobuf:"bytes,6,opt,name=subscription_status,json=subscriptionStatus,proto3" json:"subscription_status,omitempty"`
	Balance              int64             `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	Billable             bool              `protobuf:"varint,8,opt,name=billable,proto3" json:"billable,omitempty"`
	Delinquent           bool              `protobuf:"varint,9,opt,name=delinquent,proto3" json:"delinquent,omitempty"`
	CreatedAt            int64             `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	InvoicePeriod        *Period           `protobuf:"bytes,11,opt,name=invoice_period,json=invoicePeriod,proto3" json:"invoice_period,omitempty"`
	DailyUsage           map[string]*Usage `protobuf:"bytes,12,rep,name=daily_usage,json=dailyUsage,proto3" json:"daily_usage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Dependents           int64             `protobuf:"varint,13,opt,name=dependents,proto3" json:"dependents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetCustomerResponse) Reset()         { *m = GetCustomerResponse{} }
func (m *GetCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*GetCustomerResponse) ProtoMessage()    {}
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{7}
}

func (m *GetCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerResponse.Unmarshal(m, b)
}
func (m *GetCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerResponse.Marshal(b, m, deterministic)
}
func (m *GetCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerResponse.Merge(m, src)
}
func (m *GetCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_GetCustomerResponse.Size(m)
}
func (m *GetCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerResponse proto.InternalMessageInfo

func (m *GetCustomerResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetCustomerResponse) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *GetCustomerResponse) GetParentKey() string {
	if m != nil {
		return m.ParentKey
	}
	return ""
}

func (m *GetCustomerResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetCustomerResponse) GetAccountStatus() string {
	if m != nil {
		return m.AccountStatus
	}
	return ""
}

func (m *GetCustomerResponse) GetSubscriptionStatus() string {
	if m != nil {
		return m.SubscriptionStatus
	}
	return ""
}

func (m *GetCustomerResponse) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *GetCustomerResponse) GetBillable() bool {
	if m != nil {
		return m.Billable
	}
	return false
}

func (m *GetCustomerResponse) GetDelinquent() bool {
	if m != nil {
		return m.Delinquent
	}
	return false
}

func (m *GetCustomerResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GetCustomerResponse) GetInvoicePeriod() *Period {
	if m != nil {
		return m.InvoicePeriod
	}
	return nil
}

func (m *GetCustomerResponse) GetDailyUsage() map[string]*Usage {
	if m != nil {
		return m.DailyUsage
	}
	return nil
}

func (m *GetCustomerResponse) GetDependents() int64 {
	if m != nil {
		return m.Dependents
	}
	return 0
}

type ListDependentCustomersRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDependentCustomersRequest) Reset()         { *m = ListDependentCustomersRequest{} }
func (m *ListDependentCustomersRequest) String() string { return proto.CompactTextString(m) }
func (*ListDependentCustomersRequest) ProtoMessage()    {}
func (*ListDependentCustomersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{8}
}

func (m *ListDependentCustomersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDependentCustomersRequest.Unmarshal(m, b)
}
func (m *ListDependentCustomersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDependentCustomersRequest.Marshal(b, m, deterministic)
}
func (m *ListDependentCustomersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDependentCustomersRequest.Merge(m, src)
}
func (m *ListDependentCustomersRequest) XXX_Size() int {
	return xxx_messageInfo_ListDependentCustomersRequest.Size(m)
}
func (m *ListDependentCustomersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDependentCustomersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDependentCustomersRequest proto.InternalMessageInfo

func (m *ListDependentCustomersRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ListDependentCustomersRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListDependentCustomersRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ListDependentCustomersResponse struct {
	Customers            []*GetCustomerResponse `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	NextOffset           int64                  `protobuf:"varint,2,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListDependentCustomersResponse) Reset()         { *m = ListDependentCustomersResponse{} }
func (m *ListDependentCustomersResponse) String() string { return proto.CompactTextString(m) }
func (*ListDependentCustomersResponse) ProtoMessage()    {}
func (*ListDependentCustomersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{9}
}

func (m *ListDependentCustomersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDependentCustomersResponse.Unmarshal(m, b)
}
func (m *ListDependentCustomersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDependentCustomersResponse.Marshal(b, m, deterministic)
}
func (m *ListDependentCustomersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDependentCustomersResponse.Merge(m, src)
}
func (m *ListDependentCustomersResponse) XXX_Size() int {
	return xxx_messageInfo_ListDependentCustomersResponse.Size(m)
}
func (m *ListDependentCustomersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDependentCustomersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDependentCustomersResponse proto.InternalMessageInfo

func (m *ListDependentCustomersResponse) GetCustomers() []*GetCustomerResponse {
	if m != nil {
		return m.Customers
	}
	return nil
}

func (m *ListDependentCustomersResponse) GetNextOffset() int64 {
	if m != nil {
		return m.NextOffset
	}
	return 0
}

type GetCustomerSessionRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerSessionRequest) Reset()         { *m = GetCustomerSessionRequest{} }
func (m *GetCustomerSessionRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomerSessionRequest) ProtoMessage()    {}
func (*GetCustomerSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{10}
}

func (m *GetCustomerSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerSessionRequest.Unmarshal(m, b)
}
func (m *GetCustomerSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerSessionRequest.Marshal(b, m, deterministic)
}
func (m *GetCustomerSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerSessionRequest.Merge(m, src)
}
func (m *GetCustomerSessionRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomerSessionRequest.Size(m)
}
func (m *GetCustomerSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerSessionRequest proto.InternalMessageInfo

func (m *GetCustomerSessionRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetCustomerSessionResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerSessionResponse) Reset()         { *m = GetCustomerSessionResponse{} }
func (m *GetCustomerSessionResponse) String() string { return proto.CompactTextString(m) }
func (*GetCustomerSessionResponse) ProtoMessage()    {}
func (*GetCustomerSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{11}
}

func (m *GetCustomerSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerSessionResponse.Unmarshal(m, b)
}
func (m *GetCustomerSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerSessionResponse.Marshal(b, m, deterministic)
}
func (m *GetCustomerSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerSessionResponse.Merge(m, src)
}
func (m *GetCustomerSessionResponse) XXX_Size() int {
	return xxx_messageInfo_GetCustomerSessionResponse.Size(m)
}
func (m *GetCustomerSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerSessionResponse proto.InternalMessageInfo

func (m *GetCustomerSessionResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type UpdateCustomerRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Balance              int64    `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Billable             bool     `protobuf:"varint,3,opt,name=billable,proto3" json:"billable,omitempty"`
	Delinquent           bool     `protobuf:"varint,4,opt,name=delinquent,proto3" json:"delinquent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCustomerRequest) Reset()         { *m = UpdateCustomerRequest{} }
func (m *UpdateCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCustomerRequest) ProtoMessage()    {}
func (*UpdateCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{12}
}

func (m *UpdateCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCustomerRequest.Unmarshal(m, b)
}
func (m *UpdateCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCustomerRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCustomerRequest.Merge(m, src)
}
func (m *UpdateCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCustomerRequest.Size(m)
}
func (m *UpdateCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCustomerRequest proto.InternalMessageInfo

func (m *UpdateCustomerRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *UpdateCustomerRequest) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *UpdateCustomerRequest) GetBillable() bool {
	if m != nil {
		return m.Billable
	}
	return false
}

func (m *UpdateCustomerRequest) GetDelinquent() bool {
	if m != nil {
		return m.Delinquent
	}
	return false
}

type UpdateCustomerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCustomerResponse) Reset()         { *m = UpdateCustomerResponse{} }
func (m *UpdateCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCustomerResponse) ProtoMessage()    {}
func (*UpdateCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{13}
}

func (m *UpdateCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCustomerResponse.Unmarshal(m, b)
}
func (m *UpdateCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCustomerResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCustomerResponse.Merge(m, src)
}
func (m *UpdateCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCustomerResponse.Size(m)
}
func (m *UpdateCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCustomerResponse proto.InternalMessageInfo

type UpdateCustomerSubscriptionRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	InvoicePeriod        *Period  `protobuf:"bytes,3,opt,name=invoice_period,json=invoicePeriod,proto3" json:"invoice_period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCustomerSubscriptionRequest) Reset()         { *m = UpdateCustomerSubscriptionRequest{} }
func (m *UpdateCustomerSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCustomerSubscriptionRequest) ProtoMessage()    {}
func (*UpdateCustomerSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{14}
}

func (m *UpdateCustomerSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCustomerSubscriptionRequest.Unmarshal(m, b)
}
func (m *UpdateCustomerSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCustomerSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCustomerSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCustomerSubscriptionRequest.Merge(m, src)
}
func (m *UpdateCustomerSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCustomerSubscriptionRequest.Size(m)
}
func (m *UpdateCustomerSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCustomerSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCustomerSubscriptionRequest proto.InternalMessageInfo

func (m *UpdateCustomerSubscriptionRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *UpdateCustomerSubscriptionRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateCustomerSubscriptionRequest) GetInvoicePeriod() *Period {
	if m != nil {
		return m.InvoicePeriod
	}
	return nil
}

type UpdateCustomerSubscriptionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCustomerSubscriptionResponse) Reset()         { *m = UpdateCustomerSubscriptionResponse{} }
func (m *UpdateCustomerSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCustomerSubscriptionResponse) ProtoMessage()    {}
func (*UpdateCustomerSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{15}
}

func (m *UpdateCustomerSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCustomerSubscriptionResponse.Unmarshal(m, b)
}
func (m *UpdateCustomerSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCustomerSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCustomerSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCustomerSubscriptionResponse.Merge(m, src)
}
func (m *UpdateCustomerSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCustomerSubscriptionResponse.Size(m)
}
func (m *UpdateCustomerSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCustomerSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCustomerSubscriptionResponse proto.InternalMessageInfo

type RecreateCustomerSubscriptionRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecreateCustomerSubscriptionRequest) Reset()         { *m = RecreateCustomerSubscriptionRequest{} }
func (m *RecreateCustomerSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*RecreateCustomerSubscriptionRequest) ProtoMessage()    {}
func (*RecreateCustomerSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{16}
}

func (m *RecreateCustomerSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecreateCustomerSubscriptionRequest.Unmarshal(m, b)
}
func (m *RecreateCustomerSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecreateCustomerSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *RecreateCustomerSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecreateCustomerSubscriptionRequest.Merge(m, src)
}
func (m *RecreateCustomerSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_RecreateCustomerSubscriptionRequest.Size(m)
}
func (m *RecreateCustomerSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecreateCustomerSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecreateCustomerSubscriptionRequest proto.InternalMessageInfo

func (m *RecreateCustomerSubscriptionRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RecreateCustomerSubscriptionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecreateCustomerSubscriptionResponse) Reset()         { *m = RecreateCustomerSubscriptionResponse{} }
func (m *RecreateCustomerSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*RecreateCustomerSubscriptionResponse) ProtoMessage()    {}
func (*RecreateCustomerSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{17}
}

func (m *RecreateCustomerSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecreateCustomerSubscriptionResponse.Unmarshal(m, b)
}
func (m *RecreateCustomerSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecreateCustomerSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *RecreateCustomerSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecreateCustomerSubscriptionResponse.Merge(m, src)
}
func (m *RecreateCustomerSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_RecreateCustomerSubscriptionResponse.Size(m)
}
func (m *RecreateCustomerSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecreateCustomerSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecreateCustomerSubscriptionResponse proto.InternalMessageInfo

type DeleteCustomerRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomerRequest) Reset()         { *m = DeleteCustomerRequest{} }
func (m *DeleteCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomerRequest) ProtoMessage()    {}
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{18}
}

func (m *DeleteCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomerRequest.Unmarshal(m, b)
}
func (m *DeleteCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomerRequest.Merge(m, src)
}
func (m *DeleteCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomerRequest.Size(m)
}
func (m *DeleteCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomerRequest proto.InternalMessageInfo

func (m *DeleteCustomerRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteCustomerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomerResponse) Reset()         { *m = DeleteCustomerResponse{} }
func (m *DeleteCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomerResponse) ProtoMessage()    {}
func (*DeleteCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{19}
}

func (m *DeleteCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomerResponse.Unmarshal(m, b)
}
func (m *DeleteCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomerResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomerResponse.Merge(m, src)
}
func (m *DeleteCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomerResponse.Size(m)
}
func (m *DeleteCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomerResponse proto.InternalMessageInfo

type IncCustomerUsageRequest struct {
	Key                  string           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ProductUsage         map[string]int64 `protobuf:"bytes,2,rep,name=product_usage,json=productUsage,proto3" json:"product_usage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *IncCustomerUsageRequest) Reset()         { *m = IncCustomerUsageRequest{} }
func (m *IncCustomerUsageRequest) String() string { return proto.CompactTextString(m) }
func (*IncCustomerUsageRequest) ProtoMessage()    {}
func (*IncCustomerUsageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{20}
}

func (m *IncCustomerUsageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncCustomerUsageRequest.Unmarshal(m, b)
}
func (m *IncCustomerUsageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncCustomerUsageRequest.Marshal(b, m, deterministic)
}
func (m *IncCustomerUsageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncCustomerUsageRequest.Merge(m, src)
}
func (m *IncCustomerUsageRequest) XXX_Size() int {
	return xxx_messageInfo_IncCustomerUsageRequest.Size(m)
}
func (m *IncCustomerUsageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncCustomerUsageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncCustomerUsageRequest proto.InternalMessageInfo

func (m *IncCustomerUsageRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *IncCustomerUsageRequest) GetProductUsage() map[string]int64 {
	if m != nil {
		return m.ProductUsage
	}
	return nil
}

type IncCustomerUsageResponse struct {
	InvoicePeriod        *Period           `protobuf:"bytes,1,opt,name=invoice_period,json=invoicePeriod,proto3" json:"invoice_period,omitempty"`
	DailyUsage           map[string]*Usage `protobuf:"bytes,2,rep,name=daily_usage,json=dailyUsage,proto3" json:"daily_usage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *IncCustomerUsageResponse) Reset()         { *m = IncCustomerUsageResponse{} }
func (m *IncCustomerUsageResponse) String() string { return proto.CompactTextString(m) }
func (*IncCustomerUsageResponse) ProtoMessage()    {}
func (*IncCustomerUsageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6bad727a6da184, []int{21}
}

func (m *IncCustomerUsageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncCustomerUsageResponse.Unmarshal(m, b)
}
func (m *IncCustomerUsageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncCustomerUsageResponse.Marshal(b, m, deterministic)
}
func (m *IncCustomerUsageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncCustomerUsageResponse.Merge(m, src)
}
func (m *IncCustomerUsageResponse) XXX_Size() int {
	return xxx_messageInfo_IncCustomerUsageResponse.Size(m)
}
func (m *IncCustomerUsageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncCustomerUsageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncCustomerUsageResponse proto.InternalMessageInfo

func (m *IncCustomerUsageResponse) GetInvoicePeriod() *Period {
	if m != nil {
		return m.InvoicePeriod
	}
	return nil
}

func (m *IncCustomerUsageResponse) GetDailyUsage() map[string]*Usage {
	if m != nil {
		return m.DailyUsage
	}
	return nil
}

func init() {
	proto.RegisterType((*Period)(nil), "api.billingd.pb.Period")
	proto.RegisterType((*Usage)(nil), "api.billingd.pb.Usage")
	proto.RegisterType((*CheckHealthRequest)(nil), "api.billingd.pb.CheckHealthRequest")
	proto.RegisterType((*CheckHealthResponse)(nil), "api.billingd.pb.CheckHealthResponse")
	proto.RegisterType((*CreateCustomerRequest)(nil), "api.billingd.pb.CreateCustomerRequest")
	proto.RegisterType((*CreateCustomerResponse)(nil), "api.billingd.pb.CreateCustomerResponse")
	proto.RegisterType((*GetCustomerRequest)(nil), "api.billingd.pb.GetCustomerRequest")
	proto.RegisterType((*GetCustomerResponse)(nil), "api.billingd.pb.GetCustomerResponse")
	proto.RegisterMapType((map[string]*Usage)(nil), "api.billingd.pb.GetCustomerResponse.DailyUsageEntry")
	proto.RegisterType((*ListDependentCustomersRequest)(nil), "api.billingd.pb.ListDependentCustomersRequest")
	proto.RegisterType((*ListDependentCustomersResponse)(nil), "api.billingd.pb.ListDependentCustomersResponse")
	proto.RegisterType((*GetCustomerSessionRequest)(nil), "api.billingd.pb.GetCustomerSessionRequest")
	proto.RegisterType((*GetCustomerSessionResponse)(nil), "api.billingd.pb.GetCustomerSessionResponse")
	proto.RegisterType((*UpdateCustomerRequest)(nil), "api.billingd.pb.UpdateCustomerRequest")
	proto.RegisterType((*UpdateCustomerResponse)(nil), "api.billingd.pb.UpdateCustomerResponse")
	proto.RegisterType((*UpdateCustomerSubscriptionRequest)(nil), "api.billingd.pb.UpdateCustomerSubscriptionRequest")
	proto.RegisterType((*UpdateCustomerSubscriptionResponse)(nil), "api.billingd.pb.UpdateCustomerSubscriptionResponse")
	proto.RegisterType((*RecreateCustomerSubscriptionRequest)(nil), "api.billingd.pb.RecreateCustomerSubscriptionRequest")
	proto.RegisterType((*RecreateCustomerSubscriptionResponse)(nil), "api.billingd.pb.RecreateCustomerSubscriptionResponse")
	proto.RegisterType((*DeleteCustomerRequest)(nil), "api.billingd.pb.DeleteCustomerRequest")
	proto.RegisterType((*DeleteCustomerResponse)(nil), "api.billingd.pb.DeleteCustomerResponse")
	proto.RegisterType((*IncCustomerUsageRequest)(nil), "api.billingd.pb.IncCustomerUsageRequest")
	proto.RegisterMapType((map[string]int64)(nil), "api.billingd.pb.IncCustomerUsageRequest.ProductUsageEntry")
	proto.RegisterType((*IncCustomerUsageResponse)(nil), "api.billingd.pb.IncCustomerUsageResponse")
	proto.RegisterMapType((map[string]*Usage)(nil), "api.billingd.pb.IncCustomerUsageResponse.DailyUsageEntry")
}

func init() { proto.RegisterFile("api/billingd/pb/billingd.proto", fileDescriptor_8c6bad727a6da184) }

var fileDescriptor_8c6bad727a6da184 = []byte{
	// 1048 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x8e, 0x93, 0x34, 0x4d, 0x4e, 0xb6, 0xdd, 0x65, 0xda, 0x66, 0xbd, 0x16, 0x5b, 0x8a, 0xb7,
	0x94, 0x2c, 0x3f, 0x8e, 0xc8, 0x82, 0x60, 0xf7, 0x02, 0xb4, 0x6d, 0x57, 0x50, 0x81, 0x44, 0xe5,
	0xa8, 0x37, 0x45, 0xc2, 0x72, 0xec, 0x69, 0x3b, 0x5a, 0x77, 0xec, 0xb5, 0xc7, 0x55, 0x2b, 0xae,
	0x11, 0x57, 0xe5, 0x09, 0x78, 0x25, 0xee, 0x79, 0x02, 0x9e, 0x03, 0xcd, 0x78, 0x92, 0xfa, 0x37,
	0x71, 0x2f, 0xb8, 0xf3, 0x7c, 0x73, 0xce, 0x9c, 0x73, 0x66, 0xce, 0xf7, 0xcd, 0x18, 0xb6, 0xed,
	0x80, 0x8c, 0xa6, 0xc4, 0xf3, 0x08, 0x3d, 0x77, 0x47, 0xc1, 0x74, 0xfe, 0x6d, 0x04, 0xa1, 0xcf,
	0x7c, 0xf4, 0xd0, 0x0e, 0x88, 0x71, 0x87, 0x4d, 0xf5, 0x7d, 0xe8, 0x1c, 0xe3, 0x90, 0xf8, 0x2e,
	0x7a, 0x0a, 0x10, 0x53, 0x72, 0x6d, 0x45, 0xcc, 0x0e, 0x99, 0xaa, 0xec, 0x28, 0xc3, 0x96, 0xd9,
	0xe3, 0xc8, 0x84, 0x03, 0xe8, 0x09, 0x74, 0xc5, 0x34, 0xa6, 0xae, 0xda, 0x14, 0x93, 0xab, 0x7c,
	0xfc, 0x86, 0xba, 0xfa, 0x2f, 0xb0, 0x72, 0x12, 0xd9, 0xe7, 0x18, 0x6d, 0xc2, 0x4a, 0x4c, 0x09,
	0x8b, 0xa4, 0x77, 0x32, 0xe0, 0x28, 0xf3, 0x99, 0xed, 0x49, 0xb7, 0x64, 0x80, 0x10, 0xb4, 0xcf,
	0x42, 0x8c, 0xd5, 0x96, 0x00, 0xc5, 0x37, 0xc7, 0x1c, 0x3f, 0x62, 0x6a, 0x3b, 0xc1, 0xf8, 0xb7,
	0xbe, 0x09, 0xe8, 0xe0, 0x02, 0x3b, 0x6f, 0x7f, 0xc0, 0xb6, 0xc7, 0x2e, 0x4c, 0xfc, 0x2e, 0xc6,
	0x11, 0xd3, 0xb7, 0x60, 0x23, 0x83, 0x46, 0x81, 0x4f, 0x23, 0xac, 0xff, 0x0a, 0x5b, 0x07, 0x21,
	0xb6, 0x19, 0x3e, 0x88, 0x23, 0xe6, 0x5f, 0xe2, 0x50, 0xda, 0xa3, 0x47, 0xd0, 0x7a, 0x8b, 0x6f,
	0x44, 0x5e, 0x3d, 0x93, 0x7f, 0xf2, 0x72, 0x03, 0x3b, 0xc4, 0x94, 0x59, 0x7c, 0xa2, 0x29, 0x26,
	0x7a, 0x09, 0xf2, 0x23, 0xbe, 0xe1, 0x49, 0xe3, 0x4b, 0x9b, 0x78, 0x22, 0xbf, 0x9e, 0x99, 0x0c,
	0xf4, 0x97, 0x30, 0xc8, 0xaf, 0x9f, 0x44, 0x46, 0x1f, 0x40, 0xdf, 0x91, 0x98, 0x45, 0x5c, 0x19,
	0x08, 0x66, 0xd0, 0x91, 0xab, 0xef, 0x01, 0xfa, 0x1e, 0xb3, 0xa5, 0x79, 0xe9, 0xff, 0xb4, 0x61,
	0x23, 0x63, 0x28, 0x03, 0x14, 0x2b, 0xc8, 0x85, 0x6c, 0xe6, 0x43, 0xe6, 0x4a, 0x6c, 0x55, 0x96,
	0xd8, 0x4e, 0x95, 0x88, 0x3e, 0x82, 0x75, 0xdb, 0x71, 0xfc, 0x98, 0x32, 0xde, 0x09, 0x2c, 0x8e,
	0xd4, 0x15, 0x31, 0xbd, 0x26, 0xd1, 0x89, 0x00, 0xd1, 0x08, 0x36, 0xa2, 0x78, 0x1a, 0x39, 0x21,
	0x09, 0x18, 0xf1, 0xe9, 0xcc, 0xb6, 0x23, 0x6c, 0x51, 0x7a, 0x4a, 0x3a, 0xa8, 0xb0, 0x3a, 0xb5,
	0x3d, 0x9b, 0x3a, 0x58, 0x5d, 0x4d, 0xda, 0x47, 0x0e, 0x91, 0x06, 0x5d, 0xde, 0x91, 0xf6, 0xd4,
	0xc3, 0x6a, 0x77, 0x47, 0x19, 0x76, 0xcd, 0xf9, 0x18, 0x6d, 0x03, 0xb8, 0xd8, 0x23, 0xf4, 0x5d,
	0x8c, 0x29, 0x53, 0x7b, 0x62, 0x36, 0x85, 0xf0, 0x12, 0x1d, 0x71, 0x20, 0xae, 0x65, 0x33, 0x15,
	0x92, 0xa6, 0x95, 0xc8, 0x6b, 0x86, 0xbe, 0x85, 0x75, 0x42, 0xaf, 0x7c, 0xe2, 0x60, 0x2b, 0x10,
	0x5d, 0xae, 0xf6, 0x77, 0x94, 0x61, 0x7f, 0xfc, 0xd8, 0xc8, 0xf1, 0xc0, 0x48, 0x48, 0x60, 0xae,
	0x49, 0x73, 0xc9, 0x89, 0x13, 0xe8, 0xbb, 0x36, 0xf1, 0x6e, 0xac, 0x98, 0xf7, 0xb7, 0xfa, 0x60,
	0xa7, 0x35, 0xec, 0x8f, 0xbf, 0x2c, 0x38, 0x97, 0x9c, 0x97, 0x71, 0xc8, 0xfd, 0x04, 0x2d, 0xde,
	0x50, 0x16, 0xde, 0x98, 0xe0, 0xce, 0x81, 0xa4, 0xaa, 0x00, 0x53, 0x17, 0x53, 0x16, 0xa9, 0x6b,
	0x22, 0xeb, 0x14, 0xa2, 0x9d, 0xc0, 0xc3, 0x9c, 0x7b, 0xc9, 0xf1, 0x7f, 0x06, 0x2b, 0x57, 0xb6,
	0x17, 0x63, 0x71, 0xf0, 0xfd, 0xf1, 0xa0, 0x90, 0x95, 0xf0, 0x36, 0x13, 0xa3, 0x57, 0xcd, 0x6f,
	0x14, 0xdd, 0x82, 0xa7, 0x3f, 0x91, 0x88, 0x1d, 0xce, 0x02, 0xcd, 0x72, 0x8e, 0xaa, 0x59, 0x32,
	0x80, 0x8e, 0x7f, 0x76, 0x16, 0x61, 0x26, 0xc9, 0x2b, 0x47, 0xbc, 0x77, 0x3c, 0x72, 0x49, 0x98,
	0xa4, 0x6f, 0x32, 0xd0, 0x7f, 0x57, 0x60, 0xbb, 0x2a, 0x82, 0x6c, 0xe3, 0x7d, 0xe8, 0xcd, 0x3a,
	0x94, 0xcb, 0x04, 0xdf, 0xcf, 0xdd, 0x3a, 0xfb, 0x69, 0xde, 0xb9, 0xf1, 0xc6, 0xa7, 0xf8, 0x9a,
	0x59, 0x99, 0xcc, 0x80, 0x43, 0x3f, 0x0b, 0x44, 0xff, 0x1c, 0x9e, 0xa4, 0x96, 0x98, 0xe0, 0x28,
	0x22, 0x3e, 0xad, 0xa6, 0x9c, 0x01, 0x5a, 0x99, 0xf9, 0x1d, 0xf1, 0xe2, 0xd0, 0x9b, 0xd9, 0xc7,
	0xa1, 0xa7, 0xff, 0xa9, 0xc0, 0xd6, 0x49, 0xe0, 0x96, 0xc8, 0xcc, 0x32, 0x15, 0x48, 0xb3, 0xa0,
	0x59, 0xcd, 0x82, 0xd6, 0x42, 0x16, 0xb4, 0xf3, 0x2c, 0xd0, 0x55, 0x18, 0xe4, 0xf3, 0x91, 0x82,
	0xf8, 0x97, 0x02, 0x1f, 0x66, 0xa7, 0x26, 0x29, 0x6a, 0xd6, 0x4e, 0x7b, 0x00, 0x1d, 0x49, 0xf0,
	0x44, 0x65, 0xe4, 0xa8, 0x84, 0x5f, 0xad, 0xfb, 0xf0, 0x4b, 0xdf, 0x05, 0x7d, 0x51, 0x76, 0xb2,
	0x88, 0xaf, 0xe1, 0x99, 0x89, 0x9d, 0x8c, 0xee, 0x96, 0x55, 0x51, 0x3c, 0xd8, 0x3d, 0xd8, 0x5d,
	0xec, 0x28, 0x03, 0x3c, 0x87, 0xad, 0x43, 0xec, 0xe1, 0x1a, 0xd7, 0x06, 0xdf, 0xea, 0xbc, 0xa9,
	0x5c, 0xe4, 0x6f, 0x05, 0x1e, 0x1f, 0x51, 0x67, 0x86, 0x27, 0xec, 0xab, 0x24, 0x96, 0x05, 0x6b,
	0x41, 0xe8, 0xbb, 0xb1, 0xc3, 0xa4, 0xb6, 0x34, 0x05, 0x17, 0x5e, 0x15, 0x36, 0xae, 0x62, 0x49,
	0xe3, 0x38, 0xf1, 0x4e, 0x29, 0xcc, 0x83, 0x20, 0x05, 0x69, 0xdf, 0xc1, 0x7b, 0x05, 0x93, 0x92,
	0x3c, 0x36, 0xd3, 0x2a, 0xd2, 0x4a, 0xab, 0xc5, 0x6d, 0x13, 0xd4, 0x62, 0x70, 0x49, 0x8a, 0xe2,
	0xc1, 0x2b, 0xf7, 0x12, 0xd6, 0xd3, 0xac, 0xb0, 0x26, 0xc5, 0xbf, 0xac, 0x51, 0xfc, 0x72, 0x75,
	0xfd, 0x9f, 0xd4, 0x73, 0xfc, 0x6f, 0x17, 0xe0, 0xf5, 0xf1, 0xd1, 0x04, 0x87, 0x57, 0xc4, 0xc1,
	0xbc, 0x82, 0xd4, 0x0b, 0x04, 0x3d, 0x2b, 0x2c, 0x50, 0x7c, 0xb5, 0x68, 0xbb, 0x8b, 0x8d, 0x64,
	0x23, 0x35, 0x90, 0x03, 0xeb, 0xd9, 0x67, 0x06, 0xda, 0x2b, 0x7a, 0x96, 0xbd, 0x73, 0xb4, 0x8f,
	0x97, 0xda, 0xcd, 0x83, 0x9c, 0x42, 0x3f, 0xa5, 0x7a, 0x25, 0x05, 0x14, 0x9f, 0x2b, 0x5a, 0x2d,
	0xa9, 0xd6, 0x1b, 0xe8, 0x37, 0x18, 0x94, 0xdf, 0x03, 0xc8, 0x28, 0xac, 0xb0, 0xf0, 0x4a, 0xd2,
	0x46, 0xb5, 0xed, 0xe7, 0xc1, 0xfd, 0xcc, 0x4b, 0x4b, 0xca, 0x39, 0xfa, 0x64, 0x51, 0xea, 0xd9,
	0x2b, 0x42, 0xfb, 0xb4, 0x96, 0x6d, 0xfa, 0xb8, 0xb2, 0x2a, 0x56, 0x72, 0x5c, 0xa5, 0xf7, 0x45,
	0xc9, 0x71, 0x55, 0xe8, 0x78, 0x03, 0xfd, 0xa1, 0x80, 0x56, 0xad, 0x95, 0x68, 0xbc, 0x64, 0xa5,
	0x12, 0xc1, 0xd4, 0x5e, 0xdc, 0xcb, 0x67, 0x9e, 0xc9, 0xad, 0x02, 0xef, 0x2f, 0x92, 0x55, 0x54,
	0x7c, 0x20, 0xd5, 0x90, 0x6f, 0xed, 0xab, 0x7b, 0x7a, 0xa5, 0xb7, 0x3f, 0x2b, 0xc9, 0x25, 0xdb,
	0x5f, 0x2a, 0xef, 0x25, 0xdb, 0x5f, 0xa1, 0xed, 0x0d, 0x44, 0xe0, 0x51, 0x5e, 0x8c, 0xd0, 0xb0,
	0xae, 0x58, 0x6b, 0xcf, 0x6b, 0x2b, 0x9b, 0xde, 0xd8, 0xff, 0xe2, 0x74, 0x74, 0x4e, 0xd8, 0x45,
	0x3c, 0x35, 0x1c, 0xff, 0x72, 0xc4, 0xf0, 0x35, 0x23, 0x1e, 0x26, 0xfe, 0xec, 0x6b, 0x74, 0x35,
	0x1e, 0xe5, 0xfe, 0xf2, 0xa6, 0x1d, 0xf1, 0x77, 0xf7, 0xe2, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x5a, 0x48, 0x7b, 0xa8, 0xff, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIServiceClient is the client API for APIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIServiceClient interface {
	CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthResponse, error)
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerResponse, error)
	GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*GetCustomerResponse, error)
	ListDependentCustomers(ctx context.Context, in *ListDependentCustomersRequest, opts ...grpc.CallOption) (*ListDependentCustomersResponse, error)
	GetCustomerSession(ctx context.Context, in *GetCustomerSessionRequest, opts ...grpc.CallOption) (*GetCustomerSessionResponse, error)
	UpdateCustomer(ctx context.Context, in *UpdateCustomerRequest, opts ...grpc.CallOption) (*UpdateCustomerResponse, error)
	UpdateCustomerSubscription(ctx context.Context, in *UpdateCustomerSubscriptionRequest, opts ...grpc.CallOption) (*UpdateCustomerSubscriptionResponse, error)
	RecreateCustomerSubscription(ctx context.Context, in *RecreateCustomerSubscriptionRequest, opts ...grpc.CallOption) (*RecreateCustomerSubscriptionResponse, error)
	DeleteCustomer(ctx context.Context, in *DeleteCustomerRequest, opts ...grpc.CallOption) (*DeleteCustomerResponse, error)
	IncCustomerUsage(ctx context.Context, in *IncCustomerUsageRequest, opts ...grpc.CallOption) (*IncCustomerUsageResponse, error)
}

type aPIServiceClient struct {
	cc *grpc.ClientConn
}

func NewAPIServiceClient(cc *grpc.ClientConn) APIServiceClient {
	return &aPIServiceClient{cc}
}

func (c *aPIServiceClient) CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthResponse, error) {
	out := new(CheckHealthResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/CheckHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerResponse, error) {
	out := new(CreateCustomerResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*GetCustomerResponse, error) {
	out := new(GetCustomerResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/GetCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) ListDependentCustomers(ctx context.Context, in *ListDependentCustomersRequest, opts ...grpc.CallOption) (*ListDependentCustomersResponse, error) {
	out := new(ListDependentCustomersResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/ListDependentCustomers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) GetCustomerSession(ctx context.Context, in *GetCustomerSessionRequest, opts ...grpc.CallOption) (*GetCustomerSessionResponse, error) {
	out := new(GetCustomerSessionResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/GetCustomerSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) UpdateCustomer(ctx context.Context, in *UpdateCustomerRequest, opts ...grpc.CallOption) (*UpdateCustomerResponse, error) {
	out := new(UpdateCustomerResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/UpdateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) UpdateCustomerSubscription(ctx context.Context, in *UpdateCustomerSubscriptionRequest, opts ...grpc.CallOption) (*UpdateCustomerSubscriptionResponse, error) {
	out := new(UpdateCustomerSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/UpdateCustomerSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) RecreateCustomerSubscription(ctx context.Context, in *RecreateCustomerSubscriptionRequest, opts ...grpc.CallOption) (*RecreateCustomerSubscriptionResponse, error) {
	out := new(RecreateCustomerSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/RecreateCustomerSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) DeleteCustomer(ctx context.Context, in *DeleteCustomerRequest, opts ...grpc.CallOption) (*DeleteCustomerResponse, error) {
	out := new(DeleteCustomerResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/DeleteCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServiceClient) IncCustomerUsage(ctx context.Context, in *IncCustomerUsageRequest, opts ...grpc.CallOption) (*IncCustomerUsageResponse, error) {
	out := new(IncCustomerUsageResponse)
	err := c.cc.Invoke(ctx, "/api.billingd.pb.APIService/IncCustomerUsage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServiceServer is the server API for APIService service.
type APIServiceServer interface {
	CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthResponse, error)
	CreateCustomer(context.Context, *CreateCustomerRequest) (*CreateCustomerResponse, error)
	GetCustomer(context.Context, *GetCustomerRequest) (*GetCustomerResponse, error)
	ListDependentCustomers(context.Context, *ListDependentCustomersRequest) (*ListDependentCustomersResponse, error)
	GetCustomerSession(context.Context, *GetCustomerSessionRequest) (*GetCustomerSessionResponse, error)
	UpdateCustomer(context.Context, *UpdateCustomerRequest) (*UpdateCustomerResponse, error)
	UpdateCustomerSubscription(context.Context, *UpdateCustomerSubscriptionRequest) (*UpdateCustomerSubscriptionResponse, error)
	RecreateCustomerSubscription(context.Context, *RecreateCustomerSubscriptionRequest) (*RecreateCustomerSubscriptionResponse, error)
	DeleteCustomer(context.Context, *DeleteCustomerRequest) (*DeleteCustomerResponse, error)
	IncCustomerUsage(context.Context, *IncCustomerUsageRequest) (*IncCustomerUsageResponse, error)
}

// UnimplementedAPIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServiceServer struct {
}

func (*UnimplementedAPIServiceServer) CheckHealth(ctx context.Context, req *CheckHealthRequest) (*CheckHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}
func (*UnimplementedAPIServiceServer) CreateCustomer(ctx context.Context, req *CreateCustomerRequest) (*CreateCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (*UnimplementedAPIServiceServer) GetCustomer(ctx context.Context, req *GetCustomerRequest) (*GetCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomer not implemented")
}
func (*UnimplementedAPIServiceServer) ListDependentCustomers(ctx context.Context, req *ListDependentCustomersRequest) (*ListDependentCustomersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDependentCustomers not implemented")
}
func (*UnimplementedAPIServiceServer) GetCustomerSession(ctx context.Context, req *GetCustomerSessionRequest) (*GetCustomerSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerSession not implemented")
}
func (*UnimplementedAPIServiceServer) UpdateCustomer(ctx context.Context, req *UpdateCustomerRequest) (*UpdateCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCustomer not implemented")
}
func (*UnimplementedAPIServiceServer) UpdateCustomerSubscription(ctx context.Context, req *UpdateCustomerSubscriptionRequest) (*UpdateCustomerSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCustomerSubscription not implemented")
}
func (*UnimplementedAPIServiceServer) RecreateCustomerSubscription(ctx context.Context, req *RecreateCustomerSubscriptionRequest) (*RecreateCustomerSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecreateCustomerSubscription not implemented")
}
func (*UnimplementedAPIServiceServer) DeleteCustomer(ctx context.Context, req *DeleteCustomerRequest) (*DeleteCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCustomer not implemented")
}
func (*UnimplementedAPIServiceServer) IncCustomerUsage(ctx context.Context, req *IncCustomerUsageRequest) (*IncCustomerUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncCustomerUsage not implemented")
}

func RegisterAPIServiceServer(s *grpc.Server, srv APIServiceServer) {
	s.RegisterService(&_APIService_serviceDesc, srv)
}

func _APIService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/CheckHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).CheckHealth(ctx, req.(*CheckHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).CreateCustomer(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/GetCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetCustomer(ctx, req.(*GetCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_ListDependentCustomers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDependentCustomersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).ListDependentCustomers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/ListDependentCustomers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).ListDependentCustomers(ctx, req.(*ListDependentCustomersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_GetCustomerSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).GetCustomerSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/GetCustomerSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).GetCustomerSession(ctx, req.(*GetCustomerSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_UpdateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).UpdateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/UpdateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).UpdateCustomer(ctx, req.(*UpdateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_UpdateCustomerSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomerSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).UpdateCustomerSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/UpdateCustomerSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).UpdateCustomerSubscription(ctx, req.(*UpdateCustomerSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_RecreateCustomerSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecreateCustomerSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).RecreateCustomerSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/RecreateCustomerSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).RecreateCustomerSubscription(ctx, req.(*RecreateCustomerSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_DeleteCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).DeleteCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/DeleteCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).DeleteCustomer(ctx, req.(*DeleteCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIService_IncCustomerUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncCustomerUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServiceServer).IncCustomerUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.billingd.pb.APIService/IncCustomerUsage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServiceServer).IncCustomerUsage(ctx, req.(*IncCustomerUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _APIService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.billingd.pb.APIService",
	HandlerType: (*APIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckHealth",
			Handler:    _APIService_CheckHealth_Handler,
		},
		{
			MethodName: "CreateCustomer",
			Handler:    _APIService_CreateCustomer_Handler,
		},
		{
			MethodName: "GetCustomer",
			Handler:    _APIService_GetCustomer_Handler,
		},
		{
			MethodName: "ListDependentCustomers",
			Handler:    _APIService_ListDependentCustomers_Handler,
		},
		{
			MethodName: "GetCustomerSession",
			Handler:    _APIService_GetCustomerSession_Handler,
		},
		{
			MethodName: "UpdateCustomer",
			Handler:    _APIService_UpdateCustomer_Handler,
		},
		{
			MethodName: "UpdateCustomerSubscription",
			Handler:    _APIService_UpdateCustomerSubscription_Handler,
		},
		{
			MethodName: "RecreateCustomerSubscription",
			Handler:    _APIService_RecreateCustomerSubscription_Handler,
		},
		{
			MethodName: "DeleteCustomer",
			Handler:    _APIService_DeleteCustomer_Handler,
		},
		{
			MethodName: "IncCustomerUsage",
			Handler:    _APIService_IncCustomerUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/billingd/pb/billingd.proto",
}
