# syntax = docker/dockerfile:1-experimental

FROM golang:1.15.5-buster

RUN apt-get update && apt-get install -y \
  libssl-dev \
  ca-certificates

RUN go get github.com/go-delve/delve/cmd/dlv

ENV SRC_DIR /textile

COPY go.mod go.sum $SRC_DIR/
RUN cd $SRC_DIR \
  && go mod download

COPY . $SRC_DIR

RUN --mount=type=cache,target=/root/.cache/go-build \
  cd $SRC_DIR \
  && CGO_ENABLED=0 GOOS=linux go build -gcflags "all=-N -l" -o analyticsd api/analyticsd/main.go

FROM debian:buster
LABEL maintainer="Textile <contact@textile.io>"

ENV SRC_DIR /textile
COPY --from=0 /go/bin/dlv /usr/local/bin/dlv
COPY --from=0 /etc/ssl/certs /etc/ssl/certs
COPY --from=0 $SRC_DIR/analyticsd /usr/local/bin/analyticsd

EXPOSE 5000

ENV ANALYTICS_PATH /data/analytics
RUN adduser --home $ANALYTICS_PATH --disabled-login --gecos "" --ingroup users analytics

USER analytics

ENTRYPOINT ["/usr/local/bin/analyticsd"]
