// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package users_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListThreadsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListThreadsRequest) Reset()         { *m = ListThreadsRequest{} }
func (m *ListThreadsRequest) String() string { return proto.CompactTextString(m) }
func (*ListThreadsRequest) ProtoMessage()    {}
func (*ListThreadsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

func (m *ListThreadsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListThreadsRequest.Unmarshal(m, b)
}
func (m *ListThreadsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListThreadsRequest.Marshal(b, m, deterministic)
}
func (m *ListThreadsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListThreadsRequest.Merge(m, src)
}
func (m *ListThreadsRequest) XXX_Size() int {
	return xxx_messageInfo_ListThreadsRequest.Size(m)
}
func (m *ListThreadsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListThreadsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListThreadsRequest proto.InternalMessageInfo

type ListThreadsReply struct {
	List                 []*GetThreadReply `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListThreadsReply) Reset()         { *m = ListThreadsReply{} }
func (m *ListThreadsReply) String() string { return proto.CompactTextString(m) }
func (*ListThreadsReply) ProtoMessage()    {}
func (*ListThreadsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

func (m *ListThreadsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListThreadsReply.Unmarshal(m, b)
}
func (m *ListThreadsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListThreadsReply.Marshal(b, m, deterministic)
}
func (m *ListThreadsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListThreadsReply.Merge(m, src)
}
func (m *ListThreadsReply) XXX_Size() int {
	return xxx_messageInfo_ListThreadsReply.Size(m)
}
func (m *ListThreadsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListThreadsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListThreadsReply proto.InternalMessageInfo

func (m *ListThreadsReply) GetList() []*GetThreadReply {
	if m != nil {
		return m.List
	}
	return nil
}

type GetThreadRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetThreadRequest) Reset()         { *m = GetThreadRequest{} }
func (m *GetThreadRequest) String() string { return proto.CompactTextString(m) }
func (*GetThreadRequest) ProtoMessage()    {}
func (*GetThreadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{2}
}

func (m *GetThreadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThreadRequest.Unmarshal(m, b)
}
func (m *GetThreadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThreadRequest.Marshal(b, m, deterministic)
}
func (m *GetThreadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThreadRequest.Merge(m, src)
}
func (m *GetThreadRequest) XXX_Size() int {
	return xxx_messageInfo_GetThreadRequest.Size(m)
}
func (m *GetThreadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThreadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetThreadRequest proto.InternalMessageInfo

func (m *GetThreadRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetThreadReply struct {
	ID                   []byte   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetThreadReply) Reset()         { *m = GetThreadReply{} }
func (m *GetThreadReply) String() string { return proto.CompactTextString(m) }
func (*GetThreadReply) ProtoMessage()    {}
func (*GetThreadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{3}
}

func (m *GetThreadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThreadReply.Unmarshal(m, b)
}
func (m *GetThreadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThreadReply.Marshal(b, m, deterministic)
}
func (m *GetThreadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThreadReply.Merge(m, src)
}
func (m *GetThreadReply) XXX_Size() int {
	return xxx_messageInfo_GetThreadReply.Size(m)
}
func (m *GetThreadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThreadReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetThreadReply proto.InternalMessageInfo

func (m *GetThreadReply) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *GetThreadReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ListThreadsRequest)(nil), "users.pb.ListThreadsRequest")
	proto.RegisterType((*ListThreadsReply)(nil), "users.pb.ListThreadsReply")
	proto.RegisterType((*GetThreadRequest)(nil), "users.pb.GetThreadRequest")
	proto.RegisterType((*GetThreadReply)(nil), "users.pb.GetThreadReply")
}

func init() { proto.RegisterFile("users.proto", fileDescriptor_030765f334c86cea) }

var fileDescriptor_030765f334c86cea = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2d, 0x4e, 0x2d,
	0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x72, 0x92, 0x94, 0x44, 0xb8, 0x84,
	0x7c, 0x32, 0x8b, 0x4b, 0x42, 0x32, 0x8a, 0x52, 0x13, 0x53, 0x8a, 0x83, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x94, 0x1c, 0xb8, 0x04, 0x50, 0x44, 0x0b, 0x72, 0x2a, 0x85, 0x74, 0xb8, 0x58, 0x72,
	0x32, 0x8b, 0x4b, 0x24, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x24, 0xf4, 0x60, 0x46, 0xe8, 0xb9,
	0xa7, 0x42, 0x15, 0x82, 0xd5, 0x05, 0x81, 0x55, 0x29, 0xa9, 0x71, 0x09, 0x20, 0x89, 0x83, 0x4d,
	0x15, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02,
	0xb3, 0x95, 0x4c, 0xb8, 0xf8, 0x50, 0xf5, 0x0b, 0xf1, 0x71, 0x31, 0x79, 0xba, 0x80, 0xd5, 0xf0,
	0x04, 0x31, 0x79, 0xba, 0xc0, 0x75, 0x31, 0x21, 0x74, 0x19, 0x4d, 0x65, 0xe4, 0x62, 0x76, 0x0c,
	0xf0, 0x14, 0x72, 0xe6, 0xe2, 0x84, 0xeb, 0x16, 0x92, 0xc2, 0xea, 0x24, 0xb0, 0xd5, 0x52, 0x38,
	0x9d, 0xab, 0xc4, 0x20, 0xe4, 0xc9, 0xc5, 0x8d, 0xe4, 0x59, 0x21, 0x19, 0x84, 0x52, 0xcc, 0x90,
	0x91, 0x92, 0xc2, 0x21, 0x0b, 0x36, 0xca, 0xc9, 0x84, 0x4b, 0x34, 0x33, 0x5f, 0xaf, 0x24, 0xb5,
	0xa2, 0x24, 0x33, 0x27, 0x15, 0xa2, 0x32, 0x3e, 0xbd, 0xa8, 0x20, 0xd9, 0x89, 0x27, 0x04, 0x22,
	0x16, 0x0a, 0x12, 0x0a, 0x60, 0x5c, 0xc4, 0xc4, 0x15, 0x12, 0x11, 0xe2, 0x13, 0x1f, 0x1a, 0xec,
	0x1a, 0x14, 0x9c, 0xc4, 0x06, 0x8e, 0x14, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xb1,
	0x8a, 0xee, 0xa3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	GetThread(ctx context.Context, in *GetThreadRequest, opts ...grpc.CallOption) (*GetThreadReply, error)
	ListThreads(ctx context.Context, in *ListThreadsRequest, opts ...grpc.CallOption) (*ListThreadsReply, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetThread(ctx context.Context, in *GetThreadRequest, opts ...grpc.CallOption) (*GetThreadReply, error) {
	out := new(GetThreadReply)
	err := c.cc.Invoke(ctx, "/users.pb.API/GetThread", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListThreads(ctx context.Context, in *ListThreadsRequest, opts ...grpc.CallOption) (*ListThreadsReply, error) {
	out := new(ListThreadsReply)
	err := c.cc.Invoke(ctx, "/users.pb.API/ListThreads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	GetThread(context.Context, *GetThreadRequest) (*GetThreadReply, error)
	ListThreads(context.Context, *ListThreadsRequest) (*ListThreadsReply, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) GetThread(ctx context.Context, req *GetThreadRequest) (*GetThreadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThread not implemented")
}
func (*UnimplementedAPIServer) ListThreads(ctx context.Context, req *ListThreadsRequest) (*ListThreadsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListThreads not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_GetThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.pb.API/GetThread",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetThread(ctx, req.(*GetThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListThreads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListThreadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListThreads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.pb.API/ListThreads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListThreads(ctx, req.(*ListThreadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "users.pb.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetThread",
			Handler:    _API_GetThread_Handler,
		},
		{
			MethodName: "ListThreads",
			Handler:    _API_ListThreads_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}
