// Code generated by protoc-gen-go. DO NOT EDIT.
// source: buckets.proto

package bucketspb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Root struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	CreatedAt            int64    `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Root) Reset()         { *m = Root{} }
func (m *Root) String() string { return proto.CompactTextString(m) }
func (*Root) ProtoMessage()    {}
func (*Root) Descriptor() ([]byte, []int) {
	return fileDescriptor_95035767e889ecda, []int{0}
}

func (m *Root) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Root.Unmarshal(m, b)
}
func (m *Root) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Root.Marshal(b, m, deterministic)
}
func (m *Root) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Root.Merge(m, src)
}
func (m *Root) XXX_Size() int {
	return xxx_messageInfo_Root.Size(m)
}
func (m *Root) XXX_DiscardUnknown() {
	xxx_messageInfo_Root.DiscardUnknown(m)
}

var xxx_messageInfo_Root proto.InternalMessageInfo

func (m *Root) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Root) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Root) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Root) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type ListPathRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPathRequest) Reset()         { *m = ListPathRequest{} }
func (m *ListPathRequest) String() string { return proto.CompactTextString(m) }
func (*ListPathRequest) ProtoMessage()    {}
func (*ListPathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95035767e889ecda, []int{1}
}

func (m *ListPathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPathRequest.Unmarshal(m, b)
}
func (m *ListPathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPathRequest.Marshal(b, m, deterministic)
}
func (m *ListPathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPathRequest.Merge(m, src)
}
func (m *ListPathRequest) XXX_Size() int {
	return xxx_messageInfo_ListPathRequest.Size(m)
}
func (m *ListPathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPathRequest proto.InternalMessageInfo

func (m *ListPathRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ListPathReply struct {
	Item                 *ListPathReply_Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Root                 *Root               `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListPathReply) Reset()         { *m = ListPathReply{} }
func (m *ListPathReply) String() string { return proto.CompactTextString(m) }
func (*ListPathReply) ProtoMessage()    {}
func (*ListPathReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_95035767e889ecda, []int{2}
}

func (m *ListPathReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPathReply.Unmarshal(m, b)
}
func (m *ListPathReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPathReply.Marshal(b, m, deterministic)
}
func (m *ListPathReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPathReply.Merge(m, src)
}
func (m *ListPathReply) XXX_Size() int {
	return xxx_messageInfo_ListPathReply.Size(m)
}
func (m *ListPathReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPathReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListPathReply proto.InternalMessageInfo

func (m *ListPathReply) GetItem() *ListPathReply_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ListPathReply) GetRoot() *Root {
	if m != nil {
		return m.Root
	}
	return nil
}

type ListPathReply_Item struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string                `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size                 int64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	IsDir                bool                  `protobuf:"varint,4,opt,name=isDir,proto3" json:"isDir,omitempty"`
	Items                []*ListPathReply_Item `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListPathReply_Item) Reset()         { *m = ListPathReply_Item{} }
func (m *ListPathReply_Item) String() string { return proto.CompactTextString(m) }
func (*ListPathReply_Item) ProtoMessage()    {}
func (*ListPathReply_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_95035767e889ecda, []int{2, 0}
}

func (m *ListPathReply_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPathReply_Item.Unmarshal(m, b)
}
func (m *ListPathReply_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPathReply_Item.Marshal(b, m, deterministic)
}
func (m *ListPathReply_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPathReply_Item.Merge(m, src)
}
func (m *ListPathReply_Item) XXX_Size() int {
	return xxx_messageInfo_ListPathReply_Item.Size(m)
}
func (m *ListPathReply_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPathReply_Item.DiscardUnknown(m)
}

var xxx_messageInfo_ListPathReply_Item proto.InternalMessageInfo

func (m *ListPathReply_Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListPathReply_Item) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ListPathReply_Item) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListPathReply_Item) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *ListPathReply_Item) GetItems() []*ListPathReply_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type PushPathRequest struct {
	// Types that are valid to be assigned to Payload:
	//	*PushPathRequest_Header_
	//	*PushPathRequest_Chunk
	Payload              isPushPathRequest_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PushPathRequest) Reset()         { *m = PushPathRequest{} }
func (m *PushPathRequest) String() string { return proto.CompactTextString(m) }
func (*PushPathRequest) ProtoMessage()    {}
func (*PushPathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95035767e889ecda, []int{3}
}

func (m *PushPathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPathRequest.Unmarshal(m, b)
}
func (m *PushPathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPathRequest.Marshal(b, m, deterministic)
}
func (m *PushPathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPathRequest.Merge(m, src)
}
func (m *PushPathRequest) XXX_Size() int {
	return xxx_messageInfo_PushPathRequest.Size(m)
}
func (m *PushPathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushPathRequest proto.InternalMessageInfo

type isPushPathRequest_Payload interface {
	isPushPathRequest_Payload()
}

type PushPathRequest_Header_ struct {
	Header *PushPathRequest_Header `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type PushPathRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*PushPathRequest_Header_) isPushPathRequest_Payload() {}

func (*PushPathRequest_Chunk) isPushPathRequest_Payload() {}

func (m *PushPathRequest) GetPayload() isPushPathRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *PushPathRequest) GetHeader() *PushPathRequest_Header {
	if x, ok := m.GetPayload().(*PushPathRequest_Header_); ok {
		return x.Header
	}
	return nil
}

func (m *PushPathRequest) GetChunk() []byte {
	if x, ok := m.GetPayload().(*PushPathRequest_Chunk); ok {
		return x.Chunk
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PushPathRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PushPathRequest_Header_)(nil),
		(*PushPathRequest_Chunk)(nil),
	}
}

type PushPathRequest_Header struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushPathRequest_Header) Reset()         { *m = PushPathRequest_Header{} }
func (m *PushPathRequest_Header) String() string { return proto.CompactTextString(m) }
func (*PushPathRequest_Header) ProtoMessage()    {}
func (*PushPathRequest_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_95035767e889ecda, []int{3, 0}
}

func (m *PushPathRequest_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPathRequest_Header.Unmarshal(m, b)
}
func (m *PushPathRequest_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPathRequest_Header.Marshal(b, m, deterministic)
}
func (m *PushPathRequest_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPathRequest_Header.Merge(m, src)
}
func (m *PushPathRequest_Header) XXX_Size() int {
	return xxx_messageInfo_PushPathRequest_Header.Size(m)
}
func (m *PushPathRequest_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPathRequest_Header.DiscardUnknown(m)
}

var xxx_messageInfo_PushPathRequest_Header proto.InternalMessageInfo

func (m *PushPathRequest_Header) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type PushPathReply struct {
	// Types that are valid to be assigned to Payload:
	//	*PushPathReply_Event_
	//	*PushPathReply_Error
	Payload              isPushPathReply_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PushPathReply) Reset()         { *m = PushPathReply{} }
func (m *PushPathReply) String() string { return proto.CompactTextString(m) }
func (*PushPathReply) ProtoMessage()    {}
func (*PushPathReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_95035767e889ecda, []int{4}
}

func (m *PushPathReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPathReply.Unmarshal(m, b)
}
func (m *PushPathReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPathReply.Marshal(b, m, deterministic)
}
func (m *PushPathReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPathReply.Merge(m, src)
}
func (m *PushPathReply) XXX_Size() int {
	return xxx_messageInfo_PushPathReply.Size(m)
}
func (m *PushPathReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPathReply.DiscardUnknown(m)
}

var xxx_messageInfo_PushPathReply proto.InternalMessageInfo

type isPushPathReply_Payload interface {
	isPushPathReply_Payload()
}

type PushPathReply_Event_ struct {
	Event *PushPathReply_Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type PushPathReply_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*PushPathReply_Event_) isPushPathReply_Payload() {}

func (*PushPathReply_Error) isPushPathReply_Payload() {}

func (m *PushPathReply) GetPayload() isPushPathReply_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *PushPathReply) GetEvent() *PushPathReply_Event {
	if x, ok := m.GetPayload().(*PushPathReply_Event_); ok {
		return x.Event
	}
	return nil
}

func (m *PushPathReply) GetError() string {
	if x, ok := m.GetPayload().(*PushPathReply_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PushPathReply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PushPathReply_Event_)(nil),
		(*PushPathReply_Error)(nil),
	}
}

type PushPathReply_Event struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Bytes                int64    `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Size                 string   `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Root                 *Root    `protobuf:"bytes,5,opt,name=root,proto3" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushPathReply_Event) Reset()         { *m = PushPathReply_Event{} }
func (m *PushPathReply_Event) String() string { return proto.CompactTextString(m) }
func (*PushPathReply_Event) ProtoMessage()    {}
func (*PushPathReply_Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_95035767e889ecda, []int{4, 0}
}

func (m *PushPathReply_Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPathReply_Event.Unmarshal(m, b)
}
func (m *PushPathReply_Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPathReply_Event.Marshal(b, m, deterministic)
}
func (m *PushPathReply_Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPathReply_Event.Merge(m, src)
}
func (m *PushPathReply_Event) XXX_Size() int {
	return xxx_messageInfo_PushPathReply_Event.Size(m)
}
func (m *PushPathReply_Event) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPathReply_Event.DiscardUnknown(m)
}

var xxx_messageInfo_PushPathReply_Event proto.InternalMessageInfo

func (m *PushPathReply_Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PushPathReply_Event) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *PushPathReply_Event) GetBytes() int64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *PushPathReply_Event) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *PushPathReply_Event) GetRoot() *Root {
	if m != nil {
		return m.Root
	}
	return nil
}

type PullPathRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullPathRequest) Reset()         { *m = PullPathRequest{} }
func (m *PullPathRequest) String() string { return proto.CompactTextString(m) }
func (*PullPathRequest) ProtoMessage()    {}
func (*PullPathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95035767e889ecda, []int{5}
}

func (m *PullPathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullPathRequest.Unmarshal(m, b)
}
func (m *PullPathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullPathRequest.Marshal(b, m, deterministic)
}
func (m *PullPathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullPathRequest.Merge(m, src)
}
func (m *PullPathRequest) XXX_Size() int {
	return xxx_messageInfo_PullPathRequest.Size(m)
}
func (m *PullPathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullPathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullPathRequest proto.InternalMessageInfo

func (m *PullPathRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type PullPathReply struct {
	Chunk                []byte   `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullPathReply) Reset()         { *m = PullPathReply{} }
func (m *PullPathReply) String() string { return proto.CompactTextString(m) }
func (*PullPathReply) ProtoMessage()    {}
func (*PullPathReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_95035767e889ecda, []int{6}
}

func (m *PullPathReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullPathReply.Unmarshal(m, b)
}
func (m *PullPathReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullPathReply.Marshal(b, m, deterministic)
}
func (m *PullPathReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullPathReply.Merge(m, src)
}
func (m *PullPathReply) XXX_Size() int {
	return xxx_messageInfo_PullPathReply.Size(m)
}
func (m *PullPathReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PullPathReply.DiscardUnknown(m)
}

var xxx_messageInfo_PullPathReply proto.InternalMessageInfo

func (m *PullPathReply) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

type RemovePathRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePathRequest) Reset()         { *m = RemovePathRequest{} }
func (m *RemovePathRequest) String() string { return proto.CompactTextString(m) }
func (*RemovePathRequest) ProtoMessage()    {}
func (*RemovePathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95035767e889ecda, []int{7}
}

func (m *RemovePathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePathRequest.Unmarshal(m, b)
}
func (m *RemovePathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePathRequest.Marshal(b, m, deterministic)
}
func (m *RemovePathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePathRequest.Merge(m, src)
}
func (m *RemovePathRequest) XXX_Size() int {
	return xxx_messageInfo_RemovePathRequest.Size(m)
}
func (m *RemovePathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePathRequest proto.InternalMessageInfo

func (m *RemovePathRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type RemovePathReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePathReply) Reset()         { *m = RemovePathReply{} }
func (m *RemovePathReply) String() string { return proto.CompactTextString(m) }
func (*RemovePathReply) ProtoMessage()    {}
func (*RemovePathReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_95035767e889ecda, []int{8}
}

func (m *RemovePathReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePathReply.Unmarshal(m, b)
}
func (m *RemovePathReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePathReply.Marshal(b, m, deterministic)
}
func (m *RemovePathReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePathReply.Merge(m, src)
}
func (m *RemovePathReply) XXX_Size() int {
	return xxx_messageInfo_RemovePathReply.Size(m)
}
func (m *RemovePathReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePathReply.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePathReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Root)(nil), "bucketspb.Root")
	proto.RegisterType((*ListPathRequest)(nil), "bucketspb.ListPathRequest")
	proto.RegisterType((*ListPathReply)(nil), "bucketspb.ListPathReply")
	proto.RegisterType((*ListPathReply_Item)(nil), "bucketspb.ListPathReply.Item")
	proto.RegisterType((*PushPathRequest)(nil), "bucketspb.PushPathRequest")
	proto.RegisterType((*PushPathRequest_Header)(nil), "bucketspb.PushPathRequest.Header")
	proto.RegisterType((*PushPathReply)(nil), "bucketspb.PushPathReply")
	proto.RegisterType((*PushPathReply_Event)(nil), "bucketspb.PushPathReply.Event")
	proto.RegisterType((*PullPathRequest)(nil), "bucketspb.PullPathRequest")
	proto.RegisterType((*PullPathReply)(nil), "bucketspb.PullPathReply")
	proto.RegisterType((*RemovePathRequest)(nil), "bucketspb.RemovePathRequest")
	proto.RegisterType((*RemovePathReply)(nil), "bucketspb.RemovePathReply")
}

func init() { proto.RegisterFile("buckets.proto", fileDescriptor_95035767e889ecda) }

var fileDescriptor_95035767e889ecda = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xcd, 0x24, 0x76, 0xbe, 0xe4, 0x36, 0xf9, 0xa2, 0x8e, 0x22, 0xb0, 0xac, 0x80, 0x82, 0x51,
	0x44, 0x56, 0x56, 0x49, 0x25, 0x16, 0xb0, 0xaa, 0x69, 0x51, 0x2a, 0xba, 0x88, 0x86, 0x20, 0xb1,
	0xab, 0x9c, 0x64, 0x84, 0x4d, 0x9d, 0x8c, 0xb1, 0xc7, 0x15, 0x61, 0xc1, 0x1b, 0x20, 0x9e, 0x01,
	0x1e, 0x8f, 0x17, 0x60, 0x8b, 0x66, 0xc6, 0x8e, 0x7f, 0x94, 0x92, 0xee, 0x3c, 0xf7, 0x9e, 0x39,
	0x73, 0xcf, 0x39, 0x57, 0x86, 0xee, 0x22, 0x59, 0xde, 0x50, 0x1e, 0xdb, 0x61, 0xc4, 0x38, 0xc3,
	0xed, 0xf4, 0x18, 0x2e, 0xac, 0x4f, 0xa0, 0x11, 0xc6, 0x38, 0xc6, 0xa0, 0x6d, 0xdc, 0x35, 0x35,
	0xd0, 0x10, 0x8d, 0xdb, 0x44, 0x7e, 0x8b, 0x5a, 0xe8, 0x72, 0xcf, 0xa8, 0xab, 0x9a, 0xf8, 0xc6,
	0x03, 0x68, 0x2f, 0x23, 0xea, 0x72, 0xba, 0x3a, 0xe3, 0x46, 0x63, 0x88, 0xc6, 0x0d, 0x92, 0x17,
	0x44, 0x37, 0x09, 0x57, 0x69, 0x57, 0x53, 0xdd, 0x5d, 0xc1, 0x1a, 0x41, 0xef, 0xca, 0x8f, 0xf9,
	0xcc, 0xe5, 0x1e, 0xa1, 0x9f, 0x13, 0x1a, 0xf3, 0xdd, 0x13, 0x28, 0x7f, 0xc2, 0xfa, 0x83, 0xa0,
	0x9b, 0xe3, 0xc2, 0x60, 0x8b, 0x9f, 0x83, 0xe6, 0x73, 0xba, 0x96, 0xa8, 0xa3, 0xc9, 0x23, 0x7b,
	0x37, 0xbe, 0x5d, 0xc2, 0xd9, 0x97, 0x9c, 0xae, 0x89, 0x84, 0xe2, 0xa7, 0xa0, 0x45, 0x8c, 0x71,
	0x39, 0xfb, 0xd1, 0xa4, 0x57, 0xb8, 0x22, 0xe4, 0x12, 0xd9, 0x34, 0xbf, 0x23, 0xd0, 0xc4, 0x9d,
	0x7b, 0xab, 0xc7, 0xa0, 0xc5, 0xfe, 0x57, 0x9a, 0x0a, 0x97, 0xdf, 0xb8, 0x0f, 0xba, 0x1f, 0x9f,
	0xfb, 0x91, 0xd4, 0xdb, 0x22, 0xea, 0x80, 0x4f, 0x41, 0x17, 0x73, 0xc4, 0x86, 0x3e, 0x6c, 0x1c,
	0x9e, 0x59, 0x61, 0xad, 0x1f, 0x08, 0x7a, 0xb3, 0x24, 0xf6, 0x8a, 0x0e, 0xbd, 0x82, 0xa6, 0x47,
	0xdd, 0x15, 0x8d, 0x52, 0xf5, 0x4f, 0x0a, 0x4c, 0x15, 0xac, 0x3d, 0x95, 0xc0, 0x69, 0x8d, 0xa4,
	0x57, 0xf0, 0x03, 0xd0, 0x97, 0x5e, 0xb2, 0xb9, 0x91, 0x22, 0x3a, 0xd3, 0x1a, 0x51, 0x47, 0x73,
	0x00, 0x4d, 0x85, 0xdd, 0x17, 0x80, 0xd3, 0x86, 0xff, 0x42, 0x77, 0x1b, 0x30, 0x77, 0x65, 0xfd,
	0x46, 0xd0, 0xcd, 0x5f, 0x11, 0x59, 0xbc, 0x00, 0x9d, 0xde, 0xd2, 0x0d, 0x4f, 0xc7, 0x79, 0xbc,
	0x77, 0x1c, 0x21, 0xec, 0x42, 0xa0, 0xc4, 0x93, 0x12, 0x2e, 0x46, 0xa1, 0x51, 0xc4, 0x22, 0xe5,
	0xa7, 0xac, 0x8b, 0xa3, 0xf9, 0x0d, 0x74, 0x89, 0xbc, 0x77, 0x06, 0x7d, 0xd0, 0x17, 0x5b, 0x4e,
	0xe3, 0x34, 0x04, 0x75, 0xd8, 0x25, 0xa3, 0x29, 0xa4, 0x4c, 0x26, 0xdb, 0x01, 0xfd, 0x1f, 0x3b,
	0x50, 0x14, 0x3b, 0x12, 0xee, 0x07, 0xc1, 0xa1, 0xfd, 0x1c, 0x09, 0x4b, 0x32, 0x98, 0xb0, 0xa4,
	0x9f, 0xb9, 0x2c, 0x50, 0x9d, 0xd4, 0x63, 0xeb, 0x19, 0x1c, 0x13, 0xba, 0x66, 0xb7, 0xf4, 0x10,
	0xdf, 0x31, 0xf4, 0x8a, 0xc0, 0x30, 0xd8, 0x4e, 0x7e, 0xd6, 0xa1, 0x71, 0x36, 0xbb, 0xc4, 0x0e,
	0xb4, 0xb2, 0x6d, 0xc1, 0xe6, 0xde, 0x15, 0x92, 0xb4, 0xa6, 0x71, 0xd7, 0x7a, 0x59, 0x35, 0xfc,
	0x06, 0x5a, 0x59, 0x30, 0x25, 0x8e, 0xca, 0xf2, 0x94, 0x38, 0x4a, 0x49, 0x5a, 0xb5, 0x31, 0x3a,
	0x41, 0xf8, 0x5c, 0xf0, 0x28, 0xd9, 0x15, 0x9e, 0x92, 0x65, 0x15, 0x9e, 0x82, 0x4f, 0x56, 0xed,
	0x04, 0xe1, 0x29, 0x40, 0x2e, 0x16, 0x0f, 0x8a, 0x99, 0x54, 0xcd, 0x32, 0xcd, 0x3b, 0xba, 0x92,
	0xcb, 0x79, 0x09, 0x0f, 0x7d, 0x66, 0x73, 0xfa, 0x85, 0xfb, 0x01, 0xcd, 0x90, 0xd7, 0x1f, 0xa3,
	0x70, 0xe9, 0xfc, 0x3f, 0x57, 0x55, 0x47, 0x15, 0x67, 0xe8, 0x57, 0xbd, 0x33, 0xff, 0x30, 0xbf,
	0xba, 0x76, 0xde, 0xbf, 0x7e, 0x7b, 0x31, 0x7f, 0xb7, 0x68, 0xca, 0xff, 0xe0, 0xe9, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x1c, 0xbe, 0x91, 0x22, 0x18, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	ListPath(ctx context.Context, in *ListPathRequest, opts ...grpc.CallOption) (*ListPathReply, error)
	PushPath(ctx context.Context, opts ...grpc.CallOption) (API_PushPathClient, error)
	PullPath(ctx context.Context, in *PullPathRequest, opts ...grpc.CallOption) (API_PullPathClient, error)
	RemovePath(ctx context.Context, in *RemovePathRequest, opts ...grpc.CallOption) (*RemovePathReply, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) ListPath(ctx context.Context, in *ListPathRequest, opts ...grpc.CallOption) (*ListPathReply, error) {
	out := new(ListPathReply)
	err := c.cc.Invoke(ctx, "/bucketspb.API/ListPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) PushPath(ctx context.Context, opts ...grpc.CallOption) (API_PushPathClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[0], "/bucketspb.API/PushPath", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIPushPathClient{stream}
	return x, nil
}

type API_PushPathClient interface {
	Send(*PushPathRequest) error
	Recv() (*PushPathReply, error)
	grpc.ClientStream
}

type aPIPushPathClient struct {
	grpc.ClientStream
}

func (x *aPIPushPathClient) Send(m *PushPathRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPIPushPathClient) Recv() (*PushPathReply, error) {
	m := new(PushPathReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) PullPath(ctx context.Context, in *PullPathRequest, opts ...grpc.CallOption) (API_PullPathClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[1], "/bucketspb.API/PullPath", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIPullPathClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_PullPathClient interface {
	Recv() (*PullPathReply, error)
	grpc.ClientStream
}

type aPIPullPathClient struct {
	grpc.ClientStream
}

func (x *aPIPullPathClient) Recv() (*PullPathReply, error) {
	m := new(PullPathReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) RemovePath(ctx context.Context, in *RemovePathRequest, opts ...grpc.CallOption) (*RemovePathReply, error) {
	out := new(RemovePathReply)
	err := c.cc.Invoke(ctx, "/bucketspb.API/RemovePath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	ListPath(context.Context, *ListPathRequest) (*ListPathReply, error)
	PushPath(API_PushPathServer) error
	PullPath(*PullPathRequest, API_PullPathServer) error
	RemovePath(context.Context, *RemovePathRequest) (*RemovePathReply, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) ListPath(ctx context.Context, req *ListPathRequest) (*ListPathReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPath not implemented")
}
func (*UnimplementedAPIServer) PushPath(srv API_PushPathServer) error {
	return status.Errorf(codes.Unimplemented, "method PushPath not implemented")
}
func (*UnimplementedAPIServer) PullPath(req *PullPathRequest, srv API_PullPathServer) error {
	return status.Errorf(codes.Unimplemented, "method PullPath not implemented")
}
func (*UnimplementedAPIServer) RemovePath(ctx context.Context, req *RemovePathRequest) (*RemovePathReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePath not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_ListPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bucketspb.API/ListPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListPath(ctx, req.(*ListPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_PushPath_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).PushPath(&aPIPushPathServer{stream})
}

type API_PushPathServer interface {
	Send(*PushPathReply) error
	Recv() (*PushPathRequest, error)
	grpc.ServerStream
}

type aPIPushPathServer struct {
	grpc.ServerStream
}

func (x *aPIPushPathServer) Send(m *PushPathReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPIPushPathServer) Recv() (*PushPathRequest, error) {
	m := new(PushPathRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _API_PullPath_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullPathRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).PullPath(m, &aPIPullPathServer{stream})
}

type API_PullPathServer interface {
	Send(*PullPathReply) error
	grpc.ServerStream
}

type aPIPullPathServer struct {
	grpc.ServerStream
}

func (x *aPIPullPathServer) Send(m *PullPathReply) error {
	return x.ServerStream.SendMsg(m)
}

func _API_RemovePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).RemovePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bucketspb.API/RemovePath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).RemovePath(ctx, req.(*RemovePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bucketspb.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPath",
			Handler:    _API_ListPath_Handler,
		},
		{
			MethodName: "RemovePath",
			Handler:    _API_RemovePath_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushPath",
			Handler:       _API_PushPath_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PullPath",
			Handler:       _API_PullPath_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "buckets.proto",
}
