FROM golang:1.16.0-buster

RUN apt-get update && apt-get install -y \
  libssl-dev \
  ca-certificates

RUN go get github.com/go-delve/delve/cmd/dlv

ENV SRC_DIR /textile

COPY go.mod go.sum $SRC_DIR/
RUN cd $SRC_DIR \
  && go mod download

COPY . $SRC_DIR

RUN cd $SRC_DIR \
  && CGO_ENABLED=0 GOOS=linux go build -gcflags "all=-N -l" -o mindexd api/mindexd/main.go

FROM debian:buster
LABEL maintainer="Textile <contact@textile.io>"

ENV SRC_DIR /textile
COPY --from=0 /go/bin/dlv /usr/local/bin/dlv
COPY --from=0 /etc/ssl/certs /etc/ssl/certs
COPY --from=0 $SRC_DIR/mindexd /usr/local/bin/mindexd

EXPOSE 5000
EXPOSE 8081
EXPOSE 40000

ENV MINDEXD_PATH /data/mindexd
RUN adduser --home $MINDEXD_PATH --disabled-login --gecos "" --ingroup users mindexd

USER mindexd

ENTRYPOINT ["dlv", "--listen=0.0.0.0:40000", "--headless=true", "--accept-multiclient", "--continue", "--api-version=2", "exec", "/usr/local/bin/mindexd"]
