version: "3"
services:
  ipfs:
    image: ipfs/go-ipfs:v0.7.0
    environment:
      - IPFS_PROFILE=test
    ports:
      - "127.0.0.1:5011:5001"
  mongo:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    command:
      - /bin/bash
      - -c
      - |
        /usr/bin/mongod --fork --logpath /var/log/mongod.log --bind_ip_all --replSet rs0
        mongo --eval 'rs.initiate({_id: "rs0", version: 1, members: [{ _id: 0, host: "127.0.0.1:27017" }]})'
        tail -f /var/log/mongod.log