// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub.proto

package hub_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignupRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupRequest) Reset()         { *m = SignupRequest{} }
func (m *SignupRequest) String() string { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()    {}
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{0}
}

func (m *SignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequest.Unmarshal(m, b)
}
func (m *SignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequest.Marshal(b, m, deterministic)
}
func (m *SignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequest.Merge(m, src)
}
func (m *SignupRequest) XXX_Size() int {
	return xxx_messageInfo_SignupRequest.Size(m)
}
func (m *SignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequest proto.InternalMessageInfo

func (m *SignupRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SignupReply struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Session              string   `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupReply) Reset()         { *m = SignupReply{} }
func (m *SignupReply) String() string { return proto.CompactTextString(m) }
func (*SignupReply) ProtoMessage()    {}
func (*SignupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{1}
}

func (m *SignupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupReply.Unmarshal(m, b)
}
func (m *SignupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupReply.Marshal(b, m, deterministic)
}
func (m *SignupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupReply.Merge(m, src)
}
func (m *SignupReply) XXX_Size() int {
	return xxx_messageInfo_SignupReply.Size(m)
}
func (m *SignupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupReply.DiscardUnknown(m)
}

var xxx_messageInfo_SignupReply proto.InternalMessageInfo

func (m *SignupReply) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SignupReply) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

type SigninRequest struct {
	UsernameOrEmail      string   `protobuf:"bytes,1,opt,name=usernameOrEmail,proto3" json:"usernameOrEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigninRequest) Reset()         { *m = SigninRequest{} }
func (m *SigninRequest) String() string { return proto.CompactTextString(m) }
func (*SigninRequest) ProtoMessage()    {}
func (*SigninRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{2}
}

func (m *SigninRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigninRequest.Unmarshal(m, b)
}
func (m *SigninRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigninRequest.Marshal(b, m, deterministic)
}
func (m *SigninRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigninRequest.Merge(m, src)
}
func (m *SigninRequest) XXX_Size() int {
	return xxx_messageInfo_SigninRequest.Size(m)
}
func (m *SigninRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SigninRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SigninRequest proto.InternalMessageInfo

func (m *SigninRequest) GetUsernameOrEmail() string {
	if m != nil {
		return m.UsernameOrEmail
	}
	return ""
}

type SigninReply struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Session              string   `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigninReply) Reset()         { *m = SigninReply{} }
func (m *SigninReply) String() string { return proto.CompactTextString(m) }
func (*SigninReply) ProtoMessage()    {}
func (*SigninReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{3}
}

func (m *SigninReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigninReply.Unmarshal(m, b)
}
func (m *SigninReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigninReply.Marshal(b, m, deterministic)
}
func (m *SigninReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigninReply.Merge(m, src)
}
func (m *SigninReply) XXX_Size() int {
	return xxx_messageInfo_SigninReply.Size(m)
}
func (m *SigninReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SigninReply.DiscardUnknown(m)
}

var xxx_messageInfo_SigninReply proto.InternalMessageInfo

func (m *SigninReply) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SigninReply) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

type SignoutRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignoutRequest) Reset()         { *m = SignoutRequest{} }
func (m *SignoutRequest) String() string { return proto.CompactTextString(m) }
func (*SignoutRequest) ProtoMessage()    {}
func (*SignoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{4}
}

func (m *SignoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignoutRequest.Unmarshal(m, b)
}
func (m *SignoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignoutRequest.Marshal(b, m, deterministic)
}
func (m *SignoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignoutRequest.Merge(m, src)
}
func (m *SignoutRequest) XXX_Size() int {
	return xxx_messageInfo_SignoutRequest.Size(m)
}
func (m *SignoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignoutRequest proto.InternalMessageInfo

type SignoutReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignoutReply) Reset()         { *m = SignoutReply{} }
func (m *SignoutReply) String() string { return proto.CompactTextString(m) }
func (*SignoutReply) ProtoMessage()    {}
func (*SignoutReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{5}
}

func (m *SignoutReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignoutReply.Unmarshal(m, b)
}
func (m *SignoutReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignoutReply.Marshal(b, m, deterministic)
}
func (m *SignoutReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignoutReply.Merge(m, src)
}
func (m *SignoutReply) XXX_Size() int {
	return xxx_messageInfo_SignoutReply.Size(m)
}
func (m *SignoutReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SignoutReply.DiscardUnknown(m)
}

var xxx_messageInfo_SignoutReply proto.InternalMessageInfo

type CheckUsernameRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUsernameRequest) Reset()         { *m = CheckUsernameRequest{} }
func (m *CheckUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*CheckUsernameRequest) ProtoMessage()    {}
func (*CheckUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{6}
}

func (m *CheckUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUsernameRequest.Unmarshal(m, b)
}
func (m *CheckUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUsernameRequest.Marshal(b, m, deterministic)
}
func (m *CheckUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUsernameRequest.Merge(m, src)
}
func (m *CheckUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_CheckUsernameRequest.Size(m)
}
func (m *CheckUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUsernameRequest proto.InternalMessageInfo

func (m *CheckUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CheckUsernameReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUsernameReply) Reset()         { *m = CheckUsernameReply{} }
func (m *CheckUsernameReply) String() string { return proto.CompactTextString(m) }
func (*CheckUsernameReply) ProtoMessage()    {}
func (*CheckUsernameReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{7}
}

func (m *CheckUsernameReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUsernameReply.Unmarshal(m, b)
}
func (m *CheckUsernameReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUsernameReply.Marshal(b, m, deterministic)
}
func (m *CheckUsernameReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUsernameReply.Merge(m, src)
}
func (m *CheckUsernameReply) XXX_Size() int {
	return xxx_messageInfo_CheckUsernameReply.Size(m)
}
func (m *CheckUsernameReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUsernameReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUsernameReply proto.InternalMessageInfo

func (m *CheckUsernameReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type GetSessionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionRequest) Reset()         { *m = GetSessionRequest{} }
func (m *GetSessionRequest) String() string { return proto.CompactTextString(m) }
func (*GetSessionRequest) ProtoMessage()    {}
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{8}
}

func (m *GetSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionRequest.Unmarshal(m, b)
}
func (m *GetSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionRequest.Marshal(b, m, deterministic)
}
func (m *GetSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionRequest.Merge(m, src)
}
func (m *GetSessionRequest) XXX_Size() int {
	return xxx_messageInfo_GetSessionRequest.Size(m)
}
func (m *GetSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionRequest proto.InternalMessageInfo

type GetSessionReply struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionReply) Reset()         { *m = GetSessionReply{} }
func (m *GetSessionReply) String() string { return proto.CompactTextString(m) }
func (*GetSessionReply) ProtoMessage()    {}
func (*GetSessionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{9}
}

func (m *GetSessionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionReply.Unmarshal(m, b)
}
func (m *GetSessionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionReply.Marshal(b, m, deterministic)
}
func (m *GetSessionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionReply.Merge(m, src)
}
func (m *GetSessionReply) XXX_Size() int {
	return xxx_messageInfo_GetSessionReply.Size(m)
}
func (m *GetSessionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionReply proto.InternalMessageInfo

func (m *GetSessionReply) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetSessionReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetSessionReply) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetThreadRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetThreadRequest) Reset()         { *m = GetThreadRequest{} }
func (m *GetThreadRequest) String() string { return proto.CompactTextString(m) }
func (*GetThreadRequest) ProtoMessage()    {}
func (*GetThreadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{10}
}

func (m *GetThreadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThreadRequest.Unmarshal(m, b)
}
func (m *GetThreadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThreadRequest.Marshal(b, m, deterministic)
}
func (m *GetThreadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThreadRequest.Merge(m, src)
}
func (m *GetThreadRequest) XXX_Size() int {
	return xxx_messageInfo_GetThreadRequest.Size(m)
}
func (m *GetThreadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThreadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetThreadRequest proto.InternalMessageInfo

func (m *GetThreadRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetThreadReply struct {
	ID                   []byte   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetThreadReply) Reset()         { *m = GetThreadReply{} }
func (m *GetThreadReply) String() string { return proto.CompactTextString(m) }
func (*GetThreadReply) ProtoMessage()    {}
func (*GetThreadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{11}
}

func (m *GetThreadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetThreadReply.Unmarshal(m, b)
}
func (m *GetThreadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetThreadReply.Marshal(b, m, deterministic)
}
func (m *GetThreadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetThreadReply.Merge(m, src)
}
func (m *GetThreadReply) XXX_Size() int {
	return xxx_messageInfo_GetThreadReply.Size(m)
}
func (m *GetThreadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetThreadReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetThreadReply proto.InternalMessageInfo

func (m *GetThreadReply) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *GetThreadReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListThreadsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListThreadsRequest) Reset()         { *m = ListThreadsRequest{} }
func (m *ListThreadsRequest) String() string { return proto.CompactTextString(m) }
func (*ListThreadsRequest) ProtoMessage()    {}
func (*ListThreadsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{12}
}

func (m *ListThreadsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListThreadsRequest.Unmarshal(m, b)
}
func (m *ListThreadsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListThreadsRequest.Marshal(b, m, deterministic)
}
func (m *ListThreadsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListThreadsRequest.Merge(m, src)
}
func (m *ListThreadsRequest) XXX_Size() int {
	return xxx_messageInfo_ListThreadsRequest.Size(m)
}
func (m *ListThreadsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListThreadsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListThreadsRequest proto.InternalMessageInfo

type ListThreadsReply struct {
	List                 []*GetThreadReply `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListThreadsReply) Reset()         { *m = ListThreadsReply{} }
func (m *ListThreadsReply) String() string { return proto.CompactTextString(m) }
func (*ListThreadsReply) ProtoMessage()    {}
func (*ListThreadsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{13}
}

func (m *ListThreadsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListThreadsReply.Unmarshal(m, b)
}
func (m *ListThreadsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListThreadsReply.Marshal(b, m, deterministic)
}
func (m *ListThreadsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListThreadsReply.Merge(m, src)
}
func (m *ListThreadsReply) XXX_Size() int {
	return xxx_messageInfo_ListThreadsReply.Size(m)
}
func (m *ListThreadsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListThreadsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListThreadsReply proto.InternalMessageInfo

func (m *ListThreadsReply) GetList() []*GetThreadReply {
	if m != nil {
		return m.List
	}
	return nil
}

type CreateKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateKeyRequest) Reset()         { *m = CreateKeyRequest{} }
func (m *CreateKeyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateKeyRequest) ProtoMessage()    {}
func (*CreateKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{14}
}

func (m *CreateKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateKeyRequest.Unmarshal(m, b)
}
func (m *CreateKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateKeyRequest.Marshal(b, m, deterministic)
}
func (m *CreateKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateKeyRequest.Merge(m, src)
}
func (m *CreateKeyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateKeyRequest.Size(m)
}
func (m *CreateKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateKeyRequest proto.InternalMessageInfo

type GetKeyReply struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Valid                bool     `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	Threads              int32    `protobuf:"varint,4,opt,name=threads,proto3" json:"threads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeyReply) Reset()         { *m = GetKeyReply{} }
func (m *GetKeyReply) String() string { return proto.CompactTextString(m) }
func (*GetKeyReply) ProtoMessage()    {}
func (*GetKeyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{15}
}

func (m *GetKeyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeyReply.Unmarshal(m, b)
}
func (m *GetKeyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeyReply.Marshal(b, m, deterministic)
}
func (m *GetKeyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeyReply.Merge(m, src)
}
func (m *GetKeyReply) XXX_Size() int {
	return xxx_messageInfo_GetKeyReply.Size(m)
}
func (m *GetKeyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeyReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeyReply proto.InternalMessageInfo

func (m *GetKeyReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetKeyReply) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *GetKeyReply) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *GetKeyReply) GetThreads() int32 {
	if m != nil {
		return m.Threads
	}
	return 0
}

type InvalidateKeyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvalidateKeyRequest) Reset()         { *m = InvalidateKeyRequest{} }
func (m *InvalidateKeyRequest) String() string { return proto.CompactTextString(m) }
func (*InvalidateKeyRequest) ProtoMessage()    {}
func (*InvalidateKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{16}
}

func (m *InvalidateKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidateKeyRequest.Unmarshal(m, b)
}
func (m *InvalidateKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidateKeyRequest.Marshal(b, m, deterministic)
}
func (m *InvalidateKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidateKeyRequest.Merge(m, src)
}
func (m *InvalidateKeyRequest) XXX_Size() int {
	return xxx_messageInfo_InvalidateKeyRequest.Size(m)
}
func (m *InvalidateKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidateKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidateKeyRequest proto.InternalMessageInfo

func (m *InvalidateKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type InvalidateKeyReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvalidateKeyReply) Reset()         { *m = InvalidateKeyReply{} }
func (m *InvalidateKeyReply) String() string { return proto.CompactTextString(m) }
func (*InvalidateKeyReply) ProtoMessage()    {}
func (*InvalidateKeyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{17}
}

func (m *InvalidateKeyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidateKeyReply.Unmarshal(m, b)
}
func (m *InvalidateKeyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidateKeyReply.Marshal(b, m, deterministic)
}
func (m *InvalidateKeyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidateKeyReply.Merge(m, src)
}
func (m *InvalidateKeyReply) XXX_Size() int {
	return xxx_messageInfo_InvalidateKeyReply.Size(m)
}
func (m *InvalidateKeyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidateKeyReply.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidateKeyReply proto.InternalMessageInfo

type ListKeysRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListKeysRequest) Reset()         { *m = ListKeysRequest{} }
func (m *ListKeysRequest) String() string { return proto.CompactTextString(m) }
func (*ListKeysRequest) ProtoMessage()    {}
func (*ListKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{18}
}

func (m *ListKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListKeysRequest.Unmarshal(m, b)
}
func (m *ListKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListKeysRequest.Marshal(b, m, deterministic)
}
func (m *ListKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListKeysRequest.Merge(m, src)
}
func (m *ListKeysRequest) XXX_Size() int {
	return xxx_messageInfo_ListKeysRequest.Size(m)
}
func (m *ListKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListKeysRequest proto.InternalMessageInfo

type ListKeysReply struct {
	List                 []*GetKeyReply `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListKeysReply) Reset()         { *m = ListKeysReply{} }
func (m *ListKeysReply) String() string { return proto.CompactTextString(m) }
func (*ListKeysReply) ProtoMessage()    {}
func (*ListKeysReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{19}
}

func (m *ListKeysReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListKeysReply.Unmarshal(m, b)
}
func (m *ListKeysReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListKeysReply.Marshal(b, m, deterministic)
}
func (m *ListKeysReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListKeysReply.Merge(m, src)
}
func (m *ListKeysReply) XXX_Size() int {
	return xxx_messageInfo_ListKeysReply.Size(m)
}
func (m *ListKeysReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListKeysReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListKeysReply proto.InternalMessageInfo

func (m *ListKeysReply) GetList() []*GetKeyReply {
	if m != nil {
		return m.List
	}
	return nil
}

type CreateOrgRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrgRequest) Reset()         { *m = CreateOrgRequest{} }
func (m *CreateOrgRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrgRequest) ProtoMessage()    {}
func (*CreateOrgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{20}
}

func (m *CreateOrgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrgRequest.Unmarshal(m, b)
}
func (m *CreateOrgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrgRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrgRequest.Merge(m, src)
}
func (m *CreateOrgRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrgRequest.Size(m)
}
func (m *CreateOrgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrgRequest proto.InternalMessageInfo

func (m *CreateOrgRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetOrgRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrgRequest) Reset()         { *m = GetOrgRequest{} }
func (m *GetOrgRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrgRequest) ProtoMessage()    {}
func (*GetOrgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{21}
}

func (m *GetOrgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrgRequest.Unmarshal(m, b)
}
func (m *GetOrgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrgRequest.Marshal(b, m, deterministic)
}
func (m *GetOrgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrgRequest.Merge(m, src)
}
func (m *GetOrgRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrgRequest.Size(m)
}
func (m *GetOrgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrgRequest proto.InternalMessageInfo

type GetOrgReply struct {
	Key                  []byte                `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Members              []*GetOrgReply_Member `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	CreatedAt            int64                 `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetOrgReply) Reset()         { *m = GetOrgReply{} }
func (m *GetOrgReply) String() string { return proto.CompactTextString(m) }
func (*GetOrgReply) ProtoMessage()    {}
func (*GetOrgReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{22}
}

func (m *GetOrgReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrgReply.Unmarshal(m, b)
}
func (m *GetOrgReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrgReply.Marshal(b, m, deterministic)
}
func (m *GetOrgReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrgReply.Merge(m, src)
}
func (m *GetOrgReply) XXX_Size() int {
	return xxx_messageInfo_GetOrgReply.Size(m)
}
func (m *GetOrgReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrgReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrgReply proto.InternalMessageInfo

func (m *GetOrgReply) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetOrgReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetOrgReply) GetMembers() []*GetOrgReply_Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *GetOrgReply) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type GetOrgReply_Member struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrgReply_Member) Reset()         { *m = GetOrgReply_Member{} }
func (m *GetOrgReply_Member) String() string { return proto.CompactTextString(m) }
func (*GetOrgReply_Member) ProtoMessage()    {}
func (*GetOrgReply_Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{22, 0}
}

func (m *GetOrgReply_Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrgReply_Member.Unmarshal(m, b)
}
func (m *GetOrgReply_Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrgReply_Member.Marshal(b, m, deterministic)
}
func (m *GetOrgReply_Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrgReply_Member.Merge(m, src)
}
func (m *GetOrgReply_Member) XXX_Size() int {
	return xxx_messageInfo_GetOrgReply_Member.Size(m)
}
func (m *GetOrgReply_Member) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrgReply_Member.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrgReply_Member proto.InternalMessageInfo

func (m *GetOrgReply_Member) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetOrgReply_Member) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetOrgReply_Member) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type ListOrgsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrgsRequest) Reset()         { *m = ListOrgsRequest{} }
func (m *ListOrgsRequest) String() string { return proto.CompactTextString(m) }
func (*ListOrgsRequest) ProtoMessage()    {}
func (*ListOrgsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{23}
}

func (m *ListOrgsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrgsRequest.Unmarshal(m, b)
}
func (m *ListOrgsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrgsRequest.Marshal(b, m, deterministic)
}
func (m *ListOrgsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrgsRequest.Merge(m, src)
}
func (m *ListOrgsRequest) XXX_Size() int {
	return xxx_messageInfo_ListOrgsRequest.Size(m)
}
func (m *ListOrgsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrgsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrgsRequest proto.InternalMessageInfo

type ListOrgsReply struct {
	List                 []*GetOrgReply `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListOrgsReply) Reset()         { *m = ListOrgsReply{} }
func (m *ListOrgsReply) String() string { return proto.CompactTextString(m) }
func (*ListOrgsReply) ProtoMessage()    {}
func (*ListOrgsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{24}
}

func (m *ListOrgsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrgsReply.Unmarshal(m, b)
}
func (m *ListOrgsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrgsReply.Marshal(b, m, deterministic)
}
func (m *ListOrgsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrgsReply.Merge(m, src)
}
func (m *ListOrgsReply) XXX_Size() int {
	return xxx_messageInfo_ListOrgsReply.Size(m)
}
func (m *ListOrgsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrgsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrgsReply proto.InternalMessageInfo

func (m *ListOrgsReply) GetList() []*GetOrgReply {
	if m != nil {
		return m.List
	}
	return nil
}

type RemoveOrgRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveOrgRequest) Reset()         { *m = RemoveOrgRequest{} }
func (m *RemoveOrgRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveOrgRequest) ProtoMessage()    {}
func (*RemoveOrgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{25}
}

func (m *RemoveOrgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOrgRequest.Unmarshal(m, b)
}
func (m *RemoveOrgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOrgRequest.Marshal(b, m, deterministic)
}
func (m *RemoveOrgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOrgRequest.Merge(m, src)
}
func (m *RemoveOrgRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveOrgRequest.Size(m)
}
func (m *RemoveOrgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOrgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOrgRequest proto.InternalMessageInfo

type RemoveOrgReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveOrgReply) Reset()         { *m = RemoveOrgReply{} }
func (m *RemoveOrgReply) String() string { return proto.CompactTextString(m) }
func (*RemoveOrgReply) ProtoMessage()    {}
func (*RemoveOrgReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{26}
}

func (m *RemoveOrgReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveOrgReply.Unmarshal(m, b)
}
func (m *RemoveOrgReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveOrgReply.Marshal(b, m, deterministic)
}
func (m *RemoveOrgReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveOrgReply.Merge(m, src)
}
func (m *RemoveOrgReply) XXX_Size() int {
	return xxx_messageInfo_RemoveOrgReply.Size(m)
}
func (m *RemoveOrgReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveOrgReply.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveOrgReply proto.InternalMessageInfo

type InviteToOrgRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteToOrgRequest) Reset()         { *m = InviteToOrgRequest{} }
func (m *InviteToOrgRequest) String() string { return proto.CompactTextString(m) }
func (*InviteToOrgRequest) ProtoMessage()    {}
func (*InviteToOrgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{27}
}

func (m *InviteToOrgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteToOrgRequest.Unmarshal(m, b)
}
func (m *InviteToOrgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteToOrgRequest.Marshal(b, m, deterministic)
}
func (m *InviteToOrgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteToOrgRequest.Merge(m, src)
}
func (m *InviteToOrgRequest) XXX_Size() int {
	return xxx_messageInfo_InviteToOrgRequest.Size(m)
}
func (m *InviteToOrgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteToOrgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteToOrgRequest proto.InternalMessageInfo

func (m *InviteToOrgRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type InviteToOrgReply struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteToOrgReply) Reset()         { *m = InviteToOrgReply{} }
func (m *InviteToOrgReply) String() string { return proto.CompactTextString(m) }
func (*InviteToOrgReply) ProtoMessage()    {}
func (*InviteToOrgReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{28}
}

func (m *InviteToOrgReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteToOrgReply.Unmarshal(m, b)
}
func (m *InviteToOrgReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteToOrgReply.Marshal(b, m, deterministic)
}
func (m *InviteToOrgReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteToOrgReply.Merge(m, src)
}
func (m *InviteToOrgReply) XXX_Size() int {
	return xxx_messageInfo_InviteToOrgReply.Size(m)
}
func (m *InviteToOrgReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteToOrgReply.DiscardUnknown(m)
}

var xxx_messageInfo_InviteToOrgReply proto.InternalMessageInfo

func (m *InviteToOrgReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LeaveOrgRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveOrgRequest) Reset()         { *m = LeaveOrgRequest{} }
func (m *LeaveOrgRequest) String() string { return proto.CompactTextString(m) }
func (*LeaveOrgRequest) ProtoMessage()    {}
func (*LeaveOrgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{29}
}

func (m *LeaveOrgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveOrgRequest.Unmarshal(m, b)
}
func (m *LeaveOrgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveOrgRequest.Marshal(b, m, deterministic)
}
func (m *LeaveOrgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveOrgRequest.Merge(m, src)
}
func (m *LeaveOrgRequest) XXX_Size() int {
	return xxx_messageInfo_LeaveOrgRequest.Size(m)
}
func (m *LeaveOrgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveOrgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveOrgRequest proto.InternalMessageInfo

type LeaveOrgReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveOrgReply) Reset()         { *m = LeaveOrgReply{} }
func (m *LeaveOrgReply) String() string { return proto.CompactTextString(m) }
func (*LeaveOrgReply) ProtoMessage()    {}
func (*LeaveOrgReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{30}
}

func (m *LeaveOrgReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveOrgReply.Unmarshal(m, b)
}
func (m *LeaveOrgReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveOrgReply.Marshal(b, m, deterministic)
}
func (m *LeaveOrgReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveOrgReply.Merge(m, src)
}
func (m *LeaveOrgReply) XXX_Size() int {
	return xxx_messageInfo_LeaveOrgReply.Size(m)
}
func (m *LeaveOrgReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveOrgReply.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveOrgReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SignupRequest)(nil), "hub.pb.SignupRequest")
	proto.RegisterType((*SignupReply)(nil), "hub.pb.SignupReply")
	proto.RegisterType((*SigninRequest)(nil), "hub.pb.SigninRequest")
	proto.RegisterType((*SigninReply)(nil), "hub.pb.SigninReply")
	proto.RegisterType((*SignoutRequest)(nil), "hub.pb.SignoutRequest")
	proto.RegisterType((*SignoutReply)(nil), "hub.pb.SignoutReply")
	proto.RegisterType((*CheckUsernameRequest)(nil), "hub.pb.CheckUsernameRequest")
	proto.RegisterType((*CheckUsernameReply)(nil), "hub.pb.CheckUsernameReply")
	proto.RegisterType((*GetSessionRequest)(nil), "hub.pb.GetSessionRequest")
	proto.RegisterType((*GetSessionReply)(nil), "hub.pb.GetSessionReply")
	proto.RegisterType((*GetThreadRequest)(nil), "hub.pb.GetThreadRequest")
	proto.RegisterType((*GetThreadReply)(nil), "hub.pb.GetThreadReply")
	proto.RegisterType((*ListThreadsRequest)(nil), "hub.pb.ListThreadsRequest")
	proto.RegisterType((*ListThreadsReply)(nil), "hub.pb.ListThreadsReply")
	proto.RegisterType((*CreateKeyRequest)(nil), "hub.pb.CreateKeyRequest")
	proto.RegisterType((*GetKeyReply)(nil), "hub.pb.GetKeyReply")
	proto.RegisterType((*InvalidateKeyRequest)(nil), "hub.pb.InvalidateKeyRequest")
	proto.RegisterType((*InvalidateKeyReply)(nil), "hub.pb.InvalidateKeyReply")
	proto.RegisterType((*ListKeysRequest)(nil), "hub.pb.ListKeysRequest")
	proto.RegisterType((*ListKeysReply)(nil), "hub.pb.ListKeysReply")
	proto.RegisterType((*CreateOrgRequest)(nil), "hub.pb.CreateOrgRequest")
	proto.RegisterType((*GetOrgRequest)(nil), "hub.pb.GetOrgRequest")
	proto.RegisterType((*GetOrgReply)(nil), "hub.pb.GetOrgReply")
	proto.RegisterType((*GetOrgReply_Member)(nil), "hub.pb.GetOrgReply.Member")
	proto.RegisterType((*ListOrgsRequest)(nil), "hub.pb.ListOrgsRequest")
	proto.RegisterType((*ListOrgsReply)(nil), "hub.pb.ListOrgsReply")
	proto.RegisterType((*RemoveOrgRequest)(nil), "hub.pb.RemoveOrgRequest")
	proto.RegisterType((*RemoveOrgReply)(nil), "hub.pb.RemoveOrgReply")
	proto.RegisterType((*InviteToOrgRequest)(nil), "hub.pb.InviteToOrgRequest")
	proto.RegisterType((*InviteToOrgReply)(nil), "hub.pb.InviteToOrgReply")
	proto.RegisterType((*LeaveOrgRequest)(nil), "hub.pb.LeaveOrgRequest")
	proto.RegisterType((*LeaveOrgReply)(nil), "hub.pb.LeaveOrgReply")
}

func init() { proto.RegisterFile("hub.proto", fileDescriptor_b3103f8d3056b01c) }

var fileDescriptor_b3103f8d3056b01c = []byte{
	// 856 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdb, 0x4e, 0xeb, 0x46,
	0x14, 0xcd, 0x8d, 0x90, 0xec, 0x90, 0x0b, 0x93, 0x00, 0xae, 0xc5, 0x03, 0xb2, 0x2a, 0x1a, 0xf1,
	0x90, 0x07, 0x8a, 0xaa, 0x22, 0x55, 0xad, 0x08, 0xa0, 0x90, 0x42, 0x15, 0x64, 0x82, 0xd4, 0x37,
	0x94, 0x84, 0x51, 0xb0, 0xe2, 0xc4, 0xa9, 0x3d, 0x41, 0xcd, 0x3f, 0x9c, 0xaf, 0x38, 0xbf, 0x74,
	0x7e, 0xe8, 0x68, 0x6e, 0x9e, 0x19, 0xc7, 0x41, 0x87, 0x37, 0xcf, 0x9e, 0x7d, 0x59, 0x7b, 0xed,
	0x3d, 0x4b, 0x86, 0xf2, 0xdb, 0x6a, 0xdc, 0x59, 0x86, 0x01, 0x09, 0x50, 0x91, 0x7d, 0x8e, 0x9d,
	0x2b, 0xa8, 0x3e, 0x79, 0xd3, 0xc5, 0x6a, 0xe9, 0xe2, 0xff, 0x56, 0x38, 0x22, 0xc8, 0x86, 0xd2,
	0x2a, 0xc2, 0xe1, 0x62, 0x34, 0xc7, 0x56, 0xf6, 0x24, 0xdb, 0x2e, 0xbb, 0xf1, 0x19, 0xb5, 0x60,
	0x07, 0xcf, 0x47, 0x9e, 0x6f, 0xe5, 0xd8, 0x05, 0x3f, 0x38, 0x97, 0x50, 0x91, 0x29, 0x96, 0xfe,
	0x1a, 0x35, 0x20, 0x3f, 0xc3, 0x6b, 0x16, 0xbb, 0xe7, 0xd2, 0x4f, 0x64, 0xc1, 0x6e, 0x84, 0xa3,
	0xc8, 0x0b, 0x16, 0x22, 0x50, 0x1e, 0x9d, 0x4b, 0x5e, 0xdd, 0x5b, 0xc8, 0xea, 0x6d, 0xa8, 0xcb,
	0x6a, 0x83, 0xf0, 0x96, 0xd5, 0xe2, 0x20, 0x92, 0x66, 0x59, 0x95, 0x86, 0x7e, 0xb6, 0x6a, 0x03,
	0x6a, 0x34, 0x34, 0x58, 0x11, 0x51, 0xd6, 0xa9, 0xc1, 0x5e, 0x6c, 0x59, 0xfa, 0x6b, 0xe7, 0x1c,
	0x5a, 0xd7, 0x6f, 0x78, 0x32, 0x7b, 0x16, 0x45, 0x7f, 0x80, 0x1c, 0xe7, 0x67, 0x40, 0x89, 0x18,
	0x8a, 0xab, 0x06, 0xb9, 0x60, 0xc6, 0x7c, 0x4b, 0x6e, 0x2e, 0x98, 0x39, 0x4d, 0xd8, 0xef, 0x61,
	0xf2, 0xc4, 0x91, 0xc8, 0xf2, 0xcf, 0x50, 0xd7, 0x8d, 0xe9, 0xfd, 0xe8, 0xb5, 0x73, 0xdb, 0x06,
	0x93, 0xd7, 0x07, 0x73, 0x0a, 0x8d, 0x1e, 0x26, 0xc3, 0xb7, 0x10, 0x8f, 0x5e, 0x65, 0x07, 0x08,
	0x0a, 0x1a, 0x7a, 0xf6, 0xed, 0x5c, 0x40, 0x4d, 0xf3, 0x13, 0xa8, 0xfb, 0x37, 0xa2, 0x78, 0xae,
	0x7f, 0x13, 0x47, 0xe5, 0xb4, 0xa8, 0x16, 0xa0, 0x07, 0x2f, 0x12, 0x61, 0x91, 0x6c, 0xe5, 0x4f,
	0x68, 0x18, 0x56, 0x9a, 0xed, 0x0c, 0x0a, 0xbe, 0x17, 0x11, 0x2b, 0x7b, 0x92, 0x6f, 0x57, 0xce,
	0x0f, 0x3b, 0x7c, 0xf5, 0x3a, 0x66, 0x4d, 0x97, 0xf9, 0x38, 0x08, 0x1a, 0xd7, 0x21, 0x1e, 0x11,
	0x7c, 0x8f, 0xd7, 0x32, 0xe7, 0x14, 0x2a, 0x3d, 0x4c, 0x98, 0x21, 0x41, 0x4d, 0x99, 0x53, 0x73,
	0x08, 0xc5, 0x08, 0x4f, 0x42, 0x4c, 0x04, 0x40, 0x71, 0xa2, 0xb4, 0xbc, 0x8f, 0x7c, 0xef, 0x95,
	0xd1, 0x52, 0x72, 0xf9, 0x81, 0x2e, 0x06, 0xe1, 0xf0, 0xac, 0xc2, 0x49, 0xb6, 0xbd, 0xe3, 0xca,
	0xa3, 0xd3, 0x86, 0x56, 0x7f, 0xc1, 0x9c, 0x0c, 0x00, 0x9b, 0x15, 0x69, 0xf3, 0x09, 0x4f, 0xba,
	0x36, 0xfb, 0x50, 0xa7, 0xcd, 0xdf, 0xe3, 0x75, 0xcc, 0xc7, 0xef, 0x50, 0x55, 0x26, 0x8a, 0xfe,
	0x17, 0x83, 0x8c, 0xa6, 0x46, 0x86, 0x4c, 0x23, 0x98, 0x38, 0x95, 0x4c, 0x0c, 0xc2, 0xe9, 0x47,
	0xd3, 0xab, 0x43, 0xb5, 0x87, 0x89, 0x72, 0x72, 0xbe, 0x65, 0x19, 0x5f, 0xcc, 0x92, 0xbe, 0x4a,
	0x29, 0xe3, 0x44, 0x17, 0xb0, 0x3b, 0xc7, 0xf3, 0x31, 0x0e, 0x23, 0x2b, 0xcf, 0xa0, 0xd9, 0x1a,
	0x34, 0x99, 0xab, 0xf3, 0x0f, 0x73, 0x71, 0xa5, 0x2b, 0x3a, 0x86, 0xf2, 0x84, 0x81, 0x7c, 0xbd,
	0x22, 0x8c, 0xcd, 0xbc, 0xab, 0x0c, 0xf6, 0xdf, 0x50, 0xe4, 0x01, 0x9f, 0x5c, 0x67, 0x04, 0x85,
	0x30, 0xf0, 0xb1, 0xd8, 0x66, 0xf6, 0x2d, 0xb9, 0x1d, 0x84, 0xd3, 0x24, 0xb7, 0xdc, 0xf4, 0x31,
	0xb7, 0xb2, 0x01, 0xb5, 0x65, 0x2e, 0x9e, 0x07, 0xef, 0x1a, 0xb7, 0x54, 0x15, 0x34, 0x1b, 0x1d,
	0xe7, 0x19, 0x1b, 0xb2, 0x47, 0xf0, 0x30, 0xd0, 0x66, 0x10, 0xbf, 0xb5, 0xac, 0xfe, 0xd6, 0xda,
	0xd0, 0x30, 0x7c, 0x29, 0x9c, 0x16, 0xec, 0x90, 0x60, 0x86, 0x17, 0xd2, 0x93, 0x1d, 0x58, 0x23,
	0x78, 0x64, 0x94, 0xae, 0x43, 0x55, 0x99, 0x96, 0xfe, 0xfa, 0xfc, 0x4b, 0x09, 0xf2, 0x57, 0x8f,
	0x7d, 0xf4, 0x1b, 0x14, 0xb9, 0xb4, 0xa2, 0x03, 0xd9, 0x8c, 0xa1, 0xd6, 0x76, 0x33, 0x69, 0xa6,
	0xb8, 0x33, 0x32, 0xce, 0x5b, 0x98, 0x71, 0xb1, 0xce, 0x9a, 0x71, 0x42, 0x43, 0x9d, 0x0c, 0xba,
	0x84, 0x5d, 0xa1, 0x83, 0xe8, 0x50, 0xf7, 0x50, 0x52, 0x69, 0xb7, 0x36, 0xec, 0x3c, 0xf4, 0x1e,
	0xaa, 0x86, 0xfc, 0xa1, 0x63, 0xe9, 0x98, 0xa6, 0xa4, 0xb6, 0xbd, 0xe5, 0x96, 0x27, 0xeb, 0x02,
	0x28, 0x41, 0x44, 0x3f, 0x69, 0x83, 0x34, 0x95, 0xd3, 0x3e, 0x4a, 0xbb, 0xe2, 0x39, 0xfe, 0x82,
	0x72, 0xac, 0x30, 0xc8, 0x4a, 0x11, 0x1d, 0x9e, 0x61, 0x8b, 0x1c, 0x39, 0x19, 0x74, 0x0b, 0x15,
	0x4d, 0xca, 0x50, 0x8c, 0x78, 0x53, 0xf5, 0x6c, 0x2b, 0xf5, 0x8e, 0xa7, 0xf9, 0x03, 0xca, 0xb1,
	0xa2, 0x29, 0x1c, 0x49, 0x91, 0xb3, 0xd3, 0x94, 0x80, 0x45, 0x97, 0xa4, 0x7e, 0xa0, 0x23, 0xbd,
	0x8a, 0x26, 0x32, 0xf6, 0xc1, 0xe6, 0x45, 0x3c, 0x14, 0x43, 0xa6, 0xd4, 0x50, 0xd2, 0x74, 0x4e,
	0x0d, 0x25, 0x45, 0xdb, 0xb4, 0x46, 0x06, 0xe1, 0x34, 0xd9, 0x88, 0x5a, 0x66, 0x3b, 0xed, 0xd9,
	0xf1, 0x95, 0xe4, 0x06, 0xb5, 0x92, 0x86, 0x6c, 0x6d, 0x8b, 0x13, 0x04, 0xd0, 0x47, 0x6e, 0x12,
	0xa0, 0x29, 0x81, 0x49, 0x40, 0xac, 0x07, 0x7c, 0x09, 0xe2, 0x47, 0xad, 0x30, 0x27, 0xdf, 0xbe,
	0x5a, 0x82, 0x84, 0x02, 0xb0, 0x25, 0xd0, 0xde, 0x35, 0xd2, 0x19, 0x4a, 0x08, 0x83, 0x5a, 0x82,
	0xa4, 0x10, 0x88, 0x2e, 0xc4, 0x0b, 0xd7, 0xba, 0x30, 0x65, 0x40, 0xeb, 0x42, 0x17, 0x03, 0x27,
	0xd3, 0xed, 0x40, 0xd3, 0x0b, 0x3a, 0x04, 0xff, 0x4f, 0x3c, 0x1f, 0x53, 0xa7, 0x97, 0x69, 0xb8,
	0x9c, 0x74, 0x61, 0xc8, 0x2d, 0x77, 0xab, 0xf1, 0x63, 0xf6, 0x6b, 0xae, 0x34, 0xfc, 0x77, 0xf8,
	0xf0, 0x72, 0xf7, 0xdc, 0x1d, 0x17, 0xd9, 0x3f, 0xde, 0xaf, 0xdf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x80, 0x86, 0x4a, 0x42, 0xf0, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupReply, error)
	Signin(ctx context.Context, in *SigninRequest, opts ...grpc.CallOption) (*SigninReply, error)
	Signout(ctx context.Context, in *SignoutRequest, opts ...grpc.CallOption) (*SignoutReply, error)
	CheckUsername(ctx context.Context, in *CheckUsernameRequest, opts ...grpc.CallOption) (*CheckUsernameReply, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionReply, error)
	GetThread(ctx context.Context, in *GetThreadRequest, opts ...grpc.CallOption) (*GetThreadReply, error)
	ListThreads(ctx context.Context, in *ListThreadsRequest, opts ...grpc.CallOption) (*ListThreadsReply, error)
	CreateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*GetKeyReply, error)
	ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysReply, error)
	InvalidateKey(ctx context.Context, in *InvalidateKeyRequest, opts ...grpc.CallOption) (*InvalidateKeyReply, error)
	CreateOrg(ctx context.Context, in *CreateOrgRequest, opts ...grpc.CallOption) (*GetOrgReply, error)
	GetOrg(ctx context.Context, in *GetOrgRequest, opts ...grpc.CallOption) (*GetOrgReply, error)
	ListOrgs(ctx context.Context, in *ListOrgsRequest, opts ...grpc.CallOption) (*ListOrgsReply, error)
	RemoveOrg(ctx context.Context, in *RemoveOrgRequest, opts ...grpc.CallOption) (*RemoveOrgReply, error)
	InviteToOrg(ctx context.Context, in *InviteToOrgRequest, opts ...grpc.CallOption) (*InviteToOrgReply, error)
	LeaveOrg(ctx context.Context, in *LeaveOrgRequest, opts ...grpc.CallOption) (*LeaveOrgReply, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupReply, error) {
	out := new(SignupReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Signin(ctx context.Context, in *SigninRequest, opts ...grpc.CallOption) (*SigninReply, error) {
	out := new(SigninReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/Signin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Signout(ctx context.Context, in *SignoutRequest, opts ...grpc.CallOption) (*SignoutReply, error) {
	out := new(SignoutReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/Signout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CheckUsername(ctx context.Context, in *CheckUsernameRequest, opts ...grpc.CallOption) (*CheckUsernameReply, error) {
	out := new(CheckUsernameReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/CheckUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionReply, error) {
	out := new(GetSessionReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/GetSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetThread(ctx context.Context, in *GetThreadRequest, opts ...grpc.CallOption) (*GetThreadReply, error) {
	out := new(GetThreadReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/GetThread", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListThreads(ctx context.Context, in *ListThreadsRequest, opts ...grpc.CallOption) (*ListThreadsReply, error) {
	out := new(ListThreadsReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/ListThreads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*GetKeyReply, error) {
	out := new(GetKeyReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/CreateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysReply, error) {
	out := new(ListKeysReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/ListKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) InvalidateKey(ctx context.Context, in *InvalidateKeyRequest, opts ...grpc.CallOption) (*InvalidateKeyReply, error) {
	out := new(InvalidateKeyReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/InvalidateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateOrg(ctx context.Context, in *CreateOrgRequest, opts ...grpc.CallOption) (*GetOrgReply, error) {
	out := new(GetOrgReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/CreateOrg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetOrg(ctx context.Context, in *GetOrgRequest, opts ...grpc.CallOption) (*GetOrgReply, error) {
	out := new(GetOrgReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/GetOrg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListOrgs(ctx context.Context, in *ListOrgsRequest, opts ...grpc.CallOption) (*ListOrgsReply, error) {
	out := new(ListOrgsReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/ListOrgs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) RemoveOrg(ctx context.Context, in *RemoveOrgRequest, opts ...grpc.CallOption) (*RemoveOrgReply, error) {
	out := new(RemoveOrgReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/RemoveOrg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) InviteToOrg(ctx context.Context, in *InviteToOrgRequest, opts ...grpc.CallOption) (*InviteToOrgReply, error) {
	out := new(InviteToOrgReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/InviteToOrg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) LeaveOrg(ctx context.Context, in *LeaveOrgRequest, opts ...grpc.CallOption) (*LeaveOrgReply, error) {
	out := new(LeaveOrgReply)
	err := c.cc.Invoke(ctx, "/hub.pb.API/LeaveOrg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	Signup(context.Context, *SignupRequest) (*SignupReply, error)
	Signin(context.Context, *SigninRequest) (*SigninReply, error)
	Signout(context.Context, *SignoutRequest) (*SignoutReply, error)
	CheckUsername(context.Context, *CheckUsernameRequest) (*CheckUsernameReply, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionReply, error)
	GetThread(context.Context, *GetThreadRequest) (*GetThreadReply, error)
	ListThreads(context.Context, *ListThreadsRequest) (*ListThreadsReply, error)
	CreateKey(context.Context, *CreateKeyRequest) (*GetKeyReply, error)
	ListKeys(context.Context, *ListKeysRequest) (*ListKeysReply, error)
	InvalidateKey(context.Context, *InvalidateKeyRequest) (*InvalidateKeyReply, error)
	CreateOrg(context.Context, *CreateOrgRequest) (*GetOrgReply, error)
	GetOrg(context.Context, *GetOrgRequest) (*GetOrgReply, error)
	ListOrgs(context.Context, *ListOrgsRequest) (*ListOrgsReply, error)
	RemoveOrg(context.Context, *RemoveOrgRequest) (*RemoveOrgReply, error)
	InviteToOrg(context.Context, *InviteToOrgRequest) (*InviteToOrgReply, error)
	LeaveOrg(context.Context, *LeaveOrgRequest) (*LeaveOrgReply, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) Signup(ctx context.Context, req *SignupRequest) (*SignupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedAPIServer) Signin(ctx context.Context, req *SigninRequest) (*SigninReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signin not implemented")
}
func (*UnimplementedAPIServer) Signout(ctx context.Context, req *SignoutRequest) (*SignoutReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signout not implemented")
}
func (*UnimplementedAPIServer) CheckUsername(ctx context.Context, req *CheckUsernameRequest) (*CheckUsernameReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUsername not implemented")
}
func (*UnimplementedAPIServer) GetSession(ctx context.Context, req *GetSessionRequest) (*GetSessionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (*UnimplementedAPIServer) GetThread(ctx context.Context, req *GetThreadRequest) (*GetThreadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThread not implemented")
}
func (*UnimplementedAPIServer) ListThreads(ctx context.Context, req *ListThreadsRequest) (*ListThreadsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListThreads not implemented")
}
func (*UnimplementedAPIServer) CreateKey(ctx context.Context, req *CreateKeyRequest) (*GetKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKey not implemented")
}
func (*UnimplementedAPIServer) ListKeys(ctx context.Context, req *ListKeysRequest) (*ListKeysReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKeys not implemented")
}
func (*UnimplementedAPIServer) InvalidateKey(ctx context.Context, req *InvalidateKeyRequest) (*InvalidateKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvalidateKey not implemented")
}
func (*UnimplementedAPIServer) CreateOrg(ctx context.Context, req *CreateOrgRequest) (*GetOrgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrg not implemented")
}
func (*UnimplementedAPIServer) GetOrg(ctx context.Context, req *GetOrgRequest) (*GetOrgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrg not implemented")
}
func (*UnimplementedAPIServer) ListOrgs(ctx context.Context, req *ListOrgsRequest) (*ListOrgsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrgs not implemented")
}
func (*UnimplementedAPIServer) RemoveOrg(ctx context.Context, req *RemoveOrgRequest) (*RemoveOrgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveOrg not implemented")
}
func (*UnimplementedAPIServer) InviteToOrg(ctx context.Context, req *InviteToOrgRequest) (*InviteToOrgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteToOrg not implemented")
}
func (*UnimplementedAPIServer) LeaveOrg(ctx context.Context, req *LeaveOrgRequest) (*LeaveOrgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveOrg not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Signin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SigninRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Signin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/Signin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Signin(ctx, req.(*SigninRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Signout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Signout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/Signout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Signout(ctx, req.(*SignoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CheckUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CheckUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/CheckUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CheckUsername(ctx, req.(*CheckUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/GetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/GetThread",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetThread(ctx, req.(*GetThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListThreads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListThreadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListThreads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/ListThreads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListThreads(ctx, req.(*ListThreadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/CreateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateKey(ctx, req.(*CreateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/ListKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListKeys(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_InvalidateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).InvalidateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/InvalidateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).InvalidateKey(ctx, req.(*InvalidateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/CreateOrg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateOrg(ctx, req.(*CreateOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/GetOrg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetOrg(ctx, req.(*GetOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListOrgs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrgsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListOrgs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/ListOrgs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListOrgs(ctx, req.(*ListOrgsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_RemoveOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).RemoveOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/RemoveOrg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).RemoveOrg(ctx, req.(*RemoveOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_InviteToOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteToOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).InviteToOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/InviteToOrg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).InviteToOrg(ctx, req.(*InviteToOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_LeaveOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).LeaveOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hub.pb.API/LeaveOrg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).LeaveOrg(ctx, req.(*LeaveOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hub.pb.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _API_Signup_Handler,
		},
		{
			MethodName: "Signin",
			Handler:    _API_Signin_Handler,
		},
		{
			MethodName: "Signout",
			Handler:    _API_Signout_Handler,
		},
		{
			MethodName: "CheckUsername",
			Handler:    _API_CheckUsername_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _API_GetSession_Handler,
		},
		{
			MethodName: "GetThread",
			Handler:    _API_GetThread_Handler,
		},
		{
			MethodName: "ListThreads",
			Handler:    _API_ListThreads_Handler,
		},
		{
			MethodName: "CreateKey",
			Handler:    _API_CreateKey_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _API_ListKeys_Handler,
		},
		{
			MethodName: "InvalidateKey",
			Handler:    _API_InvalidateKey_Handler,
		},
		{
			MethodName: "CreateOrg",
			Handler:    _API_CreateOrg_Handler,
		},
		{
			MethodName: "GetOrg",
			Handler:    _API_GetOrg_Handler,
		},
		{
			MethodName: "ListOrgs",
			Handler:    _API_ListOrgs_Handler,
		},
		{
			MethodName: "RemoveOrg",
			Handler:    _API_RemoveOrg_Handler,
		},
		{
			MethodName: "InviteToOrg",
			Handler:    _API_InviteToOrg_Handler,
		},
		{
			MethodName: "LeaveOrg",
			Handler:    _API_LeaveOrg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub.proto",
}
