version: "3"
services:
#  billing:
#    build:
#      context: ../../
#      dockerfile: ./api/billingd/Dockerfile
#    environment:
#      - BILLING_ADDR_API=/ip4/0.0.0.0/tcp/10006
#      - BILLING_ADDR_MONGO_URI=mongodb://127.0.0.1:27017/?replicaSet=rs0
#      - BILLING_STRIPE_KEY
#      - BILLING_STRIPE_STORED_DATA_PRICE
#      - BILLING_STRIPE_NETWORK_EGRESS_PRICE
#      - BILLING_STRIPE_INSTANCE_READS_PRICE
#      - BILLING_STRIPE_INSTANCE_WRITES_PRICE
#      - BILLING_LOG_DEBUG=true
#    ports:
#      - "127.0.0.1:10006:10006"
  stripe:
    container_name: stripe
    image: adrienverge/localstripe:latest
    expose:
      - "8420"
    ports:
      - "8420:8420"
    restart: always
  mongo:
    hostname: mongodb
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_REPLICA_SET_NAME: rs0
    expose:
      - "27017"
    ports:
      - "27017:27017"
    restart: always
    command:
      - /bin/bash
      - -c
      - |
        /usr/bin/mongod --fork --logpath /var/log/mongod.log --bind_ip_all --replSet rs0
        mongo --eval 'rs.initiate({_id: "rs0", version: 1, members: [{ _id: 0, host: "127.0.0.1:27017" }]})'
        tail -f /var/log/mongod.log