FROM golang:1.16.0-buster

RUN apt-get update && apt-get install -y \
  libssl-dev \
  ca-certificates

RUN go get github.com/go-delve/delve/cmd/dlv

ENV SRC_DIR /textile

COPY go.mod go.sum $SRC_DIR/
RUN cd $SRC_DIR \
  && go mod download

COPY . $SRC_DIR

RUN cd $SRC_DIR \
  && CGO_ENABLED=0 GOOS=linux go build -gcflags "all=-N -l" -o billingd api/billingd/main.go

FROM debian:buster
LABEL maintainer="Textile <contact@textile.io>"

ENV SRC_DIR /textile
COPY --from=0 /go/bin/dlv /usr/local/bin/dlv
COPY --from=0 /etc/ssl/certs /etc/ssl/certs
COPY --from=0 $SRC_DIR/billingd /usr/local/bin/billingd

EXPOSE 10006
EXPOSE 8010
EXPOSE 40000

ENV BILLING_PATH /data/billing
RUN adduser --home $BILLING_PATH --disabled-login --gecos "" --ingroup users billing

USER billing

ENTRYPOINT ["dlv", "--listen=0.0.0.0:40000", "--headless=true", "--accept-multiclient", "--continue", "--api-version=2", "exec", "/usr/local/bin/billingd"]
