name: Buf
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Buf Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: success()
        uses: actions/checkout@v1
        with:
          ref: master
      - name: checkout-master
        if: success()
        run: git checkout master
      - name: checkout
        if: success()
        uses: actions/checkout@v1
      - name: make local
        if: success()
        run: make buf-local
