name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  buck:
    name: Buck CLI
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: success()
        uses: actions/checkout@v1
        with:
          ref: master
      - name: checkout-master
        if: success()
        run: git checkout master
      - name: checkout
        if: success()
        uses: actions/checkout@v1
      - name: build
        if: success()
        run: make build-buck
  buckd:
    name: Buck Daemon
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: success()
        uses: actions/checkout@v1
        with:
          ref: master
      - name: checkout-master
        if: success()
        run: git checkout master
      - name: checkout
        if: success()
        uses: actions/checkout@v1
      - name: build
        if: success()
        run: make build-buckd
  hub-cli:
    name: Hub CLI
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: success()
        uses: actions/checkout@v1
        with:
          ref: master
      - name: checkout-master
        if: success()
        run: git checkout master
      - name: checkout
        if: success()
        uses: actions/checkout@v1
      - name: build
        if: success()
        run: make build-hub
  hubd:
    name: Hub Daemon
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: success()
        uses: actions/checkout@v1
        with:
          ref: master
      - name: checkout-master
        if: success()
        run: git checkout master
      - name: checkout
        if: success()
        uses: actions/checkout@v1
      - name: build
        if: success()
        run: make build-hubd
  buf:
    name: Buf
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: success()
        uses: actions/checkout@v1
        with:
          ref: master
      - name: checkout-master
        if: success()
        run: git checkout master
      - name: checkout
        if: success()
        uses: actions/checkout@v1
      - name: make local
        if: success()
        run: make buf-local
